# -*- coding: utf-8 -*-
"""Integra l'ordine CQ in docs/STATO_VIVO.md, nella sezione giusta."""
NL = chr(10)
P = 'docs/STATO_VIVO.md'

VOCE = (
    "0untriginta. **L'ORDINE CQ, LE REGRESSIONI DEL TELEFONO E IL CAMMINO CHE "
    "MURAVA. 3 e 4 settembre 2026.** Manifesto "
    "`docs/ordini/ORDINE_CQ_MANIFESTO.md`, prova del rosso "
    "`docs/ordini/CQ_prova_del_rosso.txt`, guardie "
    "`test/ordine_cq_guard_test.dart` e "
    "`test/i_manifesti_sono_sigillati_test.dart`. **Trentadue voci: ventidue "
    "chiuse, quattro fermate, SEI aperte, tutte del pezzo secondo.** "
    "**REGOLA ZERO: tre premesse verificate e cadute.** Il \"trenta gettate\" "
    "che nessuna lettura del piano spiegava e' il tetto dell'Adepto, e le ore "
    "degli screenshot lo dicono: le Rune col 29 su 30 sono delle 20:09, i "
    "Piani con l'Illuminato attivo sono delle 20:13, quattro minuti DOPO. La "
    "runa rovesciata una lettura ce l'ha, misurato su tutte e ventiquattro le "
    "rune nei due versi e su 93 sere di Tramonto. Il Tramonto non ha il "
    "difetto dell'Arcano: compone la sua chiave con la nascita intera. "
    "**IL DIFETTO PIU' GROSSO NON ERA NELL'ORDINE, ED E' USCITO DA UNA "
    "MISURA CHE L'ORDINE CHIEDEVA DI FARE.** La voce 2.12 chiedeva di provare "
    "il difetto prima di curarlo: su quattrocento giorni di uso onesto con "
    "dodici arti al giorno, **112 traguardi soddisfatti e TREDICI accesi**, "
    "con 99 gradini gia' guadagnati che non si accendevano mai e i tre "
    "sentieri fermi su arti che chi fa i Doni del giorno non tocca. **La "
    "scala dell'ordine CP voce 01 non ritardava, murava.** Con la voce 2.13 "
    "il tetto si e' spostato dalla maturazione alla SCENA: adesso 112 su 112, "
    "ritardo zero, i sentieri accendono 36, 39 e 37 gradini invece di 4, 6 e "
    "3, e il giorno peggiore dell'anno resta a TRE feste. **IL PIANO VIVEVA "
    "IN DUE POSTI CHE NON SI PARLAVANO**: il telefono e "
    "`users/<uid>/stato/abbonamento.piano`, che nessuno scriveva e valeva "
    "free per tutti; adesso c'e' la callable `attivaIlPianoInDemo`, che nasce "
    "chiusa a chiave e aspetta il PASSO 7 dal PC del fondatore. **LE PUSH NON "
    "SONO MAI PARTITE**: ventitre chiamate, ventitre 400, e la raccolta "
    "`push_dei_doni` che non esiste. Dei tre controlli scattava il secondo, "
    "il fuso: il telefono mandava `CEST` e il server pretende `Area/Citta`. "
    "**IL SUONO DELLA CARTA NON USCIVA per due difetti gia' misurati nella "
    "coda dell'ordine CN e curati sulla sola musica**: `play` di audioplayers "
    "non e' una chiamata che finisce, e il lettore chiedeva il fuoco audio "
    "esclusivo che la musica non molla. **NESSUN SUONO CHE IL FONDATORE NON "
    "ABBIA SCELTO**: ogni comando Material chiamava il ritorno di sistema, e "
    "in tutta l'app non c'era un solo `enableFeedback` scritto, su "
    "trentatre InkWell e su tutti i pulsanti del tema; nessuna guardia lo "
    "aveva mai visto perche' il click di sistema non e' un file negli asset. "
    "**I CARATTERI, LA QUARTA VOLTA**: il ruolo `etichetta` valeva DODICI "
    "punti in duecentotre posti, e il commento accanto diceva \"vale "
    "esattamente il pavimento\" senza scrivere quanto fosse; il censimento "
    "guardava le schermate e non i ruoli. Adesso quattordici, e la barra del "
    "Santuario resta a dodici per non restituire otto dei ventidue punti che "
    "l'ordine CF le aveva tolto. **L'ALBA E IL SOFFIO davano risposte "
    "identiche perche' erano lo stesso oggetto**: il Soffio chiamava il rito "
    "dell'Alba con la sola data. **L'ARCANO non era individuale**: nel seme "
    "entrava il solo numero della carta natale, da uno a ventidue, quindi due "
    "persone con la stessa carta natale vedevano lo stesso Arcano per sempre. "
    "**VIA IL RITO ANNUNCIATO CHE NON ESISTE** da tutte e quattro le "
    "schermate, e il componente e' stato cancellato, non solo smontato. "
    "**L'AGGIUNTA CQ4, I MANIFESTI NON SIGILLATI.** Il Collaudatore degli "
    "Ordini prende solo manifesti terminali e sigillati: CM, CN, CO e CP non "
    "lo erano, quindi li saltava e collaudava ordini di settimane fa mentre i "
    "quattro piu' recenti non passavano da nessun controllo. Adesso sono "
    "sigillati con gli stati VERI: **cinque voci dell'ordine CO non sono "
    "CHIUSE**, fra cui CO.07 che ha bloccato la scelta delle carte e CO.20 "
    "che ha spostato il cuore invece di centrarlo, e CP.01 nemmeno. CG chiude "
    "tutte e sedici le voci. **REGOLA F, nuova**: un ordine non e' finito "
    "finche' il suo manifesto non e' sigillato coi marcatori terminali, e una "
    "guardia di famiglia resta rossa finche' un ordine lascia una voce "
    "aperta. **I NUMERI: sedici guardie nuove, quarantatre innesti provati e "
    "quarantatre rossi, ventisette guardie esistenti viste rosse prima o "
    "durante il lavoro.** Registro da 261 a 277 guardie, viste rosse da 46 a "
    "59, dal 17,6 al 21,3 per cento.")


testo = open(P, encoding='utf-8').read()
assert '0untriginta.' not in testo, 'la voce c e gia'
ancora = "0tricies. **L'ORDINE CP,"
assert testo.count(ancora) == 1
testo = testo.replace(ancora, VOCE + NL + NL + ancora)
open(P, 'w', encoding='utf-8', newline=NL).write(testo)
print('VOCE CQ integrata, prima di quella dell ordine CP')
