# -*- coding: utf-8 -*-
"""I CENTOSESSANTACINQUE GRADINI, revisione F. Ordine CP voce 05.

Ogni voce e' `(condizione, nome, porta_che_apre)`. **La frase che la persona
legge NON sta qui**: si compone dalla condizione in `genera_corpus_f.py`, cosi'
non puo' contraddirla. E' la stessa ragione per cui la condizione non si deduce
piu' dal testo, applicata dall'altro capo.

**I costi in giorni salgono e non scendono mai** lungo un sentiero, e dove due
gradini costano uguale nominano gesti diversi: un solo evento non puo' farli
maturare insieme, ed e' la regola 2 del fondatore resa misura.

**Un solo gradino per sentiero costa un giorno**, ed e' il primo: tre feste
nella prima sessione, una per Maestro, e non una di piu'. Tutti e tre sono un
pezzo dell'identita', perche' il primo gradino di un cammino deve dire chi sei,
non quanto sei stato bravo.

Le regole che governano questo file stanno in `docs/regole_dei_traguardi.md`.
"""
from corpus_traguardi import (arco, cielo, giornate, ora, pezzo, stessaOra,
                              volte)

# ---------------------------------------------------------------------------
# LA COSTELLAZIONE, Medora. Arti: carta natale, Ascendente, Oroscopo, stesa,
# Arcano del Giorno, Sinastria VIP, Angelo Custode.
# ---------------------------------------------------------------------------
COSTELLAZIONE = [
    # --- Primi giorni, da 1 a 8 ---
    (pezzo('carta_natale'), 'Il cielo dell’istante',
     'Il Cosmic Passport, che senza carta natale resta un documento vuoto'),
    (volte('oroscopo', 2), 'Il cielo di domani',
     'Gli orizzonti dell’Oroscopo: giorno, settimana, mese'),
    (volte('stesa', 2), 'Le tre carte',
     'Le domande della stesa, che cambiano le carte che escono'),
    (volte('oracolo', 3), 'L’Arcano che torna',
     'Il filo fra gli Arcani, che si vede solo dal terzo giorno'),
    (volte('sinastria', 3), 'I cieli degli altri',
     'La galleria dei cinquanta volti della Sinastria'),
    (giornate(['oroscopo', 'stesa'], 4), 'Il cielo e le carte',
     'La lettura incrociata, dove il cielo del giorno spiega la carta uscita'),
    (volte('angelo_custode', 4), 'I tre Angeli',
     'I settantadue Angeli dello Shem HaMephorash'),
    (volte('oracolo', 5), 'La settimana dell’Arcano',
     'Lo storico degli Arcani, che comincia a dire qualcosa'),
    (volte('ascendente', 5), 'Il segno che sale',
     'Le dodici case, che senza Ascendente non esistono'),
    (arco('oracolo', 6, 8), 'La costanza dell’Arcano',
     'Il promemoria dell’Arcano, che da qui sceglie la tua ora'),
    (cielo('primo_quarto', 'stesa'), 'Le carte al primo quarto',
     'Il calendario lunare del Cerchio, con le fasi che verranno'),
    # --- Prima settimana, da 9 a 30 ---
    (ora('oracolo', 'alba', 9), 'L’Arcano all’alba',
     'Le ore rituali, che il Cerchio calcola sul tuo luogo vero'),
    (arco('oracolo', 10, 14), 'Dieci Arcani in quattordici giorni',
     'Il diario del Cammino, con i giorni segnati uno per uno'),
    (volte('stesa', 12), 'Le carte che tornano',
     'Le coincidenze delle carte, che il Cerchio comincia a notare'),
    (stessaOra('oracolo', 14), 'L’ora fedele',
     'L’appuntamento con Medora, che da qui ti aspetta a quell’ora'),
    (cielo('luna_piena', 'ascendente'), 'L’Ascendente sotto la Luna piena',
     'La lettura lunare dell’Ascendente, che vale solo a Luna piena'),
    (giornate(['oroscopo', 'stesa', 'sinastria'], 16), 'Le tre letture',
     'Il responso composto, dove le tre arti si parlano'),
    (arco('oracolo', 18, 25), 'Diciotto Arcani in venticinque giorni',
     'La costanza larga, che perdona un giorno saltato'),
    (volte('oracolo', 20), 'Venti Arcani',
     'La mappa degli Arcani incontrati, con quelli che mancano'),
    (volte('oroscopo', 25), 'Il cielo interrogato',
     'Le previsioni lunghe dell’Oroscopo, mese e stagione'),
    (cielo('luna_nel_tuo_segno', 'angelo_custode'),
     'L’Angelo sotto la tua Luna',
     'Il tuo Angelo del cuore, che si rivela con la Luna nel tuo segno'),
    (cielo('transito_sulla_luna', 'stesa'), 'Le carte sotto un transito',
     'Il registro dei transiti, con quelli che ti aspettano'),
    # --- Primo mese, da 31 a 90 ---
    (volte('stesa', 31), 'Un mese di stese',
     'Le stese lunghe, con la croce celtica a dieci carte'),
    (arco('oracolo', 35, 45), 'Trentacinque Arcani in quarantacinque giorni',
     'Il tuo Arcano dominante, che si calcola solo con questa storia'),
    (giornate(['oracolo', 'oroscopo'], 40), 'Quaranta giorni compiuti',
     'La lettura del mattino, che unisce Arcano e cielo del giorno'),
    (cielo('transito_sull_ascendente', 'oroscopo'),
     'Il cielo sul tuo Ascendente',
     'Le soglie della vita, che i transiti sull’Ascendente aprono'),
    (cielo('transito_sul_sole', 'stesa'), 'Le carte sul tuo Sole',
     'Il ritratto solare, che si legge solo sotto il transito'),
    (volte('sinastria', 55), 'Cinquantacinque confronti',
     'La classifica delle affinità, con i volti più vicini al tuo cielo'),
    (cielo('mercurio_retrogrado', 'oracolo'), 'L’Arcano di Mercurio',
     'Il quaderno dei ripensamenti, che si apre solo a Mercurio retrogrado'),
    (giornate(['sinastria', 'stesa', 'oroscopo'], 60), 'Sessanta giorni pieni',
     'La sintesi di stagione, che Medora scrive su sessanta giornate'),
    (volte('oroscopo', 75), 'Settantacinque cieli',
     'Il confronto fra il tuo anno e il cielo che l’ha attraversato'),
    (arco('oracolo', 80, 100), 'Ottanta Arcani in cento giorni',
     'La costanza riconosciuta, che Medora nomina nelle sue risposte'),
    (cielo('eclissi', 'stesa'), 'Le carte dell’eclissi',
     'La lettura dell’eclissi, che il Cerchio conserva per sempre'),
    # --- La stagione, da 91 a 190 ---
    (cielo('solstizio', 'oroscopo'), 'Il cielo del solstizio',
     'Il rito del solstizio, che torna due volte l’anno'),
    (volte('stesa', 100), 'Cento stese',
     'Lo Specchio delle carte, che confronta cento letture'),
    (arco('oracolo', 110, 140), 'Centodieci Arcani in centoquaranta giorni',
     'La memoria lunga di Medora, che ricorda quello che dicevi a marzo'),
    (cielo('mercurio_diretto', 'stesa'), 'Le carte di Mercurio diretto',
     'La lettura del ritorno, quando Mercurio riprende il cammino'),
    (cielo('giove_retrogrado', 'oroscopo'), 'Il cielo di Giove retrogrado',
     'Il capitolo della fortuna che si ripiega, raro e lungo'),
    (volte('oracolo', 140), 'Centoquaranta Arcani',
     'Il tuo mazzo personale, con gli Arcani che ti cercano più spesso'),
    (giornate(['oroscopo', 'stesa', 'oracolo', 'sinastria'], 150),
     'Centocinquanta giornate intere',
     'Il ritratto delle quattro arti, che nessuna delle quattro dice da sola'),
    (arco('oracolo', 160, 200), 'Centosessanta Arcani in duecento giorni',
     'La stagione riconosciuta, con il tuo Arcano dell’anno'),
    (volte('sinastria', 165), 'Centosessantacinque volti',
     'La mappa delle affinità, con i cieli che assomigliano al tuo'),
    (stessaOra('oracolo', 170), 'L’ora che non cambia',
     'Il tuo rito fisso, che Medora protegge dalle notifiche'),
    (cielo('sole_nel_tuo_segno', 'stesa'), 'Le carte del tuo Sole',
     'Il mese del compleanno, con la stesa che si legge una volta l’anno'),
    # --- L'anno, da 191 a 365 ---
    (volte('stesa', 191), 'Centonovantuno stese',
     'L’archivio completo delle tue stese, ricercabile per carta'),
    (arco('oracolo', 200, 250), 'Duecento Arcani in duecentocinquanta giorni',
     'Il capitolo dell’anno, che Medora scrive solo per chi c’è stato'),
    (giornate(['oracolo', 'sinastria', 'ascendente'], 220),
     'Duecentoventi giornate di lettura',
     'La lettura a tre voci, dove Arcano, volto e Ascendente si spiegano'),
    (cielo('giove_diretto', 'oroscopo'), 'Il cielo di Giove diretto',
     'Il capitolo dell’espansione, che apre l’anno che viene'),
    (cielo('saturno_diretto', 'stesa'), 'Le carte di Saturno diretto',
     'La lettura della prova superata, che Saturno concede tornando diretto'),
    (volte('oroscopo', 280), 'Duecentottanta cieli',
     'Il tuo anno confrontato col cielo, giorno per giorno'),
    (cielo('venere_retrograda', 'sinastria'),
     'La Sinastria di Venere retrograda',
     'Il capitolo degli affetti che tornano, uno ogni diciotto mesi'),
    (arco('oracolo', 300, 340), 'Trecento Arcani in trecentoquaranta giorni',
     'Il titolo di custode dell’Arcano, che pochi vedranno'),
    (giornate(['oroscopo', 'stesa', 'sinastria', 'oracolo',
               'angelo_custode'], 320), 'Trecentoventi giornate complete',
     'La Costellazione intera, con tutte e cinque le arti in una pagina'),
    (volte('stesa', 340), 'Trecentoquaranta stese',
     'Il mazzo che ti conosce, con la carta che ti è uscita di più'),
    (cielo('ritorno_solare', 'oroscopo'), 'Il tuo ritorno solare',
     'La carta del ritorno solare, il cielo del tuo anno nuovo'),
]

# ---------------------------------------------------------------------------
# IL FIORE DI LOTO, Aura. Arti: Costellazione del Viso, Rito dell'Alba, Soffio
# del Destino, Archetipo, Meditazione, Due Volti.
# ---------------------------------------------------------------------------
LOTO = [
    # --- Primi giorni ---
    (pezzo('viso'), 'Il tuo volto letto',
     'La Costellazione del Viso, che da qui entra nel tuo profilo'),
    (volte('alba', 2), 'Due albe',
     'La parola del giorno, che cambia con l’ora in cui ti alzi'),
    (volte('soffio', 2), 'Due Soffi',
     'Il respiro contato, con il ritmo che Aura ti propone'),
    (volte('archetipo', 3), 'Il tuo Archetipo',
     'I dodici Archetipi, con quello che ti governa'),
    (volte('meditazione', 3), 'Tre meditazioni',
     'Le meditazioni guidate lunghe, dai sette minuti in su'),
    (giornate(['alba', 'soffio'], 4), 'L’alba e il respiro',
     'Il rito del mattino completo, alba e Soffio uno dopo l’altro'),
    (volte('due_volti', 4), 'I tuoi due volti',
     'Il confronto fra il volto che mostri e quello che sei'),
    (arco('soffio', 5, 7), 'Cinque Soffi in sette giorni',
     'Il grafico del respiro, che senza cinque giorni non dice niente'),
    (volte('meditazione', 5), 'Cinque meditazioni',
     'Le meditazioni sui chakra, una per centro'),
    (arco('alba', 6, 8), 'La costanza dell’Alba',
     'Il promemoria dell’Alba, che da qui sceglie la tua ora'),
    (cielo('primo_quarto', 'alba'), 'L’Alba al primo quarto',
     'Il calendario lunare del Cerchio, con le fasi che verranno'),
    # --- Prima settimana ---
    (ora('alba', 'alba', 9), 'L’Alba nella sua ora',
     'Le ore rituali, che il Cerchio calcola sul tuo luogo vero'),
    (arco('soffio', 10, 14), 'Dieci Soffi in quattordici giorni',
     'Il diario del respiro, con i giorni segnati uno per uno'),
    (volte('viso', 12), 'Il volto che cambia',
     'Il confronto fra la prima lettura del viso e l’ultima'),
    (stessaOra('alba', 14), 'L’ora fedele dell’Alba',
     'L’appuntamento con Aura, che da qui ti aspetta a quell’ora'),
    (cielo('luna_piena', 'soffio'), 'Il Soffio sotto la Luna piena',
     'Il respiro lunare, che si pratica solo a Luna piena'),
    (giornate(['alba', 'soffio', 'meditazione'], 16), 'Le tre pratiche',
     'La sequenza del risveglio, dove le tre pratiche si tengono'),
    (arco('alba', 18, 25), 'Diciotto albe in venticinque giorni',
     'La costanza larga, che perdona un giorno saltato'),
    (volte('archetipo', 20), 'Venti Archetipi',
     'Il tuo Archetipo in movimento, che cambia col tempo'),
    (volte('due_volti', 25), 'Venticinque confronti',
     'La storia dei tuoi volti, mese per mese'),
    (cielo('luna_nel_tuo_segno', 'viso'), 'Il Viso sotto la tua Luna',
     'La lettura lunare del volto, che vale solo nel tuo segno'),
    (cielo('transito_sulla_luna', 'alba'), 'L’Alba sotto un transito',
     'Il registro dei transiti, con quelli che ti aspettano'),
    # --- Primo mese ---
    (volte('soffio', 31), 'Un mese di Soffi',
     'Il respiro profondo, la pratica lunga da undici minuti'),
    (arco('alba', 35, 45), 'Trentacinque albe in quarantacinque giorni',
     'Il tuo ritmo del mattino, che si calcola solo con questa storia'),
    (giornate(['alba', 'meditazione'], 40), 'Quaranta mattine intere',
     'La meditazione dell’alba, che si sblocca con la costanza'),
    (cielo('transito_sull_ascendente', 'alba'), 'L’Alba sul tuo Ascendente',
     'Le soglie della vita, che i transiti sull’Ascendente aprono'),
    (cielo('transito_sul_sole', 'soffio'), 'Il Soffio sul tuo Sole',
     'Il respiro solare, che si pratica solo sotto il transito'),
    (volte('viso', 55), 'Cinquantacinque letture del volto',
     'La mappa completa dei tratti, con quelli che si sono mossi'),
    (cielo('mercurio_retrogrado', 'archetipo'),
     'L’Archetipo di Mercurio retrogrado',
     'L’Archetipo dell’ombra, che si mostra solo a Mercurio retrogrado'),
    (giornate(['soffio', 'viso', 'due_volti'], 60), 'Sessanta giorni pieni',
     'Il ritratto energetico, che unisce respiro e volto'),
    (volte('alba', 75), 'Settantacinque albe',
     'Il confronto fra le tue albe e le stagioni che le hanno viste'),
    (arco('soffio', 80, 100), 'Ottanta Soffi in cento giorni',
     'La costanza riconosciuta, che Aura nomina nelle sue risposte'),
    (cielo('eclissi', 'alba'), 'L’Alba dell’eclissi',
     'Il rito dell’eclissi, che il Cerchio conserva per sempre'),
    # --- La stagione ---
    (cielo('solstizio', 'soffio'), 'Il Soffio del solstizio',
     'Il respiro del solstizio, che torna due volte l’anno'),
    (volte('alba', 100), 'Cento albe',
     'Lo Specchio del mattino, che confronta cento risvegli'),
    (arco('soffio', 110, 140), 'Centodieci Soffi in centoquaranta giorni',
     'La memoria lunga di Aura, che ricorda come respiravi a marzo'),
    (cielo('mercurio_diretto', 'alba'), 'L’Alba di Mercurio diretto',
     'Il rito del ritorno, quando Mercurio riprende il cammino'),
    (cielo('giove_retrogrado', 'soffio'), 'Il Soffio di Giove retrogrado',
     'Il capitolo dell’abbondanza che si ripiega, raro e lungo'),
    (volte('meditazione', 140), 'Centoquaranta meditazioni',
     'Le meditazioni che Aura scrive per te, non più dal catalogo'),
    (giornate(['alba', 'soffio', 'viso', 'archetipo'], 150),
     'Centocinquanta giornate intere',
     'Il ritratto delle quattro pratiche, che nessuna dice da sola'),
    (arco('alba', 160, 200), 'Centosessanta albe in duecento giorni',
     'La stagione riconosciuta, con il tuo risveglio dell’anno'),
    (volte('archetipo', 165), 'Centosessantacinque Archetipi',
     'La storia del tuo Archetipo, con tutte le sue mutazioni'),
    (stessaOra('alba', 170), 'L’ora che non cambia',
     'Il tuo rito fisso, che Aura protegge dalle notifiche'),
    (cielo('sole_nel_tuo_segno', 'soffio'), 'Il Soffio del tuo Sole',
     'Il mese del compleanno, col respiro che si pratica una volta l’anno'),
    # --- L'anno ---
    (volte('alba', 191), 'Centonovantuna albe',
     'L’archivio completo delle tue albe, con la parola di ogni giorno'),
    (arco('soffio', 200, 250), 'Duecento Soffi in duecentocinquanta giorni',
     'Il capitolo dell’anno, che Aura scrive solo per chi c’è stato'),
    (giornate(['alba', 'archetipo', 'due_volti'], 220),
     'Duecentoventi giornate di pratica',
     'Il ritratto lungo di Aura, che tiene insieme risveglio, Archetipo e '
     'volti'),
    (cielo('giove_diretto', 'alba'), 'L’Alba di Giove diretto',
     'Il capitolo dell’espansione, che apre l’anno che viene'),
    (cielo('saturno_diretto', 'soffio'), 'Il Soffio di Saturno diretto',
     'Il respiro della prova superata, che Saturno concede tornando diretto'),
    (volte('viso', 280), 'Duecentottanta volti',
     'Il tuo volto nel tempo, con la lettura di come è cambiato'),
    (cielo('venere_retrograda', 'due_volti'),
     'I Due Volti di Venere retrograda',
     'Il capitolo degli affetti che tornano, uno ogni diciotto mesi'),
    (arco('alba', 300, 340), 'Trecento albe in trecentoquaranta giorni',
     'Il titolo di custode dell’Alba, che pochi vedranno'),
    (giornate(['alba', 'soffio', 'viso', 'archetipo', 'meditazione',
               'due_volti'], 320), 'Trecentoventi giornate complete',
     'Il Fiore intero, con tutte e sei le pratiche in una sola pagina'),
    (volte('soffio', 340), 'Trecentoquaranta Soffi',
     'Il respiro che ti conosce, col ritmo che il tuo corpo ha scelto'),
    (cielo('ritorno_solare', 'alba'), 'Il tuo ritorno solare',
     'Il rito del ritorno solare, il risveglio del tuo anno nuovo'),
]

# ---------------------------------------------------------------------------
# L'ALBERO DELLA VITA, Caligo. Arti: Animale Guida, gettata di rune, Runa del
# Tramonto, Sigillo del Sogno, Sigillo d'Intenzione, runa girata, Bosco.
# ---------------------------------------------------------------------------
ALBERO = [
    # --- Primi giorni ---
    (pezzo('animale_guida'), 'Il tuo Animale Guida',
     'I dodici Animali Guida, con il tuo fra loro'),
    (volte('gettata', 2), 'Due gettate',
     'I modi della gettata: una runa, tre rune, la croce'),
    (volte('tramonto', 2), 'Due tramonti',
     'La Runa del Tramonto, che cambia con l’ora vera del tuo luogo'),
    (volte('sogno', 3), 'Tre notti',
     'Il Sigillo del Sogno, col quaderno che lo raccoglie'),
    (volte('sigillo', 3), 'Tre Sigilli',
     'Il Sigillo d’Intenzione, che si incide e si custodisce'),
    (giornate(['tramonto', 'sogno'], 4), 'Il tramonto e la notte',
     'Il rito della sera completo, dalla runa al sigillo del sonno'),
    (volte('runa_girata', 4), 'Quattro pietre girate',
     'Le ventiquattro rune dell’Elder Futhark, una per una'),
    (volte('bosco', 5), 'Cinque passi nel Bosco',
     'Il Bosco del Cerchio, che cresce con chi lo attraversa'),
    (arco('gettata', 5, 7), 'Cinque gettate in sette giorni',
     'Lo storico delle gettate, che senza cinque giorni non dice niente'),
    (arco('tramonto', 6, 8), 'La costanza del Tramonto',
     'Il promemoria del Tramonto, che da qui segue l’ora vera'),
    (cielo('primo_quarto', 'gettata'), 'La gettata al primo quarto',
     'Il calendario lunare del Cerchio, con le fasi che verranno'),
    # --- Prima settimana ---
    (ora('tramonto', 'tramonto', 9), 'Il Tramonto nella sua ora',
     'Le ore rituali, che il Cerchio calcola sul tuo luogo vero'),
    (arco('sogno', 10, 14), 'Dieci notti in quattordici giorni',
     'Il quaderno dei sogni, con i giorni segnati uno per uno'),
    (volte('gettata', 12), 'Dodici gettate',
     'Le rune che tornano, che il Cerchio comincia a notare'),
    (stessaOra('tramonto', 14), 'L’ora fedele del Tramonto',
     'L’appuntamento con Caligo, che da qui ti aspetta a quell’ora'),
    (cielo('luna_nuova', 'gettata'), 'La gettata della Luna nuova',
     'La gettata dei cominciamenti, che vale solo a Luna nuova'),
    (giornate(['gettata', 'tramonto', 'sogno'], 16), 'I tre riti di Caligo',
     'Il responso composto, dove gettata, runa e sogno si parlano'),
    (arco('tramonto', 18, 25), 'Diciotto tramonti in venticinque giorni',
     'La costanza larga, che perdona un giorno saltato'),
    (volte('sigillo', 20), 'Venti Sigilli',
     'La raccolta dei tuoi Sigilli, con quelli che si sono compiuti'),
    (volte('bosco', 25), 'Venticinque passi nel Bosco',
     'Le radure del Bosco, che si aprono solo a chi torna'),
    (cielo('luna_nel_segno_opposto', 'sogno'), 'Il Sogno nel segno opposto',
     'Il sogno dell’ombra, che la Luna opposta porta a galla'),
    (cielo('transito_sulla_luna', 'tramonto'),
     'Il Tramonto sotto un transito',
     'Il registro dei transiti, con quelli che ti aspettano'),
    # --- Primo mese ---
    (volte('sogno', 31), 'Un mese di notti',
     'La lettura dei sogni ricorrenti, che serve un mese per vedere'),
    (arco('tramonto', 35, 45), 'Trentacinque tramonti in quarantacinque giorni',
     'La tua runa dominante, che si calcola solo con questa storia'),
    (giornate(['gettata', 'runa_girata'], 40), 'Quaranta giorni di pietra',
     'La lettura incrociata, dove la runa girata spiega la gettata'),
    (cielo('transito_sull_ascendente', 'sigillo'),
     'Il Sigillo sul tuo Ascendente',
     'Le soglie della vita, che i transiti sull’Ascendente aprono'),
    (cielo('transito_sul_sole', 'gettata'), 'La gettata sul tuo Sole',
     'La gettata solare, che si tira solo sotto il transito'),
    (volte('runa_girata', 55), 'Cinquantacinque pietre girate',
     'Le rune che non ti sono mai uscite, con la domanda del perché'),
    (cielo('mercurio_retrogrado', 'tramonto'),
     'Il Tramonto di Mercurio retrogrado',
     'La runa del ripensamento, che esce solo a Mercurio retrogrado'),
    (giornate(['gettata', 'sigillo', 'bosco'], 60), 'Sessanta giorni pieni',
     'Il ritratto runico, che unisce gettata, intenzione e Bosco'),
    (volte('tramonto', 75), 'Settantacinque tramonti',
     'Il confronto fra le tue sere e le stagioni che le hanno viste'),
    (arco('sogno', 80, 100), 'Ottanta notti in cento giorni',
     'La costanza riconosciuta, che Caligo nomina nelle sue risposte'),
    (cielo('eclissi', 'gettata'), 'La gettata dell’eclissi',
     'La gettata dell’eclissi, che il Cerchio conserva per sempre'),
    # --- La stagione ---
    (cielo('equinozio', 'tramonto'), 'Il Tramonto dell’equinozio',
     'Il rito dell’equinozio, che torna due volte l’anno'),
    (volte('gettata', 100), 'Cento gettate',
     'Lo Specchio delle rune, che confronta cento gettate'),
    (arco('tramonto', 110, 140), 'Centodieci tramonti in centoquaranta giorni',
     'La memoria lunga di Caligo, che ricorda le tue rune di marzo'),
    (cielo('mercurio_diretto', 'gettata'), 'La gettata di Mercurio diretto',
     'La gettata del ritorno, quando Mercurio riprende il cammino'),
    (cielo('saturno_retrogrado', 'sogno'), 'Il Sogno di Saturno retrogrado',
     'Il sogno della prova, che Saturno retrogrado porta con sé'),
    (volte('runa_girata', 140), 'Centoquaranta pietre girate',
     'Il tuo mazzo di rune, con quelle che ti cercano più spesso'),
    (giornate(['gettata', 'tramonto', 'sogno', 'sigillo'], 150),
     'Centocinquanta giornate intere',
     'Il ritratto dei quattro riti, che nessuno dei quattro dice da solo'),
    (arco('sogno', 160, 200), 'Centosessanta notti in duecento giorni',
     'La stagione riconosciuta, con il tuo sogno dell’anno'),
    (volte('bosco', 165), 'Centosessantacinque passi nel Bosco',
     'Il cuore del Bosco, dove si arriva solo a piedi'),
    (stessaOra('tramonto', 170), 'L’ora che non cambia',
     'Il tuo rito fisso, che Caligo protegge dalle notifiche'),
    (cielo('tre_transiti_insieme', 'gettata'), 'La gettata dei tre transiti',
     'La lettura dei nodi, quando tre transiti si affacciano insieme'),
    # --- L'anno ---
    (volte('tramonto', 191), 'Centonovantuno tramonti',
     'L’archivio completo delle tue sere, con la runa di ogni giorno'),
    (arco('sogno', 200, 250), 'Duecento notti in duecentocinquanta giorni',
     'Il capitolo dell’anno, che Caligo scrive solo per chi c’è stato'),
    (giornate(['gettata', 'sogno', 'animale_guida'], 220),
     'Duecentoventi giornate di bosco',
     'Il legame con l’Animale, che si stringe solo con gli anni'),
    (cielo('giove_diretto', 'sigillo'), 'Il Sigillo di Giove diretto',
     'Il capitolo dell’espansione, che apre l’anno che viene'),
    (cielo('saturno_diretto', 'gettata'), 'La gettata di Saturno diretto',
     'La gettata della prova superata, che Saturno concede tornando diretto'),
    (volte('sogno', 280), 'Duecentottanta notti',
     'Il tuo anno di sogni, con i temi che sono tornati'),
    (cielo('venere_diretta', 'animale_guida'),
     'L’Animale di Venere diretta',
     'Il capitolo del legame ritrovato, uno ogni diciotto mesi'),
    (arco('tramonto', 300, 340), 'Trecento tramonti in trecentoquaranta giorni',
     'Il titolo di custode del Tramonto, che pochi vedranno'),
    (giornate(['gettata', 'tramonto', 'sogno', 'sigillo', 'runa_girata',
               'bosco'], 320), 'Trecentoventi giornate complete',
     'L’Albero intero, con tutti e sei i riti in una sola pagina'),
    (volte('gettata', 340), 'Trecentoquaranta gettate',
     'Le rune che ti conoscono, con quella che ti è uscita di più'),
    (cielo('luna_piena_nel_tuo_segno', 'tramonto'),
     'Il Tramonto della tua Luna piena',
     'La runa della Luna piena nel tuo segno, una volta l’anno'),
]

SENTIERI = [
    ('costellazione', 'Costellazione personale', 'Medora', 'med',
     COSTELLAZIONE,
     ['LA COSTELLAZIONE NASCENTE', 'LA COSTELLAZIONE DELLA LETTURA',
      'LA COSTELLAZIONE DEL CIELO VERO', 'LA COSTELLAZIONE DELLA STAGIONE',
      'LA COSTELLAZIONE COMPIUTA']),
    ('loto', 'Fiore di Loto', 'Aura', 'aur', LOTO,
     ['IL PRIMO PETALO', 'LA PRIMA FIORITURA', 'IL FIORE CHE RESPIRA',
      'IL FIORE DELLA STAGIONE', 'IL FIORE COMPIUTO']),
    ('albero', 'Albero della Vita', 'Caligo', 'cal', ALBERO,
     ['MALKUTH, IL REGNO', 'YESOD, IL FONDAMENTO', 'TIPHERETH, LA BELLEZZA',
      'CHESED, LA MISERICORDIA', 'KETHER, LA CORONA']),
]
