// GENERATO DA tool/genera_sentieri_dal_corpus.py: NON SI SCRIVE
// A MANO. Ordine AR voce 02.
//
// La fonte e' docs/corpus/Traguardi_165_Revisione_E.json, e il
// dato comanda: nomi, condizioni, fasce, Eos e porte vengono da
// li' verbatim. Per cambiare un traguardo si cambia il corpus e
// si rigenera, mai il contrario.

import 'eventi_del_cielo.dart';
import 'traguardo.dart';

final List<Traguardo> sentieroDelLoto = [
  Traguardo(
    id: 'aur_1',
    nome: 'Hai ricevuto il primo Soffio',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('soffio', 1),
    frase: 'Compi il tuo primo Soffio del Destino.',
    posizione: 1,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Il Rito dell\'Alba',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Prima volta',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_2',
    nome: 'Il primo mattino',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('alba', 1),
    frase: 'Compi il tuo primo Rito dell\'Alba.',
    posizione: 2,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Il dono del mattino',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Prima volta',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_3',
    nome: 'Il tuo nome nel Cerchio',
    famiglia: FamigliaDelTraguardo.identita,
    condizione: const PezzoDellIdentita('nome_proprio'),
    frase: 'Il tuo nome proprio entra nel profilo e Aura comincia a chiamarti.',
    posizione: 3,
    percheConta: FamigliaDelTraguardo.identita.percheContaLaFamiglia,
    cosaApre: 'Le letture che ti chiamano per nome',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Identità',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_4',
    nome: 'Sai quale archetipo ti somiglia',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('archetipo', 1),
    frase: 'Scopri il tuo archetipo.',
    posizione: 4,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'La lettura archetipica del giorno',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Prima volta',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_5',
    nome: 'Il tuo volto letto',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('viso', 1),
    frase: 'La Costellazione del Viso legge i tuoi tratti per la prima volta.',
    posizione: 5,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'La scheda dei tuoi tratti',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Prima volta',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_6',
    nome: 'Il primo petalo condiviso',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const GestoDelCerchio('condivisione_petalo', 1),
    frase: 'Condividi pubblicamente un responso di Aura.',
    posizione: 6,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'Il bonus della condivisione',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Legame',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_7',
    nome: 'Il soffio che dura',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const VarietaDelDettaglio('soffio', 'tenuto', 1),
    frase: 'Un Soffio del Destino tenuto fino alla fine senza interrompersi.',
    posizione: 7,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'La misura del tuo respiro',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Profondità',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_8',
    nome: 'La tua Luna di nascita',
    famiglia: FamigliaDelTraguardo.identita,
    condizione: const PezzoDellIdentita('luna_natale'),
    frase: 'La Luna della tua carta entra nel profilo e le letture la usano.',
    posizione: 8,
    percheConta: FamigliaDelTraguardo.identita.percheContaLaFamiglia,
    cosaApre: 'Le letture lunari personali',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Identità',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_9',
    nome: 'Il mattino aperto',
    famiglia: FamigliaDelTraguardo.giornata,
    condizione: const GestiNelloStessoGiorno(['soffio', 'alba']),
    frase: 'Un Rito dell\'Alba e un Soffio del Destino nello stesso giorno.',
    posizione: 9,
    percheConta: FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
    cosaApre: 'Il riepilogo della giornata nel Journal',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Coincidenza',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_10',
    nome: 'Il tuo numero',
    famiglia: FamigliaDelTraguardo.identita,
    condizione: const PezzoDellIdentita('numero_della_vita'),
    frase: 'Scopri nel Passaporto il Numero che ti accompagna.',
    posizione: 10,
    percheConta: FamigliaDelTraguardo.identita.percheContaLaFamiglia,
    cosaApre: 'La lettura numerologica del giorno',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Identità',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_11',
    nome: 'LA PRIMA FIORITURA',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GradiniAlleSpalle('loto', 10),
    frase: 'Dieci gradini qualunque del Loto alle spalle.',
    posizione: 11,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il respiro guidato dalla voce di Aura',
    eGrande: true,
    eos: 40,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Perla',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_12',
    nome: 'Due mattine',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDentroUnArco('alba', 2, 3),
    frase: 'Due Riti dell\'Alba dentro tre giorni.',
    posizione: 12,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'Il filo delle tue mattine',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Costanza',
    sezioneDelCammino: 'LA FIORITURA DEL RESPIRO',
  ),
  Traguardo(
    id: 'aur_13',
    nome: 'Il petalo mandato a una persona sola',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const VarietaDelDettaglio('condivisione', 'privato_aura', 1),
    frase: 'Mandi un responso di Aura a qualcuno in privato.',
    posizione: 13,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il bonus della condivisione privata',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Legame',
    sezioneDelCammino: 'LA FIORITURA DEL RESPIRO',
  ),
  Traguardo(
    id: 'aur_14',
    nome: 'Il respiro che rallenta',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('soffio', 3),
    frase:
        'Il tuo Soffio dura più a lungo del precedente per tre volte di fila.',
    posizione: 14,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'La curva del tuo respiro nel Journal',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Profondità',
    sezioneDelCammino: 'LA FIORITURA DEL RESPIRO',
  ),
  Traguardo(
    id: 'aur_15',
    nome: 'Il primo che entra grazie ad Aura',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const GestoDelCerchio('invito_aura', 1),
    frase:
        'Qualcuno accetta il tuo invito ed entra nel Cerchio da questa porta.',
    posizione: 15,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'I sessanta Eos dell\'invito accolto',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Legame',
    sezioneDelCammino: 'LA FIORITURA DEL RESPIRO',
  ),
  Traguardo(
    id: 'aur_16',
    nome: 'Il volto che cambia',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const VarietaDelDettaglio('viso', 'tratto_cambiato', 1),
    frase:
        'La Costellazione del Viso ti rilegge a distanza di un mese e trova un tratto diverso.',
    posizione: 16,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il confronto fra i tuoi due volti',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Coincidenza',
    sezioneDelCammino: 'LA FIORITURA DEL RESPIRO',
  ),
  Traguardo(
    id: 'aur_17',
    nome: 'La prima meditazione portata a termine',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const Dormiente('aur_17',
        'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: la meditazione oggi non ha una fine, prescrizione P35'),
    frase: 'Una meditazione seguita dall\'inizio alla fine.',
    posizione: 17,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Le meditazioni lunghe',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: true,
    ragione: 'Prima volta',
    sezioneDelCammino: 'LA FIORITURA DEL RESPIRO',
  ),
  Traguardo(
    id: 'aur_18',
    nome: 'Il mattino prima del sole',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const VarietaDelDettaglio('alba', 'prima_del_sole', 1),
    frase:
        'Un Rito dell\'Alba compiuto prima che il sole sorga davvero, nel tuo luogo.',
    posizione: 18,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'L\'ora esatta dell\'alba nel tuo luogo',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA FIORITURA DEL RESPIRO',
  ),
  Traguardo(
    id: 'aur_19',
    nome: 'Tre archetipi a confronto',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('archetipo', 2),
    frase:
        'Metti il tuo archetipo accanto ad altri due e ne leggi le differenze.',
    posizione: 19,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'La mappa degli archetipi',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Profondità',
    sezioneDelCammino: 'LA FIORITURA DEL RESPIRO',
  ),
  Traguardo(
    id: 'aur_20',
    nome: 'La Luna che cresce',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.lunaCrescente,
        conGesto: 'soffio'),
    frase: 'Un Soffio del Destino mentre la Luna sta crescendo.',
    posizione: 20,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Il Calendario degli Eventi',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA FIORITURA DEL RESPIRO',
  ),
  Traguardo(
    id: 'aur_21',
    nome: 'Il tuo respiro sotto pressione',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const RitornoAlRito('soffio', 3),
    frase:
        'Un Soffio del Destino compiuto in un giorno in cui ne avevi saltati tre.',
    posizione: 21,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'Il saluto di Aura a chi rientra',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Ritorno',
    sezioneDelCammino: 'LA FIORITURA DEL RESPIRO',
  ),
  Traguardo(
    id: 'aur_22',
    nome: 'LA FIORITURA DEL RESPIRO',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GradiniAlleSpalle('loto', 21),
    frase: 'Ventuno gradini qualunque del Loto alle spalle.',
    posizione: 22,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'La sequenza guidata del respiro',
    eGrande: true,
    eos: 60,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Perla',
    sezioneDelCammino: 'LA FIORITURA DEL RESPIRO',
  ),
  Traguardo(
    id: 'aur_23',
    nome: 'Il primo quarto',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.primoQuarto,
        conSentiero: 'loto', nellOra: 'notte'),
    frase: 'Un rito di Aura nella notte del primo quarto di Luna.',
    posizione: 23,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Le quattro fasi nel Calendario',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA FIORITURA DEL CIELO',
  ),
  Traguardo(
    id: 'aur_24',
    nome: 'La Luna nel segno opposto',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.lunaNelSegnoOpposto,
        conGesto: 'soffio'),
    frase: 'Un Soffio quando la Luna sta nel segno opposto al tuo.',
    posizione: 24,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'La lettura dell\'opposizione lunare',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA FIORITURA DEL CIELO',
  ),
  Traguardo(
    id: 'aur_25',
    nome: 'Il tuo primo chakra',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const Dormiente('aur_25',
        'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: i chakra non sono attivi nell\'MVP'),
    frase: 'Riconosci quale dei sette centri è il più chiuso oggi.',
    posizione: 25,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'La mappa dei sette chakra',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: true,
    ragione: 'Prima volta',
    sezioneDelCammino: 'LA FIORITURA DEL CIELO',
  ),
  Traguardo(
    id: 'aur_26',
    nome: 'Sette mattine',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDentroUnArco('alba', 7, 10),
    frase: 'Sette Riti dell\'Alba dentro dieci giorni.',
    posizione: 26,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'Il sigillo della settimana',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Costanza',
    sezioneDelCammino: 'LA FIORITURA DEL CIELO',
  ),
  Traguardo(
    id: 'aur_27',
    nome: 'Il transito sulla tua Luna',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.transitoSullaLuna),
    frase: 'Un pianeta lento passa sul grado della tua Luna di nascita.',
    posizione: 27,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'La scheda del transito lunare',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA FIORITURA DEL CIELO',
  ),
  Traguardo(
    id: 'aur_28',
    nome: 'La tua aura ha un colore',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const Dormiente('aur_28',
        'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: l\'analisi dell\'aura non è attiva nell\'MVP'),
    frase: 'L\'analisi dell\'aura ti restituisce il tuo colore dominante.',
    posizione: 28,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'L\'analisi dell\'aura',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: true,
    ragione: 'Prima volta',
    sezioneDelCammino: 'LA FIORITURA DEL CIELO',
  ),
  Traguardo(
    id: 'aur_29',
    nome: 'Il petalo che ha viaggiato',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const Dormiente('aur_29',
        'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: serve il tracciamento delle condivisioni'),
    frase:
        'Un tuo responso condiviso viene aperto da qualcuno fuori dal Cerchio.',
    posizione: 29,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'Il conto di chi ha visto i tuoi petali',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: true,
    ragione: 'Legame',
    sezioneDelCammino: 'LA FIORITURA DEL CIELO',
  ),
  Traguardo(
    id: 'aur_30',
    nome: 'Il respiro delle quattro fasi',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const VarietaPerValore('stesa', 'carta_e_luna', 4),
    frase: 'Un Soffio del Destino sotto ognuna delle quattro fasi lunari.',
    posizione: 30,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'La lettura del ciclo lunare completo',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA FIORITURA DEL CIELO',
  ),
  Traguardo(
    id: 'aur_31',
    nome: 'Due volti nello stesso Cerchio',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('due_volti', 1),
    frase:
        'Confronti la tua Costellazione del Viso con quella di un\'altra persona.',
    posizione: 31,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Il confronto dei volti',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Legame',
    sezioneDelCammino: 'LA FIORITURA DEL CIELO',
  ),
  Traguardo(
    id: 'aur_32',
    nome: 'Il mattino che si ripete',
    famiglia: FamigliaDelTraguardo.memoria,
    condizione: const CoincidenzaNellaFinestra('archetipo', 'archetipo', 2, 7),
    frase: 'Lo stesso archetipo esce due volte in una settimana.',
    posizione: 32,
    percheConta: FamigliaDelTraguardo.memoria.percheContaLaFamiglia,
    cosaApre: 'La nota di Aura sull\'archetipo che torna',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Coincidenza',
    sezioneDelCammino: 'LA FIORITURA DEL CIELO',
  ),
  Traguardo(
    id: 'aur_33',
    nome: 'LA FIORITURA DEL CIELO',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GradiniAlleSpalle('loto', 32),
    frase: 'Trentadue gradini qualunque del Loto alle spalle.',
    posizione: 33,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'La lettura lunare estesa',
    eGrande: true,
    eos: 80,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Perla',
    sezioneDelCammino: 'LA FIORITURA DEL CIELO',
  ),
  Traguardo(
    id: 'aur_34',
    nome: 'L\'ora fedele del mattino',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const StessaOraPerGiorni('alba', 5),
    frase: 'Compi il Rito dell\'Alba alla stessa ora per cinque giorni.',
    posizione: 34,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'L\'appuntamento fisso col mattino',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Costanza',
    sezioneDelCammino: 'LA FIORITURA DELLA MEMORIA',
  ),
  Traguardo(
    id: 'aur_35',
    nome: 'La tua scrittura ti somiglia',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const Dormiente('aur_35',
        'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: fase 4'),
    frase: 'La grafologia esoterica legge il tuo tratto e la tua firma.',
    posizione: 35,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'La grafologia esoterica',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Prima volta',
    sezioneDelCammino: 'LA FIORITURA DELLA MEMORIA',
  ),
  Traguardo(
    id: 'aur_36',
    nome: 'Il bioritmo che si incrocia',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const Dormiente('aur_36',
        'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: fase successiva',
        eraDelCielo: true),
    frase: 'Cogli il giorno in cui i tuoi tre cicli si incontrano.',
    posizione: 36,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Il Bioritmo grafico',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA FIORITURA DELLA MEMORIA',
  ),
  Traguardo(
    id: 'aur_37',
    nome: 'Il transito su Venere',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.transitoSuVenere),
    frase: 'Un pianeta lento passa sul grado della tua Venere di nascita.',
    posizione: 37,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'La scheda del transito di Venere',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA FIORITURA DELLA MEMORIA',
  ),
  Traguardo(
    id: 'aur_38',
    nome: 'Il tuo volto in un anno',
    famiglia: FamigliaDelTraguardo.giornata,
    condizione: const Dormiente('aur_38',
        'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: serve la memoria lunga dei volti'),
    frase:
        'La Costellazione del Viso ti rilegge dopo sei mesi e mostra il cambiamento.',
    posizione: 38,
    percheConta: FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
    cosaApre: 'La linea del tempo del tuo volto',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Coincidenza',
    sezioneDelCammino: 'LA FIORITURA DELLA MEMORIA',
  ),
  Traguardo(
    id: 'aur_39',
    nome: 'Sette petali condivisi',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const GestoDelCerchio('condivisione_petalo', 7),
    frase: 'Sette responsi di Aura condivisi.',
    posizione: 39,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'Il grado di Voce del Loto',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Legame',
    sezioneDelCammino: 'LA FIORITURA DELLA MEMORIA',
  ),
  Traguardo(
    id: 'aur_40',
    nome: 'Il tuo respiro nel giorno peggiore',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.saturnoRetrogrado,
        conGesto: 'soffio'),
    frase: 'Un Soffio compiuto in un giorno in cui il cielo ti è contrario.',
    posizione: 40,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'La lettura dei giorni difficili',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA FIORITURA DELLA MEMORIA',
  ),
  Traguardo(
    id: 'aur_41',
    nome: 'I sette centri aperti',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const Dormiente('aur_41',
        'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: i chakra non sono attivi nell\'MVP'),
    frase: 'Tutti e sette i chakra riconosciuti almeno una volta.',
    posizione: 41,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il sigillo dei sette centri',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Profondità',
    sezioneDelCammino: 'LA FIORITURA DELLA MEMORIA',
  ),
  Traguardo(
    id: 'aur_42',
    nome: 'La tua finestra fertile',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const Dormiente('aur_42',
        'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: fase successiva'),
    frase:
        'Il calcolo della fertilità ti restituisce la tua finestra del mese.',
    posizione: 42,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Il Calcolo della fertilità',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Prima volta',
    sezioneDelCammino: 'LA FIORITURA DELLA MEMORIA',
  ),
  Traguardo(
    id: 'aur_43',
    nome: 'Il volto che qualcuno ha riconosciuto',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const Dormiente('aur_43',
        'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: serve il conto sociale'),
    frase: 'Condividi la tua Costellazione del Viso e qualcuno ci si ritrova.',
    posizione: 43,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'La bacheca dei volti del Cerchio',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Legame',
    sezioneDelCammino: 'LA FIORITURA DELLA MEMORIA',
  ),
  Traguardo(
    id: 'aur_44',
    nome: 'LA FIORITURA DELLA MEMORIA',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GradiniAlleSpalle('loto', 43),
    frase: 'Quarantatre gradini qualunque del Loto alle spalle.',
    posizione: 44,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il Journal del corpo nel tempo',
    eGrande: true,
    eos: 100,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Perla',
    sezioneDelCammino: 'LA FIORITURA DELLA MEMORIA',
  ),
  Traguardo(
    id: 'aur_45',
    nome: 'Trenta mattine',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDiSeguito('alba', 30),
    frase: 'Trenta Riti dell\'Alba compiuti, non per forza di seguito.',
    posizione: 45,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'Il sigillo del mese di mattini',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Profondità',
    sezioneDelCammino: 'IL LOTO APERTO',
  ),
  Traguardo(
    id: 'aur_46',
    nome: 'Il respiro guidato dalla voce',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const Dormiente('aur_46',
        'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: la voce dei Maestri non è attiva'),
    frase:
        'Una meditazione seguita con la voce di Aura dall\'inizio alla fine.',
    posizione: 46,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Le meditazioni con voce',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
    ragione: 'Profondità',
    sezioneDelCammino: 'IL LOTO APERTO',
  ),
  Traguardo(
    id: 'aur_47',
    nome: 'La Luna piena sul tuo corpo',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.lunaPiena,
        conSentiero: 'loto', nellOra: 'notte'),
    frase: 'Un rito di Aura nella notte di Luna piena che cade nel tuo segno.',
    posizione: 47,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Il rito della Luna nel tuo segno',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'IL LOTO APERTO',
  ),
  Traguardo(
    id: 'aur_48',
    nome: 'Il tuo calendario lunare',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const Dormiente('aur_48',
        'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: fase successiva'),
    frase: 'Segui il tuo calendario lunare personale per un ciclo intero.',
    posizione: 48,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'Il Calendario lunare personale',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
    ragione: 'Costanza',
    sezioneDelCammino: 'IL LOTO APERTO',
  ),
  Traguardo(
    id: 'aur_49',
    nome: 'L\'eclissi sul respiro',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione:
        const FinestraDelCielo(EventiDelCielo.eclissi, conGesto: 'soffio'),
    frase: 'Un Soffio del Destino nelle ore di un\'eclissi.',
    posizione: 49,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'La Reliquia del Cielo di quella data',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'IL LOTO APERTO',
  ),
  Traguardo(
    id: 'aur_50',
    nome: 'Dodici petali condivisi',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const GestoDelCerchio('condivisione_petalo', 12),
    frase: 'Dodici responsi di Aura condivisi.',
    posizione: 50,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'Il grado di Fiore del Cerchio',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Legame',
    sezioneDelCammino: 'IL LOTO APERTO',
  ),
  Traguardo(
    id: 'aur_51',
    nome: 'La tua aura che cambia colore',
    famiglia: FamigliaDelTraguardo.giornata,
    condizione: const Dormiente('aur_51',
        'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: l\'analisi dell\'aura non è attiva'),
    frase: 'L\'analisi dell\'aura ti restituisce un colore diverso dal primo.',
    posizione: 51,
    percheConta: FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
    cosaApre: 'La linea del tempo della tua aura',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
    ragione: 'Coincidenza',
    sezioneDelCammino: 'IL LOTO APERTO',
  ),
  Traguardo(
    id: 'aur_52',
    nome: 'Il ritorno solare del corpo',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const Dormiente('aur_52',
        'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: il rito del Ritorno Solare è fase 2',
        eraDelCielo: true),
    frase: 'Un rito di Aura nell\'istante del tuo ritorno solare.',
    posizione: 52,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'La lettura del Ritorno Solare',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
    ragione: 'Cielo',
    sezioneDelCammino: 'IL LOTO APERTO',
  ),
  Traguardo(
    id: 'aur_53',
    nome: 'Le tre letture profonde',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const Dormiente('aur_53',
        'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: aura e grafologia non sono attive'),
    frase: 'Volto, aura e scrittura letti tutti e tre.',
    posizione: 53,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il ritratto profondo completo',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
    ragione: 'Profondità',
    sezioneDelCammino: 'IL LOTO APERTO',
  ),
  Traguardo(
    id: 'aur_54',
    nome: 'Il Loto che hai seminato',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const Dormiente('aur_54',
        'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: serve il conto degli inviti accolti'),
    frase: 'Cinque persone sono entrate nel Cerchio dalla porta di Aura.',
    posizione: 54,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'Il grado di Custode del Loto',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
    ragione: 'Legame',
    sezioneDelCammino: 'IL LOTO APERTO',
  ),
  Traguardo(
    id: 'aur_55',
    nome: 'IL LOTO APERTO',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GradiniAlleSpalle('loto', 54),
    frase: 'Cinquantaquattro gradini del Loto alle spalle.',
    posizione: 55,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il Cammino della fase successiva',
    eGrande: true,
    eos: 130,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Perla',
    sezioneDelCammino: 'IL LOTO APERTO',
  ),
];
