// GENERATO DA tool/genera_sentieri_dal_corpus.py: NON SI SCRIVE
// A MANO. Ordine AR voce 02.
//
// La fonte e' docs/corpus/Traguardi_165_Revisione_E.json, e il
// dato comanda: nomi, condizioni, fasce, Eos e porte vengono da
// li' verbatim. Per cambiare un traguardo si cambia il corpus e
// si rigenera, mai il contrario.

import 'eventi_del_cielo.dart';
import 'traguardo.dart';

final List<Traguardo> sentieroDellAlbero = [
  Traguardo(
    id: 'cal_1',
    nome: 'Hai gettato le prime rune',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('gettata', 1),
    frase: 'Compi la tua prima gettata di rune.',
    posizione: 1,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Il Segno del Tramonto',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Prima volta',
    sezioneDelCammino: 'MALKUTH, IL REGNO',
  ),
  Traguardo(
    id: 'cal_2',
    nome: 'Il segno del tramonto',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('tramonto', 1),
    frase: 'Ricevi il tuo primo Segno del Tramonto.',
    posizione: 2,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Il Sigillo del Sogno',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Prima volta',
    sezioneDelCammino: 'MALKUTH, IL REGNO',
  ),
  Traguardo(
    id: 'cal_3',
    nome: 'Il tuo Animale ti ha trovato',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('animale_guida', 1),
    frase: 'Il tamburo chiama e il tuo Animale Guida si presenta.',
    posizione: 3,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'La scheda del tuo Animale',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Prima volta',
    sezioneDelCammino: 'MALKUTH, IL REGNO',
  ),
  Traguardo(
    id: 'cal_4',
    nome: 'Il primo sogno',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('sogno', 1),
    frase: 'Compi il tuo primo Sigillo del Sogno.',
    posizione: 4,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Il diario dei sogni',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Prima volta',
    sezioneDelCammino: 'MALKUTH, IL REGNO',
  ),
  Traguardo(
    id: 'cal_5',
    nome: 'Il primo sigillo',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('sigillo', 1),
    frase: 'Tracci il tuo primo Sigillo dell\'Intenzione.',
    posizione: 5,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Il Sigillo del Cerchio',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Prima volta',
    sezioneDelCammino: 'MALKUTH, IL REGNO',
  ),
  Traguardo(
    id: 'cal_6',
    nome: 'Il Sigillo del Cerchio',
    famiglia: FamigliaDelTraguardo.identita,
    condizione: const PezzoDellIdentita('sigillo_del_cerchio'),
    frase: 'Il tuo sigillo personale entra nel profilo e ti rappresenta.',
    posizione: 6,
    percheConta: FamigliaDelTraguardo.identita.percheContaLaFamiglia,
    cosaApre: 'La firma sui tuoi responsi',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Identità',
    sezioneDelCammino: 'MALKUTH, IL REGNO',
  ),
  Traguardo(
    id: 'cal_7',
    nome: 'Il primo frutto condiviso',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const GestoDelCerchio('condivisione_frutto', 1),
    frase: 'Condividi pubblicamente un responso di Caligo.',
    posizione: 7,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'Il bonus della condivisione',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Legame',
    sezioneDelCammino: 'MALKUTH, IL REGNO',
  ),
  Traguardo(
    id: 'cal_8',
    nome: 'La pietra girata a mano',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const Dormiente('cal_8', 'girare una runa coperta invece di lasciarla al caso e un gesto che la scena non distingue: manda la gettata e il suo modo, non chi ha scoperto la runa'),
    frase: 'Scopri una runa coperta girandola tu invece di lasciarla al caso.',
    posizione: 8,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'I modi di gettare',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: true,
    ragione: 'Profondità',
    sezioneDelCammino: 'MALKUTH, IL REGNO',
  ),
  Traguardo(
    id: 'cal_9',
    nome: 'Pietra e sogno',
    famiglia: FamigliaDelTraguardo.giornata,
    condizione: const GestiNelloStessoGiorno(['gettata', 'sogno']),
    frase: 'Una gettata e un Sigillo del Sogno nello stesso giorno.',
    posizione: 9,
    percheConta: FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
    cosaApre: 'Il riepilogo della notte nel Journal',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Coincidenza',
    sezioneDelCammino: 'MALKUTH, IL REGNO',
  ),
  Traguardo(
    id: 'cal_10',
    nome: 'Il tuo Animale nel bosco degli altri',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const Dormiente('cal_10', 'guardare cosa accompagna gli altri chiede il Cerchio degli altri, che nell app non esiste: nessuna schermata lo mostra e nessun gesto lo registra'),
    frase: 'Guardi quali Animali Guida accompagnano gli altri del Cerchio.',
    posizione: 10,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'Il bosco del Cerchio',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: true,
    ragione: 'Legame',
    sezioneDelCammino: 'MALKUTH, IL REGNO',
  ),
  Traguardo(
    id: 'cal_11',
    nome: 'MALKUTH, IL REGNO',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GradiniAlleSpalle('albero', 10),
    frase: 'Dieci gradini qualunque dell\'Albero alle spalle.',
    posizione: 11,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'La lettura estesa delle rune',
    eGrande: true,
    eos: 40,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Perla',
    sezioneDelCammino: 'MALKUTH, IL REGNO',
  ),
  Traguardo(
    id: 'cal_12',
    nome: 'Due sere',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDentroUnArco('tramonto', 2, 3),
    frase: 'Due Segni del Tramonto dentro tre giorni.',
    posizione: 12,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'Il filo delle tue sere',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Costanza',
    sezioneDelCammino: 'YESOD, IL FONDAMENTO',
  ),
  Traguardo(
    id: 'cal_13',
    nome: 'Il frutto mandato a una persona sola',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const Dormiente('cal_13', 'mandare un responso in privato invece che al mondo chiede il canale della condivisione, che il gesto non porta: la regia sa che si e condiviso, non dove'),
    frase: 'Mandi un responso di Caligo a qualcuno in privato.',
    posizione: 13,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'Il bonus della condivisione privata',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: true,
    ragione: 'Legame',
    sezioneDelCammino: 'YESOD, IL FONDAMENTO',
  ),
  Traguardo(
    id: 'cal_14',
    nome: 'Due modi di gettare',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const VarietaDelDettaglio('gettata', 'modo', 2),
    frase: 'Provi due modi diversi di gettare le rune.',
    posizione: 14,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Tutti i modi di gettare',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Profondità',
    sezioneDelCammino: 'YESOD, IL FONDAMENTO',
  ),
  Traguardo(
    id: 'cal_15',
    nome: 'Sotto la Luna nuova',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.lunaNuova, conGesto: 'gettata'),
    frase: 'Una gettata nella notte di Luna nuova.',
    posizione: 15,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Il Calendario degli Eventi',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'YESOD, IL FONDAMENTO',
  ),
  Traguardo(
    id: 'cal_16',
    nome: 'Il primo che entra grazie a Caligo',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const Dormiente('cal_16', 'il gesto del Cerchio invito non arriva alla regia'),
    frase: 'Qualcuno accetta il tuo invito ed entra nel Cerchio da questa porta.',
    posizione: 16,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'I sessanta Eos dell\'invito accolto',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: true,
    ragione: 'Legame',
    sezioneDelCammino: 'YESOD, IL FONDAMENTO',
  ),
  Traguardo(
    id: 'cal_17',
    nome: 'Il sogno riletto',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const Dormiente('cal_17', 'il rito del sogno non passa cio che si e sognato: la scena manda il gesto e basta. Servirebbe un dettaglio nuovo'),
    frase: 'Torni su un sogno annotato e lo rileggi a distanza di giorni.',
    posizione: 17,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il diario dei sogni nel tempo',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: true,
    ragione: 'Profondità',
    sezioneDelCammino: 'YESOD, IL FONDAMENTO',
  ),
  Traguardo(
    id: 'cal_18',
    nome: 'La runa che ti cerca',
    famiglia: FamigliaDelTraguardo.memoria,
    condizione: const CoincidenzaDelDettaglio('tramonto', 'runa', 2),
    frase: 'La stessa runa esce in due gettate diverse.',
    posizione: 18,
    percheConta: FamigliaDelTraguardo.memoria.percheContaLaFamiglia,
    cosaApre: 'La scheda della runa che ti segue',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Coincidenza',
    sezioneDelCammino: 'YESOD, IL FONDAMENTO',
  ),
  Traguardo(
    id: 'cal_19',
    nome: 'Il tuo sogno interpretato',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const Dormiente('cal_19', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: fase successiva'),
    frase: 'L\'interpretazione dei sogni legge il racconto che hai scritto.',
    posizione: 19,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'L\'Interpretazione dei sogni',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: true,
    ragione: 'Prima volta',
    sezioneDelCammino: 'YESOD, IL FONDAMENTO',
  ),
  Traguardo(
    id: 'cal_20',
    nome: 'La Luna che cala',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.lunaCalante),
    frase: 'Un rito di Caligo mentre la Luna sta calando.',
    posizione: 20,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'La lettura della Luna calante',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'YESOD, IL FONDAMENTO',
  ),
  Traguardo(
    id: 'cal_21',
    nome: 'Il ritorno dal buio',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const RitornoDopoAssenza(7),
    frase: 'Torni a Caligo dopo sette giorni in cui non l\'hai cercato.',
    posizione: 21,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'Il saluto di Caligo a chi rientra',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Ritorno',
    sezioneDelCammino: 'YESOD, IL FONDAMENTO',
  ),
  Traguardo(
    id: 'cal_22',
    nome: 'YESOD, IL FONDAMENTO',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GradiniAlleSpalle('albero', 21),
    frase: 'Ventuno gradini qualunque dell\'Albero alle spalle.',
    posizione: 22,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il Sigillo del Sogno in versione lunga',
    eGrande: true,
    eos: 60,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Perla',
    sezioneDelCammino: 'YESOD, IL FONDAMENTO',
  ),
  Traguardo(
    id: 'cal_23',
    nome: 'Dodici rune diverse',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const VarietaDelDettaglio('tramonto', 'runa', 12),
    frase: 'Dodici rune diverse uscite nelle tue gettate.',
    posizione: 23,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Metà dell\'alfabeto runico',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Profondità',
    sezioneDelCammino: 'TIPHERETH, LA BELLEZZA',
  ),
  Traguardo(
    id: 'cal_24',
    nome: 'La notte del solstizio',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const Dormiente('cal_24', 'l ora del rito non viaggia con l\'evento del cielo: l app sa che oggi e solstizio e che il gesto e stato compiuto, non che sia stato compiuto di notte', eraDelCielo: true),
    frase: 'Un rito di Caligo nella notte del solstizio.',
    posizione: 24,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Le quattro porte dell\'anno nel Calendario',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: true,
    ragione: 'Cielo',
    sezioneDelCammino: 'TIPHERETH, LA BELLEZZA',
  ),
  Traguardo(
    id: 'cal_25',
    nome: 'Il primo rito guidato',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const Dormiente('cal_25', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: i rituali guidati sono fase C'),
    frase: 'Segui un rituale guidato passo per passo fino alla fine.',
    posizione: 25,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'I rituali guidati interattivi',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: true,
    ragione: 'Prima volta',
    sezioneDelCammino: 'TIPHERETH, LA BELLEZZA',
  ),
  Traguardo(
    id: 'cal_26',
    nome: 'Sette sere',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDentroUnArco('tramonto', 7, 10),
    frase: 'Sette Segni del Tramonto dentro dieci giorni.',
    posizione: 26,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'Il sigillo della settimana',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Costanza',
    sezioneDelCammino: 'TIPHERETH, LA BELLEZZA',
  ),
  Traguardo(
    id: 'cal_27',
    nome: 'Marte torna indietro',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.marteRetrogrado, conGesto: 'gettata'),
    frase: 'Una gettata mentre Marte è retrogrado.',
    posizione: 27,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'La lettura di Marte nel Calendario',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'TIPHERETH, LA BELLEZZA',
  ),
  Traguardo(
    id: 'cal_28',
    nome: 'Il rito nell\'ora sua',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const Dormiente('cal_28', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: il motore delle ore planetarie non esiste', eraDelCielo: true),
    frase: 'Un rito compiuto nell\'ora planetaria che gli appartiene.',
    posizione: 28,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Le ore planetarie',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: true,
    ragione: 'Cielo',
    sezioneDelCammino: 'TIPHERETH, LA BELLEZZA',
  ),
  Traguardo(
    id: 'cal_29',
    nome: 'Il frutto che ha viaggiato',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const Dormiente('cal_29', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: serve il tracciamento delle condivisioni'),
    frase: 'Un tuo responso condiviso viene aperto da qualcuno fuori dal Cerchio.',
    posizione: 29,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'Il conto di chi ha visto i tuoi frutti',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: true,
    ragione: 'Legame',
    sezioneDelCammino: 'TIPHERETH, LA BELLEZZA',
  ),
  Traguardo(
    id: 'cal_30',
    nome: 'Tutti i modi di gettare',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const VarietaDelDettaglio('gettata', 'modo', 4),
    frase: 'Ogni modo di gettare le rune provato almeno una volta.',
    posizione: 30,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'La gettata libera',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Profondità',
    sezioneDelCammino: 'TIPHERETH, LA BELLEZZA',
  ),
  Traguardo(
    id: 'cal_31',
    nome: 'Il sogno che si ripete',
    famiglia: FamigliaDelTraguardo.giornata,
    condizione: const Dormiente('cal_31', 'il rito del sogno non passa cio che si e sognato: la scena manda il gesto e basta. Servirebbe un dettaglio nuovo'),
    frase: 'Lo stesso simbolo torna in due sogni annotati.',
    posizione: 31,
    percheConta: FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
    cosaApre: 'La nota di Caligo sul simbolo che insiste',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: true,
    ragione: 'Coincidenza',
    sezioneDelCammino: 'TIPHERETH, LA BELLEZZA',
  ),
  Traguardo(
    id: 'cal_32',
    nome: 'Il tuo Animale nel sogno',
    famiglia: FamigliaDelTraguardo.giornata,
    condizione: const Dormiente('cal_32', 'il rito del sogno non passa cio che si e sognato: la scena manda il gesto e basta. Servirebbe un dettaglio nuovo'),
    frase: 'Il tuo Animale Guida compare in un sogno che hai annotato.',
    posizione: 32,
    percheConta: FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
    cosaApre: 'La scheda del tuo Animale nel diario',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: true,
    ragione: 'Coincidenza',
    sezioneDelCammino: 'TIPHERETH, LA BELLEZZA',
  ),
  Traguardo(
    id: 'cal_33',
    nome: 'TIPHERETH, LA BELLEZZA',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GradiniAlleSpalle('albero', 32),
    frase: 'Trentadue gradini qualunque dell\'Albero alle spalle.',
    posizione: 33,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'La lettura dei simboli ricorrenti',
    eGrande: true,
    eos: 80,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Perla',
    sezioneDelCammino: 'TIPHERETH, LA BELLEZZA',
  ),
  Traguardo(
    id: 'cal_34',
    nome: 'L\'ora fedele della sera',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const Dormiente('cal_34', 'l app sa se un gesto cade nell ora rituale dell alba, del tramonto o della notte, non se cade sempre alla STESSA ora: servirebbe la memoria dell ora di ogni gesto'),
    frase: 'Ricevi il Segno del Tramonto alla stessa ora per cinque giorni.',
    posizione: 34,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'L\'appuntamento fisso con la sera',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Costanza',
    sezioneDelCammino: 'BINAH, LA COMPRENSIONE',
  ),
  Traguardo(
    id: 'cal_35',
    nome: 'La magia verde',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const Dormiente('cal_35', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: le tre vie non sono attive nell\'MVP'),
    frase: 'Compi il tuo primo rito di abbondanza della via verde.',
    posizione: 35,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'La magia verde',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Prima volta',
    sezioneDelCammino: 'BINAH, LA COMPRENSIONE',
  ),
  Traguardo(
    id: 'cal_36',
    nome: 'La magia bianca',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const Dormiente('cal_36', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: le tre vie non sono attive nell\'MVP'),
    frase: 'Compi il tuo primo rito di protezione della via bianca.',
    posizione: 36,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'La magia bianca',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Prima volta',
    sezioneDelCammino: 'BINAH, LA COMPRENSIONE',
  ),
  Traguardo(
    id: 'cal_37',
    nome: 'Il transito su Marte',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.transitoSuMarte),
    frase: 'Un pianeta lento passa sul grado del tuo Marte di nascita.',
    posizione: 37,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'La scheda del transito di Marte',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'BINAH, LA COMPRENSIONE',
  ),
  Traguardo(
    id: 'cal_38',
    nome: 'Il simbolo riconosciuto',
    famiglia: FamigliaDelTraguardo.giornata,
    condizione: const Dormiente('cal_38', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: la simbologia non è attiva nell\'MVP'),
    frase: 'Riconosci nella simbologia un segno che avevi già incontrato in un sogno.',
    posizione: 38,
    percheConta: FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
    cosaApre: 'La simbologia',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Coincidenza',
    sezioneDelCammino: 'BINAH, LA COMPRENSIONE',
  ),
  Traguardo(
    id: 'cal_39',
    nome: 'Sette frutti condivisi',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const GestoDelCerchio('condivisione_frutto', 7),
    frase: 'Sette responsi di Caligo condivisi.',
    posizione: 39,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'Il grado di Voce dell\'Albero',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Legame',
    sezioneDelCammino: 'BINAH, LA COMPRENSIONE',
  ),
  Traguardo(
    id: 'cal_40',
    nome: 'Tre sogni che si somigliano',
    famiglia: FamigliaDelTraguardo.giornata,
    condizione: const Dormiente('cal_40', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: riconoscere la somiglianza chiede l\'Interpretazione dei sogni, fase successiva'),
    frase: 'Tre sogni annotati che parlano della stessa cosa.',
    posizione: 40,
    percheConta: FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
    cosaApre: 'Il filo dei tuoi sogni',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Coincidenza',
    sezioneDelCammino: 'BINAH, LA COMPRENSIONE',
  ),
  Traguardo(
    id: 'cal_41',
    nome: 'Il tuo sigillo magico',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const Dormiente('cal_41', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: MVP, uscito dalle distintive di Demo'),
    frase: 'Costruisci il tuo sigillo magico personale e lo usi in un rito.',
    posizione: 41,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Il Sigillo magico personale',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Prima volta',
    sezioneDelCammino: 'BINAH, LA COMPRENSIONE',
  ),
  Traguardo(
    id: 'cal_42',
    nome: 'La Luna nuova nel tuo segno',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.lunaNuovaNelTuoSegno, conGesto: 'gettata'),
    frase: 'Una gettata nella notte in cui la Luna nuova cade nel tuo segno.',
    posizione: 42,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Il rito della Luna nel tuo segno',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'BINAH, LA COMPRENSIONE',
  ),
  Traguardo(
    id: 'cal_43',
    nome: 'Il rito compiuto in due',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const Dormiente('cal_43', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: i riti in due sono fase viralità'),
    frase: 'Compi un rito insieme a un\'altra persona del Cerchio.',
    posizione: 43,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'I riti condivisi',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Legame',
    sezioneDelCammino: 'BINAH, LA COMPRENSIONE',
  ),
  Traguardo(
    id: 'cal_44',
    nome: 'BINAH, LA COMPRENSIONE',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GradiniAlleSpalle('albero', 43),
    frase: 'Quarantatre gradini qualunque dell\'Albero alle spalle.',
    posizione: 44,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il libro dei simboli del Cerchio',
    eGrande: true,
    eos: 100,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Perla',
    sezioneDelCammino: 'BINAH, LA COMPRENSIONE',
  ),
  Traguardo(
    id: 'cal_45',
    nome: 'Tutte le ventiquattro rune',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const VarietaDelDettaglio('tramonto', 'runa', 24),
    frase: 'Ogni runa dell\'alfabeto uscita almeno una volta.',
    posizione: 45,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'L\'alfabeto runico completo nel Passaporto',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Profondità',
    sezioneDelCammino: 'KETHER, LA CORONA',
  ),
  Traguardo(
    id: 'cal_46',
    nome: 'La magia rossa',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const Dormiente('cal_46', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: le tre vie non sono attive nell\'MVP'),
    frase: 'Compi il tuo primo rito della via rossa.',
    posizione: 46,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'La magia rossa',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
    ragione: 'Prima volta',
    sezioneDelCammino: 'KETHER, LA CORONA',
  ),
  Traguardo(
    id: 'cal_47',
    nome: 'Saturno torna diretto',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.saturnoDiretto),
    frase: 'Un rito di Caligo nel giorno in cui Saturno riprende il cammino.',
    posizione: 47,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'La lettura di Saturno nel Calendario',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'KETHER, LA CORONA',
  ),
  Traguardo(
    id: 'cal_48',
    nome: 'Dodici frutti condivisi',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const GestoDelCerchio('condivisione_frutto', 12),
    frase: 'Dodici responsi di Caligo condivisi.',
    posizione: 48,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'Il grado di Radice del Cerchio',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Legame',
    sezioneDelCammino: 'KETHER, LA CORONA',
  ),
  Traguardo(
    id: 'cal_49',
    nome: 'L\'Animale che muta',
    famiglia: FamigliaDelTraguardo.giornata,
    condizione: const Dormiente('cal_49', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: serve la memoria lunga. Sostituisce Novanta sere, che ripeteva la costanza'),
    frase: 'Dopo un anno il tamburo chiama e ti si presenta un Animale diverso.',
    posizione: 49,
    percheConta: FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
    cosaApre: 'La linea del tempo del tuo Animale',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
    ragione: 'Coincidenza',
    sezioneDelCammino: 'KETHER, LA CORONA',
  ),
  Traguardo(
    id: 'cal_50',
    nome: 'La notte dell\'eclissi',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const Dormiente('cal_50', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: il motore delle eclissi non esiste', eraDelCielo: true),
    frase: 'Un rito di Caligo nelle ore di un\'eclissi.',
    posizione: 50,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'La Reliquia del Cielo di quella data',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
    ragione: 'Cielo',
    sezioneDelCammino: 'KETHER, LA CORONA',
  ),
  Traguardo(
    id: 'cal_51',
    nome: 'Le tre vie percorse',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const Dormiente('cal_51', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: le tre vie non sono attive nell\'MVP'),
    frase: 'Un rito compiuto in ognuna delle tre vie, rossa, bianca e verde.',
    posizione: 51,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il sigillo delle tre vie',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
    ragione: 'Profondità',
    sezioneDelCammino: 'KETHER, LA CORONA',
  ),
  Traguardo(
    id: 'cal_52',
    nome: 'La congiunzione delle Guide',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const Dormiente('cal_52', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: la Congiunzione delle Guide è fase 2', eraDelCielo: true),
    frase: 'Sei nel Santuario nella notte rara in cui i tre Maestri appaiono insieme.',
    posizione: 52,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'La lettura a tre voci',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
    ragione: 'Cielo',
    sezioneDelCammino: 'KETHER, LA CORONA',
  ),
  Traguardo(
    id: 'cal_53',
    nome: 'La Reliquia della notte più lunga',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const Dormiente('cal_53', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: Reliquie del Cielo, fase 2', eraDelCielo: true),
    frase: 'Compi il rito del solstizio d\'inverno e ricevi il Sigillo datato.',
    posizione: 53,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Le Reliquie del Cielo',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
    ragione: 'Cielo',
    sezioneDelCammino: 'KETHER, LA CORONA',
  ),
  Traguardo(
    id: 'cal_54',
    nome: 'L\'Albero che hai piantato',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const Dormiente('cal_54', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: serve il conto degli inviti accolti'),
    frase: 'Cinque persone sono entrate nel Cerchio dalla porta di Caligo.',
    posizione: 54,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'Il grado di Custode dell\'Albero',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
    ragione: 'Legame',
    sezioneDelCammino: 'KETHER, LA CORONA',
  ),
  Traguardo(
    id: 'cal_55',
    nome: 'KETHER, LA CORONA',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GradiniAlleSpalle('albero', 54),
    frase: 'Cinquantaquattro gradini dell\'Albero alle spalle.',
    posizione: 55,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il Cammino della fase successiva',
    eGrande: true,
    eos: 130,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Perla',
    sezioneDelCammino: 'KETHER, LA CORONA',
  ),
];
