// GENERATO DA tool/genera_corpus_f.py: NON SI SCRIVE A MANO.
// Ordine CP voce 05, 3 settembre 2026.
//
// La fonte e' docs/corpus/Traguardi_165_Revisione_F.json, scritto a sua
// volta da tool/corpus_traguardi_dati.py. **La condizione si dichiara,
// non si deduce**: qui non c'e' nessun riconoscimento di testo, la
// condizione arriva strutturata e si trascrive. La frase che la persona
// legge si compone DALLA condizione, quindi non puo' contraddirla.
//
// Per cambiare un traguardo si cambia il dato e si rigenera, mai il
// contrario. Le regole stanno in docs/regole_dei_traguardi.md.

import 'eventi_del_cielo.dart';
import 'traguardo.dart';

final List<Traguardo> sentieroDelLoto = [
  Traguardo(
    id: 'aur_1',
    nome: 'Il tuo volto letto',
    famiglia: FamigliaDelTraguardo.identita,
    condizione: const PezzoDellIdentita('viso'),
    frase:
        'Hai dato al Cerchio la Costellazione del Viso: da adesso ogni responso parte da qui.',
    posizione: 1,
    percheConta: FamigliaDelTraguardo.identita.percheContaLaFamiglia,
    cosaApre: 'La Costellazione del Viso, che da qui entra nel tuo profilo',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Identita',
    sezioneDelCammino: 'IL PRIMO PETALO',
  ),
  Traguardo(
    id: 'aur_2',
    nome: 'Due albe',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GestiCompiuti('alba', 2, inGiorniDiversi: true),
    frase: 'Hai compiuto il Rito dell’Alba in 2 giorni diversi.',
    posizione: 2,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'La parola del giorno, che cambia con l’ora in cui ti alzi',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Profondita',
    sezioneDelCammino: 'IL PRIMO PETALO',
  ),
  Traguardo(
    id: 'aur_3',
    nome: 'Due Soffi',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GestiCompiuti('soffio', 2, inGiorniDiversi: true),
    frase: 'Hai compiuto il Soffio del Destino in 2 giorni diversi.',
    posizione: 3,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il respiro contato, con il ritmo che Aura ti propone',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Profondita',
    sezioneDelCammino: 'IL PRIMO PETALO',
  ),
  Traguardo(
    id: 'aur_4',
    nome: 'Il tuo Archetipo',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GestiCompiuti('archetipo', 3, inGiorniDiversi: true),
    frase: 'Hai compiuto l’Archetipo in 3 giorni diversi.',
    posizione: 4,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'I dodici Archetipi, con quello che ti governa',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Profondita',
    sezioneDelCammino: 'IL PRIMO PETALO',
  ),
  Traguardo(
    id: 'aur_5',
    nome: 'Tre meditazioni',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GestiCompiuti('meditazione', 3, inGiorniDiversi: true),
    frase: 'Hai compiuto la Meditazione in 3 giorni diversi.',
    posizione: 5,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Le meditazioni guidate lunghe, dai sette minuti in su',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Profondita',
    sezioneDelCammino: 'IL PRIMO PETALO',
  ),
  Traguardo(
    id: 'aur_6',
    nome: 'L’alba e il respiro',
    famiglia: FamigliaDelTraguardo.giornata,
    condizione: const GiornateInsieme(['alba', 'soffio'], 4),
    frase:
        '4 giornate chiuse con il Rito dell’Alba e il Soffio del Destino, nello stesso giorno.',
    posizione: 6,
    percheConta: FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
    cosaApre: 'Il rito del mattino completo, alba e Soffio uno dopo l’altro',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Legame',
    sezioneDelCammino: 'IL PRIMO PETALO',
  ),
  Traguardo(
    id: 'aur_7',
    nome: 'I tuoi due volti',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GestiCompiuti('due_volti', 4, inGiorniDiversi: true),
    frase: 'Hai compiuto i Due Volti in 4 giorni diversi.',
    posizione: 7,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il confronto fra il volto che mostri e quello che sei',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Profondita',
    sezioneDelCammino: 'IL PRIMO PETALO',
  ),
  Traguardo(
    id: 'aur_8',
    nome: 'Cinque Soffi in sette giorni',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDentroUnArco('soffio', 5, 7),
    frase:
        '5 giorni con il Soffio del Destino negli ultimi 7: nessuno te l’ha chiesto.',
    posizione: 8,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'Il grafico del respiro, che senza cinque giorni non dice niente',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Costanza',
    sezioneDelCammino: 'IL PRIMO PETALO',
  ),
  Traguardo(
    id: 'aur_9',
    nome: 'Cinque meditazioni',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GestiCompiuti('meditazione', 5, inGiorniDiversi: true),
    frase: 'Hai compiuto la Meditazione in 5 giorni diversi.',
    posizione: 9,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Le meditazioni sui chakra, una per centro',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Profondita',
    sezioneDelCammino: 'IL PRIMO PETALO',
  ),
  Traguardo(
    id: 'aur_10',
    nome: 'La costanza dell’Alba',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDentroUnArco('alba', 6, 8),
    frase:
        '6 giorni con il Rito dell’Alba negli ultimi 8: nessuno te l’ha chiesto.',
    posizione: 10,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'Il promemoria dell’Alba, che da qui sceglie la tua ora',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Costanza',
    sezioneDelCammino: 'IL PRIMO PETALO',
  ),
  Traguardo(
    id: 'aur_11',
    nome: 'L’Alba al primo quarto',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione:
        const FinestraDelCielo(EventiDelCielo.primoQuarto, conGesto: 'alba'),
    frase: 'La Luna è al primo quarto: tu eri qui con il Rito dell’Alba.',
    posizione: 11,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Il calendario lunare del Cerchio, con le fasi che verranno',
    eGrande: true,
    eos: 40,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'IL PRIMO PETALO',
  ),
  Traguardo(
    id: 'aur_12',
    nome: 'L’Alba nella sua ora',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const GestoNellOraGiusta('alba', 'alba', quanteVolte: 9),
    frase: '9 volte il Rito dell’Alba nell’ora vera dell’alba.',
    posizione: 12,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Le ore rituali, che il Cerchio calcola sul tuo luogo vero',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_13',
    nome: 'Dieci Soffi in quattordici giorni',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDentroUnArco('soffio', 10, 14),
    frase:
        '10 giorni con il Soffio del Destino negli ultimi 14: nessuno te l’ha chiesto.',
    posizione: 13,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'Il diario del respiro, con i giorni segnati uno per uno',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Costanza',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_14',
    nome: 'Il volto che cambia',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GestiCompiuti('viso', 12, inGiorniDiversi: true),
    frase: 'Hai compiuto la Costellazione del Viso in 12 giorni diversi.',
    posizione: 14,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il confronto fra la prima lettura del viso e l’ultima',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Profondita',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_15',
    nome: 'L’ora fedele dell’Alba',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const StessaOraPerGiorni('alba', 14),
    frase:
        '14 giorni alla stessa ora con il Rito dell’Alba: l’abitudine ha trovato il suo posto.',
    posizione: 15,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'L’appuntamento con Aura, che da qui ti aspetta a quell’ora',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Costanza',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_16',
    nome: 'Il Soffio sotto la Luna piena',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione:
        const FinestraDelCielo(EventiDelCielo.lunaPiena, conGesto: 'soffio'),
    frase: 'La Luna è piena: tu eri qui con il Soffio del Destino.',
    posizione: 16,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Il respiro lunare, che si pratica solo a Luna piena',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_17',
    nome: 'Le tre pratiche',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GiornateInsieme(['alba', 'meditazione', 'soffio'], 16),
    frase: '16 giornate con 3 arti diverse, nello stesso giorno.',
    posizione: 17,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'La sequenza del risveglio, dove le tre pratiche si tengono',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Legame',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_18',
    nome: 'Diciotto albe in venticinque giorni',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDentroUnArco('alba', 18, 25),
    frase:
        '18 giorni con il Rito dell’Alba negli ultimi 25: nessuno te l’ha chiesto.',
    posizione: 18,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'La costanza larga, che perdona un giorno saltato',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Costanza',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_19',
    nome: 'Venti Archetipi',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GestiCompiuti('archetipo', 20, inGiorniDiversi: true),
    frase: 'Hai compiuto l’Archetipo in 20 giorni diversi.',
    posizione: 19,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il tuo Archetipo in movimento, che cambia col tempo',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Profondita',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_20',
    nome: 'Venticinque confronti',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GestiCompiuti('due_volti', 25, inGiorniDiversi: true),
    frase: 'Hai compiuto i Due Volti in 25 giorni diversi.',
    posizione: 20,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'La storia dei tuoi volti, mese per mese',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Profondita',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_21',
    nome: 'Il Viso sotto la tua Luna',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.lunaNelTuoSegno,
        conGesto: 'viso'),
    frase:
        'La Luna passa nel tuo segno: tu eri qui con la Costellazione del Viso.',
    posizione: 21,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'La lettura lunare del volto, che vale solo nel tuo segno',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_22',
    nome: 'L’Alba sotto un transito',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.transitoSullaLuna,
        conGesto: 'alba'),
    frase:
        'Un pianeta transita sulla tua Luna: tu eri qui con il Rito dell’Alba.',
    posizione: 22,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Il registro dei transiti, con quelli che ti aspettano',
    eGrande: true,
    eos: 60,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA PRIMA FIORITURA',
  ),
  Traguardo(
    id: 'aur_23',
    nome: 'Un mese di Soffi',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GestiCompiuti('soffio', 31, inGiorniDiversi: true),
    frase: 'Hai compiuto il Soffio del Destino in 31 giorni diversi.',
    posizione: 23,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il respiro profondo, la pratica lunga da undici minuti',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Profondita',
    sezioneDelCammino: 'IL FIORE CHE RESPIRA',
  ),
  Traguardo(
    id: 'aur_24',
    nome: 'Trentacinque albe in quarantacinque giorni',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDentroUnArco('alba', 35, 45),
    frase:
        '35 giorni con il Rito dell’Alba negli ultimi 45: nessuno te l’ha chiesto.',
    posizione: 24,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'Il tuo ritmo del mattino, che si calcola solo con questa storia',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Costanza',
    sezioneDelCammino: 'IL FIORE CHE RESPIRA',
  ),
  Traguardo(
    id: 'aur_25',
    nome: 'Quaranta mattine intere',
    famiglia: FamigliaDelTraguardo.giornata,
    condizione: const GiornateInsieme(['alba', 'meditazione'], 40),
    frase:
        '40 giornate chiuse con il Rito dell’Alba e la Meditazione, nello stesso giorno.',
    posizione: 25,
    percheConta: FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
    cosaApre: 'La meditazione dell’alba, che si sblocca con la costanza',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Legame',
    sezioneDelCammino: 'IL FIORE CHE RESPIRA',
  ),
  Traguardo(
    id: 'aur_26',
    nome: 'L’Alba sul tuo Ascendente',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.transitoSullAscendente,
        conGesto: 'alba'),
    frase:
        'Un pianeta transita sul tuo Ascendente: tu eri qui con il Rito dell’Alba.',
    posizione: 26,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Le soglie della vita, che i transiti sull’Ascendente aprono',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'IL FIORE CHE RESPIRA',
  ),
  Traguardo(
    id: 'aur_27',
    nome: 'Il Soffio sul tuo Sole',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.transitoSulSole,
        conGesto: 'soffio'),
    frase:
        'Un pianeta transita sul tuo Sole: tu eri qui con il Soffio del Destino.',
    posizione: 27,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Il respiro solare, che si pratica solo sotto il transito',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'IL FIORE CHE RESPIRA',
  ),
  Traguardo(
    id: 'aur_28',
    nome: 'Cinquantacinque letture del volto',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GestiCompiuti('viso', 55, inGiorniDiversi: true),
    frase: 'Hai compiuto la Costellazione del Viso in 55 giorni diversi.',
    posizione: 28,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'La mappa completa dei tratti, con quelli che si sono mossi',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Profondita',
    sezioneDelCammino: 'IL FIORE CHE RESPIRA',
  ),
  Traguardo(
    id: 'aur_29',
    nome: 'L’Archetipo di Mercurio retrogrado',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.mercurioRetrogrado,
        conGesto: 'archetipo'),
    frase: 'Mercurio è retrogrado: tu eri qui con l’Archetipo.',
    posizione: 29,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre:
        'L’Archetipo dell’ombra, che si mostra solo a Mercurio retrogrado',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'IL FIORE CHE RESPIRA',
  ),
  Traguardo(
    id: 'aur_30',
    nome: 'Sessanta giorni pieni',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GiornateInsieme(['due_volti', 'soffio', 'viso'], 60),
    frase: '60 giornate con 3 arti diverse, nello stesso giorno.',
    posizione: 30,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Il ritratto energetico, che unisce respiro e volto',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Legame',
    sezioneDelCammino: 'IL FIORE CHE RESPIRA',
  ),
  Traguardo(
    id: 'aur_31',
    nome: 'Settantacinque albe',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GestiCompiuti('alba', 75, inGiorniDiversi: true),
    frase: 'Hai compiuto il Rito dell’Alba in 75 giorni diversi.',
    posizione: 31,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il confronto fra le tue albe e le stagioni che le hanno viste',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Profondita',
    sezioneDelCammino: 'IL FIORE CHE RESPIRA',
  ),
  Traguardo(
    id: 'aur_32',
    nome: 'Ottanta Soffi in cento giorni',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDentroUnArco('soffio', 80, 100),
    frase:
        '80 giorni con il Soffio del Destino negli ultimi 100: nessuno te l’ha chiesto.',
    posizione: 32,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'La costanza riconosciuta, che Aura nomina nelle sue risposte',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Costanza',
    sezioneDelCammino: 'IL FIORE CHE RESPIRA',
  ),
  Traguardo(
    id: 'aur_33',
    nome: 'L’Alba dell’eclissi',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione:
        const FinestraDelCielo(EventiDelCielo.eclissi, conGesto: 'alba'),
    frase: 'Il cielo porta un’eclissi: tu eri qui con il Rito dell’Alba.',
    posizione: 33,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Il rito dell’eclissi, che il Cerchio conserva per sempre',
    eGrande: true,
    eos: 80,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'IL FIORE CHE RESPIRA',
  ),
  Traguardo(
    id: 'aur_34',
    nome: 'Il Soffio del solstizio',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione:
        const FinestraDelCielo(EventiDelCielo.solstizio, conGesto: 'soffio'),
    frase: 'Il Sole tocca il solstizio: tu eri qui con il Soffio del Destino.',
    posizione: 34,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Il respiro del solstizio, che torna due volte l’anno',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'IL FIORE DELLA STAGIONE',
  ),
  Traguardo(
    id: 'aur_35',
    nome: 'Cento albe',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GestiCompiuti('alba', 100, inGiorniDiversi: true),
    frase: 'Hai compiuto il Rito dell’Alba in 100 giorni diversi.',
    posizione: 35,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Lo Specchio del mattino, che confronta cento risvegli',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Profondita',
    sezioneDelCammino: 'IL FIORE DELLA STAGIONE',
  ),
  Traguardo(
    id: 'aur_36',
    nome: 'Centodieci Soffi in centoquaranta giorni',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDentroUnArco('soffio', 110, 140),
    frase:
        '110 giorni con il Soffio del Destino negli ultimi 140: nessuno te l’ha chiesto.',
    posizione: 36,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'La memoria lunga di Aura, che ricorda come respiravi a marzo',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Costanza',
    sezioneDelCammino: 'IL FIORE DELLA STAGIONE',
  ),
  Traguardo(
    id: 'aur_37',
    nome: 'L’Alba di Mercurio diretto',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.mercurioDiretto,
        conGesto: 'alba'),
    frase: 'Mercurio torna diretto: tu eri qui con il Rito dell’Alba.',
    posizione: 37,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Il rito del ritorno, quando Mercurio riprende il cammino',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'IL FIORE DELLA STAGIONE',
  ),
  Traguardo(
    id: 'aur_38',
    nome: 'Il Soffio di Giove retrogrado',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.gioveRetrogrado,
        conGesto: 'soffio'),
    frase: 'Giove è retrogrado: tu eri qui con il Soffio del Destino.',
    posizione: 38,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Il capitolo dell’abbondanza che si ripiega, raro e lungo',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'IL FIORE DELLA STAGIONE',
  ),
  Traguardo(
    id: 'aur_39',
    nome: 'Centoquaranta meditazioni',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GestiCompiuti('meditazione', 140, inGiorniDiversi: true),
    frase: 'Hai compiuto la Meditazione in 140 giorni diversi.',
    posizione: 39,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Le meditazioni che Aura scrive per te, non più dal catalogo',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Profondita',
    sezioneDelCammino: 'IL FIORE DELLA STAGIONE',
  ),
  Traguardo(
    id: 'aur_40',
    nome: 'Centocinquanta giornate intere',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione:
        const GiornateInsieme(['alba', 'archetipo', 'soffio', 'viso'], 150),
    frase: '150 giornate con 4 arti diverse, nello stesso giorno.',
    posizione: 40,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Il ritratto delle quattro pratiche, che nessuna dice da sola',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Legame',
    sezioneDelCammino: 'IL FIORE DELLA STAGIONE',
  ),
  Traguardo(
    id: 'aur_41',
    nome: 'Centosessanta albe in duecento giorni',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDentroUnArco('alba', 160, 200),
    frase:
        '160 giorni con il Rito dell’Alba negli ultimi 200: nessuno te l’ha chiesto.',
    posizione: 41,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'La stagione riconosciuta, con il tuo risveglio dell’anno',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Costanza',
    sezioneDelCammino: 'IL FIORE DELLA STAGIONE',
  ),
  Traguardo(
    id: 'aur_42',
    nome: 'Centosessantacinque Archetipi',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GestiCompiuti('archetipo', 165, inGiorniDiversi: true),
    frase: 'Hai compiuto l’Archetipo in 165 giorni diversi.',
    posizione: 42,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'La storia del tuo Archetipo, con tutte le sue mutazioni',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Profondita',
    sezioneDelCammino: 'IL FIORE DELLA STAGIONE',
  ),
  Traguardo(
    id: 'aur_43',
    nome: 'L’ora che non cambia',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const StessaOraPerGiorni('alba', 170),
    frase:
        '170 giorni alla stessa ora con il Rito dell’Alba: l’abitudine ha trovato il suo posto.',
    posizione: 43,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'Il tuo rito fisso, che Aura protegge dalle notifiche',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Costanza',
    sezioneDelCammino: 'IL FIORE DELLA STAGIONE',
  ),
  Traguardo(
    id: 'aur_44',
    nome: 'Il Soffio del tuo Sole',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.soleNelTuoSegno,
        conGesto: 'soffio'),
    frase:
        'Il Sole attraversa il tuo segno: tu eri qui con il Soffio del Destino.',
    posizione: 44,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre:
        'Il mese del compleanno, col respiro che si pratica una volta l’anno',
    eGrande: true,
    eos: 100,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'IL FIORE DELLA STAGIONE',
  ),
  Traguardo(
    id: 'aur_45',
    nome: 'Centonovantuna albe',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GestiCompiuti('alba', 191, inGiorniDiversi: true),
    frase: 'Hai compiuto il Rito dell’Alba in 191 giorni diversi.',
    posizione: 45,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre:
        'L’archivio completo delle tue albe, con la parola di ogni giorno',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Profondita',
    sezioneDelCammino: 'IL FIORE COMPIUTO',
  ),
  Traguardo(
    id: 'aur_46',
    nome: 'Duecento Soffi in duecentocinquanta giorni',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDentroUnArco('soffio', 200, 250),
    frase:
        '200 giorni con il Soffio del Destino negli ultimi 250: nessuno te l’ha chiesto.',
    posizione: 46,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'Il capitolo dell’anno, che Aura scrive solo per chi c’è stato',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Costanza',
    sezioneDelCammino: 'IL FIORE COMPIUTO',
  ),
  Traguardo(
    id: 'aur_47',
    nome: 'Duecentoventi giornate di pratica',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GiornateInsieme(['alba', 'archetipo', 'due_volti'], 220),
    frase: '220 giornate con 3 arti diverse, nello stesso giorno.',
    posizione: 47,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre:
        'Il ritratto lungo di Aura, che tiene insieme risveglio, Archetipo e volti',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Legame',
    sezioneDelCammino: 'IL FIORE COMPIUTO',
  ),
  Traguardo(
    id: 'aur_48',
    nome: 'L’Alba di Giove diretto',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione:
        const FinestraDelCielo(EventiDelCielo.gioveDiretto, conGesto: 'alba'),
    frase: 'Giove torna diretto: tu eri qui con il Rito dell’Alba.',
    posizione: 48,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Il capitolo dell’espansione, che apre l’anno che viene',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'IL FIORE COMPIUTO',
  ),
  Traguardo(
    id: 'aur_49',
    nome: 'Il Soffio di Saturno diretto',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.saturnoDiretto,
        conGesto: 'soffio'),
    frase: 'Saturno torna diretto: tu eri qui con il Soffio del Destino.',
    posizione: 49,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre:
        'Il respiro della prova superata, che Saturno concede tornando diretto',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'IL FIORE COMPIUTO',
  ),
  Traguardo(
    id: 'aur_50',
    nome: 'Duecentottanta volti',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GestiCompiuti('viso', 280, inGiorniDiversi: true),
    frase: 'Hai compiuto la Costellazione del Viso in 280 giorni diversi.',
    posizione: 50,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il tuo volto nel tempo, con la lettura di come è cambiato',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Profondita',
    sezioneDelCammino: 'IL FIORE COMPIUTO',
  ),
  Traguardo(
    id: 'aur_51',
    nome: 'I Due Volti di Venere retrograda',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.venereRetrograda,
        conGesto: 'due_volti'),
    frase: 'Venere è retrograda: tu eri qui con i Due Volti.',
    posizione: 51,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Il capitolo degli affetti che tornano, uno ogni diciotto mesi',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'IL FIORE COMPIUTO',
  ),
  Traguardo(
    id: 'aur_52',
    nome: 'Trecento albe in trecentoquaranta giorni',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDentroUnArco('alba', 300, 340),
    frase:
        '300 giorni con il Rito dell’Alba negli ultimi 340: nessuno te l’ha chiesto.',
    posizione: 52,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'Il titolo di custode dell’Alba, che pochi vedranno',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Costanza',
    sezioneDelCammino: 'IL FIORE COMPIUTO',
  ),
  Traguardo(
    id: 'aur_53',
    nome: 'Trecentoventi giornate complete',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GiornateInsieme(
        ['alba', 'archetipo', 'due_volti', 'meditazione', 'soffio', 'viso'],
        320),
    frase: '320 giornate con 6 arti diverse, nello stesso giorno.',
    posizione: 53,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Il Fiore intero, con tutte e sei le pratiche in una sola pagina',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Legame',
    sezioneDelCammino: 'IL FIORE COMPIUTO',
  ),
  Traguardo(
    id: 'aur_54',
    nome: 'Trecentoquaranta Soffi',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GestiCompiuti('soffio', 340, inGiorniDiversi: true),
    frase: 'Hai compiuto il Soffio del Destino in 340 giorni diversi.',
    posizione: 54,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il respiro che ti conosce, col ritmo che il tuo corpo ha scelto',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Profondita',
    sezioneDelCammino: 'IL FIORE COMPIUTO',
  ),
  Traguardo(
    id: 'aur_55',
    nome: 'Il tuo ritorno solare',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione:
        const FinestraDelCielo(EventiDelCielo.ritornoSolare, conGesto: 'alba'),
    frase:
        'Il Sole torna dov’era quando sei nato: tu eri qui con il Rito dell’Alba.',
    posizione: 55,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Il rito del ritorno solare, il risveglio del tuo anno nuovo',
    eGrande: true,
    eos: 130,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'IL FIORE COMPIUTO',
  ),
];
