// GENERATO DA tool/genera_sentieri_dal_corpus.py: NON SI SCRIVE
// A MANO. Ordine AR voce 02.
//
// La fonte e' docs/corpus/Traguardi_165_Revisione_E.json, e il
// dato comanda: nomi, condizioni, fasce, Eos e porte vengono da
// li' verbatim. Per cambiare un traguardo si cambia il corpus e
// si rigenera, mai il contrario.

import 'eventi_del_cielo.dart';
import 'traguardo.dart';

final List<Traguardo> sentieroDellaCostellazione = [
  Traguardo(
    id: 'med_1',
    nome: 'La tua carta è nata',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('carta_natale', 1),
    frase: 'Calcoli la carta natale con data, ora e luogo di nascita.',
    posizione: 1,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Il Cosmic Passport',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Prima volta',
    sezioneDelCammino: 'LA COSTELLAZIONE NASCENTE',
  ),
  Traguardo(
    id: 'med_2',
    nome: 'Il segno che sale',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const Dormiente('med_2', 'la lettura FINO IN FONDO non arriva alla regia: la schermata manda il gesto quando si apre, non quando si è letta tutta. Servirebbe che la scena segnasse la fine della lettura'),
    frase: 'Apri la scheda del tuo Ascendente e la leggi fino in fondo.',
    posizione: 2,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Le dodici case, che senza Ascendente non esistono',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: true,
    ragione: 'Profondità',
    sezioneDelCammino: 'LA COSTELLAZIONE NASCENTE',
  ),
  Traguardo(
    id: 'med_3',
    nome: 'La prima stesa',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('stesa', 1),
    frase: 'Porti a termine una Stesa fino all\'ultima carta.',
    posizione: 3,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'La scelta della domanda nella Stesa',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Prima volta',
    sezioneDelCammino: 'LA COSTELLAZIONE NASCENTE',
  ),
  Traguardo(
    id: 'med_4',
    nome: 'Il cielo di oggi ti riguarda',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('oracolo', 1),
    frase: 'Apri il tuo primo Arcano del Giorno.',
    posizione: 4,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'I Doni del giorno',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Prima volta',
    sezioneDelCammino: 'LA COSTELLAZIONE NASCENTE',
  ),
  Traguardo(
    id: 'med_5',
    nome: 'Il tuo Angelo ha un nome',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('angelo_custode', 1),
    frase: 'Scopri quale dei settantadue Angeli ti accompagna.',
    posizione: 5,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Il Messaggio del giorno dell\'Angelo',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Prima volta',
    sezioneDelCammino: 'LA COSTELLAZIONE NASCENTE',
  ),
  Traguardo(
    id: 'med_6',
    nome: 'Il primo oroscopo letto intero',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('oroscopo', 1),
    frase: 'Non solo apri l\'Oroscopo: lo scorri fino all\'ultima riga.',
    posizione: 6,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'La Riflessione del Cielo',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Profondità',
    sezioneDelCammino: 'LA COSTELLAZIONE NASCENTE',
  ),
  Traguardo(
    id: 'med_7',
    nome: 'Quello che il Cerchio ricorda di te',
    famiglia: FamigliaDelTraguardo.identita,
    condizione: const PezzoDellIdentita('nascita_completa'),
    frase: 'Data, ora e luogo di nascita sono tutti e tre nel tuo profilo.',
    posizione: 7,
    percheConta: FamigliaDelTraguardo.identita.percheContaLaFamiglia,
    cosaApre: 'I transiti veri sopra la tua carta',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Identità',
    sezioneDelCammino: 'LA COSTELLAZIONE NASCENTE',
  ),
  Traguardo(
    id: 'med_8',
    nome: 'La prima stella condivisa',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const GestoDelCerchio('condivisione_stella', 1),
    frase: 'Condividi pubblicamente un responso di Medora.',
    posizione: 8,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'Il bonus della condivisione',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Legame',
    sezioneDelCammino: 'LA COSTELLAZIONE NASCENTE',
  ),
  Traguardo(
    id: 'med_9',
    nome: 'La prima affinità',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('sinastria', 1),
    frase: 'Confronti il tuo cielo con quello di una persona famosa.',
    posizione: 9,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'La Collezione delle coppie',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Prima volta',
    sezioneDelCammino: 'LA COSTELLAZIONE NASCENTE',
  ),
  Traguardo(
    id: 'med_10',
    nome: 'Due domande diverse',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const VarietaDelDettaglio('stesa', 'argomento', 2),
    frase: 'Due Stese su due argomenti diversi.',
    posizione: 10,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'La scelta della profondità della lettura',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Profondità',
    sezioneDelCammino: 'LA COSTELLAZIONE NASCENTE',
  ),
  Traguardo(
    id: 'med_11',
    nome: 'LA COSTELLAZIONE NASCENTE',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GradiniAlleSpalle('costellazione', 10),
    frase: 'Dieci gradini qualunque della Costellazione alle spalle.',
    posizione: 11,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'La Riflessione del Cielo in versione estesa',
    eGrande: true,
    eos: 40,
    fascia: 'Primi giorni',
    dormiente: false,
    ragione: 'Perla',
    sezioneDelCammino: 'LA COSTELLAZIONE NASCENTE',
  ),
  Traguardo(
    id: 'med_12',
    nome: 'La carta che ti cerca',
    famiglia: FamigliaDelTraguardo.memoria,
    condizione: const CoincidenzaDelDettaglio('stesa', 'carte', 2),
    frase: 'La stessa carta esce in due Stese diverse.',
    posizione: 12,
    percheConta: FamigliaDelTraguardo.memoria.percheContaLaFamiglia,
    cosaApre: 'Il Filo fra le carte',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Coincidenza',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA LETTURA',
  ),
  Traguardo(
    id: 'med_13',
    nome: 'Le quattro chiavi',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const VarietaDelDettaglio('stesa', 'argomento', 4),
    frase: 'Quattro argomenti diversi interrogati nelle tue Stese.',
    posizione: 13,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Gli argomenti rari del selettore',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Profondità',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA LETTURA',
  ),
  Traguardo(
    id: 'med_14',
    nome: 'La stella mandata a una persona sola',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const Dormiente('med_14', 'mandare un responso in privato invece che al mondo chiede il canale della condivisione, che il gesto non porta: la regia sa che si e condiviso, non dove'),
    frase: 'Mandi un responso a qualcuno in privato, non al mondo.',
    posizione: 14,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'Il bonus della condivisione privata',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: true,
    ragione: 'Legame',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA LETTURA',
  ),
  Traguardo(
    id: 'med_15',
    nome: 'Tre giorni sotto lo stesso cielo',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDiSeguito('oracolo', 3),
    frase: 'Apri l\'Arcano del Giorno tre giorni di seguito.',
    posizione: 15,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'Il ricordo dell\'Arcano di ieri',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Costanza',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA LETTURA',
  ),
  Traguardo(
    id: 'med_16',
    nome: 'La carta al rovescio',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const Dormiente('med_16', 'la carta rovesciata non viaggia coi dettagli della stesa: la scena manda carte, semi, maggiori e argomento. Servirebbe un dettaglio nuovo, il verso della carta'),
    frase: 'Per la prima volta una carta esce rovesciata e tu la leggi.',
    posizione: 16,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'L\'interruttore delle carte rovesciate',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: true,
    ragione: 'Profondità',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA LETTURA',
  ),
  Traguardo(
    id: 'med_17',
    nome: 'Il primo che entra grazie a te',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const Dormiente('med_17', 'il gesto del Cerchio invito non arriva alla regia'),
    frase: 'Qualcuno accetta il tuo invito ed entra nel Cerchio.',
    posizione: 17,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'I sessanta Eos dell\'invito accolto',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: true,
    ragione: 'Legame',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA LETTURA',
  ),
  Traguardo(
    id: 'med_18',
    nome: 'Il giorno intero di Medora',
    famiglia: FamigliaDelTraguardo.giornata,
    condizione: const GestiNelloStessoGiorno(['oracolo', 'stesa', 'oroscopo']),
    frase: 'Oracolo, Oroscopo e Stesa nello stesso giorno.',
    posizione: 18,
    percheConta: FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
    cosaApre: 'Il riepilogo della giornata nel Journal',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Coincidenza',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA LETTURA',
  ),
  Traguardo(
    id: 'med_19',
    nome: 'Il secondo mazzo',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const Dormiente('med_19', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: i mazzi multipli sono MVP, non Demo'),
    frase: 'Una Stesa con un mazzo diverso dal Rider-Waite.',
    posizione: 19,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Marsiglia e Thoth',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: true,
    ragione: 'Profondità',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA LETTURA',
  ),
  Traguardo(
    id: 'med_20',
    nome: 'Mercurio torna indietro',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.mercurioRetrogrado, conGesto: 'oroscopo'),
    frase: 'Leggi l\'Oroscopo mentre Mercurio è retrogrado.',
    posizione: 20,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Il Calendario degli Eventi',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA LETTURA',
  ),
  Traguardo(
    id: 'med_21',
    nome: 'Tre affinità',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('sinastria', 3),
    frase: 'Tre Sinastrie diverse compiute.',
    posizione: 21,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Il confronto fra due persone famose',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Legame',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA LETTURA',
  ),
  Traguardo(
    id: 'med_22',
    nome: 'LA COSTELLAZIONE DELLA LETTURA',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GradiniAlleSpalle('costellazione', 21),
    frase: 'Ventuno gradini qualunque della Costellazione alle spalle.',
    posizione: 22,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Le tre chiavi di lettura della Stesa',
    eGrande: true,
    eos: 60,
    fascia: 'Prima settimana',
    dormiente: false,
    ragione: 'Perla',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA LETTURA',
  ),
  Traguardo(
    id: 'med_23',
    nome: 'Il Sole nel tuo segno',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.soleNelTuoSegno, conGesto: 'oroscopo'),
    frase: 'Leggi l\'Oroscopo nei giorni in cui il Sole attraversa il tuo segno.',
    posizione: 23,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'La lettura del tuo compleanno astrale',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA COSTELLAZIONE DEL CIELO VERO',
  ),
  Traguardo(
    id: 'med_24',
    nome: 'Il transito sul tuo Sole',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.transitoSulSole),
    frase: 'Un pianeta lento passa sul grado del tuo Sole di nascita e tu lo leggi.',
    posizione: 24,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'La scheda del transito nel Passaporto',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA COSTELLAZIONE DEL CIELO VERO',
  ),
  Traguardo(
    id: 'med_25',
    nome: 'Il ritorno dopo il vuoto',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const Dormiente('med_25', 'l app registra i gesti, non da quale Maestro si torni: "torni a Medora dopo sette giorni" e "torni a Caligo dopo sette giorni" misurano lo stesso identico fatto. Due gradini per un fatto solo sono un gradino detto due volte'),
    frase: 'Torni a Medora dopo sette giorni in cui non l\'hai cercata.',
    posizione: 25,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'Il saluto di Medora a chi rientra',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: true,
    ragione: 'Ritorno',
    sezioneDelCammino: 'LA COSTELLAZIONE DEL CIELO VERO',
  ),
  Traguardo(
    id: 'med_26',
    nome: 'Tutti e quattro i semi',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const VarietaDelDettaglio('stesa', 'semi', 4),
    frase: 'Coppe, Denari, Spade e Bastoni sono usciti almeno una volta.',
    posizione: 26,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'La lettura per seme dominante',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Profondità',
    sezioneDelCammino: 'LA COSTELLAZIONE DEL CIELO VERO',
  ),
  Traguardo(
    id: 'med_27',
    nome: 'Le tre chiavi di lettura',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const Dormiente('med_27', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: le tre chiavi sono MVP, non Demo'),
    frase: 'Interroghi la stessa Stesa con un metodo di interpretazione diverso.',
    posizione: 27,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'I tre metodi di lettura',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: true,
    ragione: 'Profondità',
    sezioneDelCammino: 'LA COSTELLAZIONE DEL CIELO VERO',
  ),
  Traguardo(
    id: 'med_28',
    nome: 'Il giorno del Sole fermo',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.solstizio),
    frase: 'Un responso di Medora nel giorno di un solstizio o di un equinozio.',
    posizione: 28,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Le quattro porte dell\'anno nel Calendario',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA COSTELLAZIONE DEL CIELO VERO',
  ),
  Traguardo(
    id: 'med_29',
    nome: 'La stella che ha viaggiato',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const Dormiente('med_29', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: serve il tracciamento delle condivisioni'),
    frase: 'Un tuo responso condiviso viene aperto da qualcuno fuori dal Cerchio.',
    posizione: 29,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'Il conto di chi ha visto le tue stelle',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: true,
    ragione: 'Legame',
    sezioneDelCammino: 'LA COSTELLAZIONE DEL CIELO VERO',
  ),
  Traguardo(
    id: 'med_30',
    nome: 'Metà del ventaglio',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const VarietaDelDettaglio('stesa', 'carte', 39),
    frase: 'Trentanove carte diverse uscite nelle tue Stese.',
    posizione: 30,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il ventaglio completo nel Journal',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Profondità',
    sezioneDelCammino: 'LA COSTELLAZIONE DEL CIELO VERO',
  ),
  Traguardo(
    id: 'med_31',
    nome: 'L\'Arcano che insiste',
    famiglia: FamigliaDelTraguardo.giornata,
    condizione: const Dormiente('med_31', 'il diario conta le ripetizioni DA SEMPRE, non dentro una finestra di tempo: "due volte in una settimana" chiede una memoria con le date che il diario non tiene'),
    frase: 'Lo stesso Arcano del Giorno esce due volte in una settimana.',
    posizione: 31,
    percheConta: FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
    cosaApre: 'La nota di Medora sull\'Arcano che torna',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: true,
    ragione: 'Coincidenza',
    sezioneDelCammino: 'LA COSTELLAZIONE DEL CIELO VERO',
  ),
  Traguardo(
    id: 'med_32',
    nome: 'L\'Oracolo degli Angeli',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const Dormiente('med_32', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: Oracolo degli Angeli, fase 2'),
    frase: 'La tua prima consultazione del mazzo dei settantadue Angeli.',
    posizione: 32,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'I Nove Cori',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: true,
    ragione: 'Prima volta',
    sezioneDelCammino: 'LA COSTELLAZIONE DEL CIELO VERO',
  ),
  Traguardo(
    id: 'med_33',
    nome: 'LA COSTELLAZIONE DEL CIELO VERO',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GradiniAlleSpalle('costellazione', 32),
    frase: 'Trentadue gradini qualunque della Costellazione alle spalle.',
    posizione: 33,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'La mappa dei transiti sulla tua carta',
    eGrande: true,
    eos: 80,
    fascia: 'Primo mese',
    dormiente: false,
    ragione: 'Perla',
    sezioneDelCammino: 'LA COSTELLAZIONE DEL CIELO VERO',
  ),
  Traguardo(
    id: 'med_34',
    nome: 'L\'ora fedele',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const Dormiente('med_34', 'l app sa se un gesto cade nell ora rituale dell alba, del tramonto o della notte, non se cade sempre alla STESSA ora: servirebbe la memoria dell ora di ogni gesto'),
    frase: 'Apri l\'Oroscopo alla stessa ora per cinque giorni.',
    posizione: 34,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'L\'appuntamento fisso col tuo cielo',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Costanza',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA MEMORIA',
  ),
  Traguardo(
    id: 'med_35',
    nome: 'Il transito sul tuo Ascendente',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.transitoSullAscendente),
    frase: 'Un pianeta lento passa sul grado del tuo Ascendente e tu lo leggi.',
    posizione: 35,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'La lettura dell\'Ascendente in transito',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA MEMORIA',
  ),
  Traguardo(
    id: 'med_36',
    nome: 'Il tema che torna',
    famiglia: FamigliaDelTraguardo.giornata,
    condizione: const Dormiente('med_36', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: il Filo dei Temi è la prescrizione P32, aperta'),
    frase: 'Tre Stese sullo stesso argomento in tre mesi diversi.',
    posizione: 36,
    percheConta: FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
    cosaApre: 'Il Filo dei Temi',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Coincidenza',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA MEMORIA',
  ),
  Traguardo(
    id: 'med_37',
    nome: 'Il tuo cielo su una pagina sola',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const Dormiente('med_37', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: nelle funzioni wow MVP, P35'),
    frase: 'Generi il tuo Cosmic CV col codice da inquadrare.',
    posizione: 37,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Il Cosmic CV',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Prima volta',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA MEMORIA',
  ),
  Traguardo(
    id: 'med_38',
    nome: 'La Luna piena nel tuo segno',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.lunaPienaNelTuoSegno, conGesto: 'stesa'),
    frase: 'Una Stesa nella notte in cui la Luna piena cade nel tuo segno.',
    posizione: 38,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Il rito della Luna nel tuo segno',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA MEMORIA',
  ),
  Traguardo(
    id: 'med_39',
    nome: 'Il cielo puntato dalla fotocamera',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const Dormiente('med_39', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: funzioni wow MVP, P35. Sostituisce un terzo traguardo di transito, che era ripetizione'),
    frase: 'Inquadri un luogo e l\'app ti dice che cielo ci sta sopra adesso.',
    posizione: 39,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Il Cosmic Scan',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Prima volta',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA MEMORIA',
  ),
  Traguardo(
    id: 'med_40',
    nome: 'Tutti i sedici argomenti',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const Dormiente('med_40', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: l\'argomento libero è MVP'),
    frase: 'Ogni argomento della Stesa interrogato almeno una volta.',
    posizione: 40,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'L\'argomento libero, scritto da te',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Profondità',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA MEMORIA',
  ),
  Traguardo(
    id: 'med_41',
    nome: 'La stessa carta in tre Lune',
    famiglia: FamigliaDelTraguardo.giornata,
    condizione: const Dormiente('med_41', 'la fase lunare non viaggia coi dettagli del gesto: servirebbe che la scena la passasse. È un dettaglio nuovo'),
    frase: 'La stessa carta esce sotto tre fasi lunari diverse.',
    posizione: 41,
    percheConta: FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
    cosaApre: 'La scheda della carta che ti segue',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Coincidenza',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA MEMORIA',
  ),
  Traguardo(
    id: 'med_42',
    nome: 'La Croce Celtica',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const Dormiente('med_42', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: stese oltre le tre carte, MVP'),
    frase: 'Una Stesa a dieci carte portata a termine.',
    posizione: 42,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Le stese lunghe',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Profondità',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA MEMORIA',
  ),
  Traguardo(
    id: 'med_43',
    nome: 'Due persone famose una contro l\'altra',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const Dormiente('med_43', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: VIP contro VIP è la prescrizione P33'),
    frase: 'Metti a confronto due celebrità fra loro.',
    posizione: 43,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'La content machine delle coppie VIP',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: true,
    ragione: 'Prima volta',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA MEMORIA',
  ),
  Traguardo(
    id: 'med_44',
    nome: 'LA COSTELLAZIONE DELLA MEMORIA',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GradiniAlleSpalle('costellazione', 43),
    frase: 'Quarantatre gradini qualunque della Costellazione alle spalle.',
    posizione: 44,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il Journal della memoria lunga',
    eGrande: true,
    eos: 100,
    fascia: 'La stagione',
    dormiente: false,
    ragione: 'Perla',
    sezioneDelCammino: 'LA COSTELLAZIONE DELLA MEMORIA',
  ),
  Traguardo(
    id: 'med_45',
    nome: 'Un mese sotto lo stesso cielo',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDiSeguito('oracolo', 30),
    frase: 'Trenta Arcani del Giorno di seguito.',
    posizione: 45,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: 'Il sigillo del mese pieno',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Costanza',
    sezioneDelCammino: 'LA COSTELLAZIONE COMPIUTA',
  ),
  Traguardo(
    id: 'med_46',
    nome: 'Il tuo ritorno solare',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const Dormiente('med_46', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: il rito del Ritorno Solare è fase 2', eraDelCielo: true),
    frase: 'Un responso nell\'istante in cui il Sole torna dov\'era alla tua nascita.',
    posizione: 46,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'La lettura del Ritorno Solare',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA COSTELLAZIONE COMPIUTA',
  ),
  Traguardo(
    id: 'med_47',
    nome: 'Saturno torna indietro',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.saturnoRetrogrado, conGesto: 'oroscopo'),
    frase: 'Leggi l\'Oroscopo mentre Saturno è retrogrado.',
    posizione: 47,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'La lettura di Saturno nel Calendario',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA COSTELLAZIONE COMPIUTA',
  ),
  Traguardo(
    id: 'med_48',
    nome: 'Dodici stelle condivise',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const GestoDelCerchio('condivisione_stella', 12),
    frase: 'Dodici responsi di Medora condivisi.',
    posizione: 48,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'Il grado di Voce del Cerchio',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Legame',
    sezioneDelCammino: 'LA COSTELLAZIONE COMPIUTA',
  ),
  Traguardo(
    id: 'med_49',
    nome: 'I Nove Cori',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const Dormiente('med_49', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: Oracolo degli Angeli, fase 2. Sostituisce Tutte le settantotto, che ripeteva Metà del ventaglio'),
    frase: 'Consulti gli Angeli in tutti e nove i Cori.',
    posizione: 49,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'La lettura per Coro angelico',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
    ragione: 'Profondità',
    sezioneDelCammino: 'LA COSTELLAZIONE COMPIUTA',
  ),
  Traguardo(
    id: 'med_50',
    nome: 'L\'eclissi sopra il Cerchio',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const Dormiente('med_50', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: il motore delle eclissi non esiste', eraDelCielo: true),
    frase: 'Un responso di Medora nelle ore di un\'eclissi.',
    posizione: 50,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'La Reliquia del Cielo di quella data',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA COSTELLAZIONE COMPIUTA',
  ),
  Traguardo(
    id: 'med_51',
    nome: 'Il volto del Cerchio in movimento',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const Dormiente('med_51', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: funzioni wow MVP, P35'),
    frase: 'Registri una Cosmic Story col tuo cielo del giorno.',
    posizione: 51,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Le Cosmic Stories',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
    ragione: 'Prima volta',
    sezioneDelCammino: 'LA COSTELLAZIONE COMPIUTA',
  ),
  Traguardo(
    id: 'med_52',
    nome: 'Il tuo cielo trovato davvero',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const Dormiente('med_52', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: Real Time Cosmo, priorità dopo la Demo'),
    frase: 'Inquadri il cielo e riconosci la tua costellazione.',
    posizione: 52,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Real Time Cosmo',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
    ragione: 'Prima volta',
    sezioneDelCammino: 'LA COSTELLAZIONE COMPIUTA',
  ),
  Traguardo(
    id: 'med_53',
    nome: 'La Reliquia che nessuno avrà più',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const Dormiente('med_53', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: Reliquie del Cielo, fase 2', eraDelCielo: true),
    frase: 'Compi il rito di una notte rara e ricevi il Sigillo datato.',
    posizione: 53,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Le Reliquie del Cielo',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
    ragione: 'Cielo',
    sezioneDelCammino: 'LA COSTELLAZIONE COMPIUTA',
  ),
  Traguardo(
    id: 'med_54',
    nome: 'Il Cerchio che hai costruito',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const Dormiente('med_54', 'il corpus della revisione E lo dichiara dormiente. La sua ragione è questa: serve il conto degli inviti accolti'),
    frase: 'Cinque persone sono entrate nel Cerchio grazie ai tuoi inviti.',
    posizione: 54,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'Il grado di Fondatore di Cerchio',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
    ragione: 'Legame',
    sezioneDelCammino: 'LA COSTELLAZIONE COMPIUTA',
  ),
  Traguardo(
    id: 'med_55',
    nome: 'LA COSTELLAZIONE COMPIUTA',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GradiniAlleSpalle('costellazione', 54),
    frase: 'Cinquantaquattro gradini della Costellazione alle spalle.',
    posizione: 55,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'Il Cammino della fase successiva',
    eGrande: true,
    eos: 130,
    fascia: 'L\'anno',
    dormiente: false,
    ragione: 'Perla',
    sezioneDelCammino: 'LA COSTELLAZIONE COMPIUTA',
  ),
];
