import 'eventi_del_cielo.dart';
import 'traguardo.dart';

/// IL FIORE DI LOTO, il sentiero di Aura.
///
/// I Petali del Risveglio sono i cinquanta traguardi piccoli, le Fioriture
/// sono i cinque grandi. Il tono e' quello di Aura: il respiro, il corpo che
/// sa prima della testa, la cura senza promesse.
///
/// I GESTI DI QUESTO SENTIERO: `soffio` (il Soffio del Destino),
/// `meditazione`, `chakra`, `viso` (la Costellazione del Viso), `archetipo`,
/// `consulto_aura`. Piu' i gesti comuni: `alba`, `oracolo`, `tramonto`.
Traguardo _t(
  String id,
  String nome,
  FamigliaDelTraguardo famiglia,
  CondizioneDelTraguardo condizione,
  String frase,
  int posizione,
) =>
    Traguardo(
      id: id,
      nome: nome,
      famiglia: famiglia,
      condizione: condizione,
      frase: frase,
      posizione: posizione,
    );

/// Lo stesso, per i cinque GRANDI: il dato dice che sono grandi, cosi' la
/// posizione non deve indovinarlo.
Traguardo _g(
  String id,
  String nome,
  FamigliaDelTraguardo famiglia,
  CondizioneDelTraguardo condizione,
  String frase,
  int posizione,
) =>
    Traguardo(
      id: id,
      nome: nome,
      famiglia: famiglia,
      condizione: condizione,
      frase: frase,
      posizione: posizione,
      eGrande: true,
    );

final List<Traguardo> sentieroDelLoto = [
  _t('aur_1', 'La tua carta è nata', FamigliaDelTraguardo.identita,
      const PezzoDellIdentita('carta_natale'),
      'La tua carta natale è calcolata: anche il respiro adesso ha un cielo di riferimento.',
      1),
  _t('aur_2', 'Il tuo Angelo ha un nome', FamigliaDelTraguardo.identita,
      const PezzoDellIdentita('angelo_custode'),
      'Il tuo Angelo Custode ha un nome: qualcuno respira insieme a te.',
      2),
  _t('aur_3', 'Il tuo Animale ti ha trovato', FamigliaDelTraguardo.identita,
      const PezzoDellIdentita('animale_guida'),
      'Il tuo Animale Guida si è mostrato: il primo Petalo del Risveglio si apre per lui.',
      3),
  _t('aur_4', 'Il mattino aperto', FamigliaDelTraguardo.giornata,
      const GestiNelloStessoGiorno(['alba', 'soffio']),
      'Alba e Soffio nello stesso mattino: hai aperto il giorno respirando, non correndo.',
      4),
  _t('aur_5', 'Tre soffi', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('soffio', 3),
      'Tre Soffi del Destino: il respiro ha cominciato a rispondere prima delle parole.',
      5),
  _t('aur_6', 'Il primo quarto', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.primoQuarto, conGesto: 'soffio'),
      'Hai respirato al primo quarto di Luna: la fase che chiede una decisione a metà strada.',
      6),
  _t('aur_7', 'Due albe di seguito', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('alba', 2),
      'Due albe di seguito: la seconda mattina è quella che decide se sarà un\'abitudine.',
      7),
  _t('aur_8', 'Respiro e centro', FamigliaDelTraguardo.ampiezza,
      const GestiNelloStessoGiorno(['soffio', 'chakra']),
      'Soffio e Chakra nello stesso giorno: hai chiesto al corpo e poi lo hai ascoltato.',
      8),
  _t('aur_9', 'Cinque soffi in giorni diversi', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('soffio', 5, inGiorniDiversi: true),
      'Cinque Soffi in cinque giorni: il respiro non è più un esercizio, è un appuntamento.',
      9),
  _t('aur_10', 'La Luna che cresce', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.lunaCrescente,
          conGesto: 'meditazione'),
      'Hai meditato con la Luna crescente: quello che semini adesso ha spazio per salire.',
      10),
  _t('aur_11', 'Aura ricorda', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('momenti_aura', 8),
      'Otto tuoi momenti custoditi da Aura: comincia a sapere come respiri.',
      11),
  _t('aur_12', 'Tre mattine di seguito', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('alba', 3),
      'Tre mattine di seguito: il Rito dell\'Alba ha trovato il suo posto nella tua giornata.',
      12),
  _t('aur_13', 'Dieci meditazioni', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('meditazione', 10, inGiorniDiversi: true),
      'Dieci meditazioni in dieci giorni: il silenzio ha smesso di essere vuoto.',
      13),
  _t('aur_14', 'Venere torna indietro', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.venereRetrograda,
          conGesto: 'chakra'),
      'Hai guardato i tuoi centri con Venere retrograda: gli affetti tornano indietro per farsi rivedere.',
      14),
  _t('aur_15', 'Il giorno respirato', FamigliaDelTraguardo.giornata,
      const GestiNelloStessoGiorno(['soffio', 'meditazione', 'chakra']),
      'Soffio, meditazione e chakra nello stesso giorno: il corpo ha avuto tutta la tua attenzione.',
      15),
  _t('aur_16', 'Tre arti di Aura', FamigliaDelTraguardo.ampiezza,
      const GestiNelloStessoGiorno(['chakra', 'viso', 'archetipo']),
      'Chakra, Viso e Archetipo in un giorno: tre modi di guardarti senza specchio.',
      16),
  _t('aur_17', 'Cinque mattine di seguito', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('alba', 5),
      'Cinque mattine di seguito: cinque giorni cominciati dalla parte giusta.',
      17),
  _t('aur_18', 'Tutti i sette centri', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('chakra_diverso', 7),
      'Hai attraversato tutti e sette i centri: dalla radice alla corona, senza saltarne uno.',
      18),
  _t('aur_19', 'Giove torna indietro', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.gioveRetrogrado,
          conGesto: 'meditazione'),
      'Hai meditato con Giove retrogrado: la crescita che rientra è quella che mette radici.',
      19),
  _t('aur_20', 'Il volto che cambia', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('viso_confronto', 2, dopoGiorni: 30),
      'Hai confrontato due letture del tuo volto a un mese di distanza: qualcosa si era mosso.',
      20),
  _t('aur_21', 'Il giorno intero di Aura', FamigliaDelTraguardo.giornata,
      const GestiNelloStessoGiorno(['alba', 'soffio', 'meditazione', 'chakra']),
      'Alba, Soffio, meditazione e chakra: una giornata intera passata dalla parte del respiro.',
      21),
  _t('aur_22', 'Venere torna diretta', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.venereDiretta, conGesto: 'viso'),
      'Venere è tornata diretta e tu hai guardato il tuo volto: la bellezza riprende la sua strada.',
      22),
  _t('aur_23', 'Venti soffi', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('soffio', 20, inGiorniDiversi: true),
      'Venti Soffi in venti giorni diversi: il respiro è diventato una pratica, non un rimedio.',
      23),
  _t('aur_24', 'Il ritorno dopo una settimana', FamigliaDelTraguardo.ritorno,
      const RitornoDopoAssenza(7),
      'Sette giorni di assenza e sei tornato: il Loto non si chiude per un\'assenza.',
      24),
  _t('aur_25', 'Corpo e cielo', FamigliaDelTraguardo.ampiezza,
      const GestiNelloStessoGiorno(['chakra', 'oroscopo']),
      'Chakra e Oroscopo nello stesso giorno: il cielo fuori e il cielo dentro, guardati insieme.',
      25),
  _t('aur_26', 'Il transito sulla tua Luna', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.transitoSullaLuna,
          conGesto: 'soffio'),
      'Un transito è passato sulla tua Luna mentre respiravi: la parte più emotiva di te era in movimento.',
      26),
  _t('aur_27', 'Il tuo volto letto', FamigliaDelTraguardo.identita,
      const PezzoDellIdentita('viso'),
      'La Costellazione del tuo Viso è tracciata: il tuo volto è una mappa e adesso l\'hai vista.',
      27),
  _t('aur_28', 'Lo stesso centro che chiama', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('chakra_ripetuto', 3),
      'Lo stesso chakra è tornato tre volte: il corpo insiste dove c\'è qualcosa da sciogliere.',
      28),
  _t('aur_29', 'Aura ti riprende', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('ripresa_aura', 1),
      'Aura ha ripreso una cosa che le avevi detto: il respiro ha una memoria lunga.',
      29),
  _t('aur_30', 'Il transito su Venere', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.transitoSuVenere,
          conGesto: 'meditazione'),
      'Un transito è passato sulla tua Venere mentre meditavi: quello che ami era sotto una luce nuova.',
      30),
  _t('aur_31', 'Una settimana di mattine', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('alba', 7),
      'Sette mattine di seguito: una settimana intera cominciata col respiro.',
      31),
  _t('aur_32', 'Due giorni respirati', FamigliaDelTraguardo.giornata,
      const GestiCompiuti('giorno_respirato', 2, inGiorniDiversi: true),
      'Due giornate intere passate dalla parte del corpo: non è stato un caso isolato.',
      32),
  _t('aur_33', 'Trenta meditazioni', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('meditazione', 30, inGiorniDiversi: true),
      'Trenta meditazioni: il silenzio è diventato un posto dove sai tornare da solo.',
      33),
  _t('aur_34', 'Il primo petalo condiviso', FamigliaDelTraguardo.cerchio,
      const GestoDelCerchio('condivisione_petalo', 1),
      'Hai condiviso il tuo primo Petalo del Risveglio: quello che si apre non si tiene per sé.',
      34),
  _t('aur_35', 'La Luna nel segno opposto', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.lunaNelSegnoOpposto,
          conGesto: 'chakra'),
      'La Luna era nel segno opposto al tuo e tu hai ascoltato i tuoi centri: si impara di più da ciò che non ci somiglia.',
      35),
  _t('aur_36', 'Respiro, pietra e carta', FamigliaDelTraguardo.ampiezza,
      const GestiNelloStessoGiorno(['soffio', 'gettata', 'stesa']),
      'Soffio, rune e carte nello stesso giorno: hai chiesto ai tre Maestri con tre linguaggi.',
      36),
  _t('aur_37', 'L\'ora dell\'alba', FamigliaDelTraguardo.ritorno,
      const GestoNellOraGiusta('alba', 'alba', quanteVolte: 5),
      'Cinque volte hai compiuto il Rito dell\'Alba all\'alba vera: il sole ti ha trovato sveglio.',
      37),
  _t('aur_38', 'Il tema del corpo', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('tema_corpo', 3, dopoGiorni: 20),
      'Lo stesso tema del corpo è tornato tre volte in venti giorni: adesso ha un nome.',
      38),
  _t('aur_39', 'Tre petali condivisi', FamigliaDelTraguardo.cerchio,
      const GestoDelCerchio('condivisione_petalo', 3),
      'Tre Petali condivisi: il tuo Loto profuma anche fuori dal Cerchio.',
      39),
  _t('aur_40', 'Cinquanta soffi', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('soffio', 50, inGiorniDiversi: true),
      'Cinquanta Soffi in cinquanta giorni diversi: il respiro è la tua arte, non un esercizio.',
      40),
  _t('aur_41', 'Tre transiti insieme', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.treTransitiInsieme),
      'Tre transiti hanno toccato i tuoi punti nello stesso giorno, e tu eri qui: giornate così sono rare.',
      41),
  _t('aur_42', 'Sette giorni respirati', FamigliaDelTraguardo.giornata,
      const GestiCompiuti('giorno_respirato', 7, inGiorniDiversi: true),
      'Sette giornate intere dalla parte del corpo: una settimana senza dimenticarti di te.',
      42),
  _t('aur_43', 'Il tuo numero', FamigliaDelTraguardo.identita,
      const PezzoDellIdentita('numero_della_vita'),
      'Il tuo Numero della Vita è calcolato: una cifra sola che ti riguarda per sempre.',
      43),
  _t('aur_44', 'Il primo invitato di Aura', FamigliaDelTraguardo.cerchio,
      const GestoDelCerchio('invito', 3),
      'Tre persone sono entrate nel Cerchio grazie a te: nessuna di loro ti doveva niente.',
      44),
  _t('aur_45', 'Due settimane di mattine', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('alba', 14),
      'Quattordici mattine di seguito: due settimane cominciate tutte dal respiro.',
      45),
  _t('aur_46', 'Il ritorno dopo dieci giorni', FamigliaDelTraguardo.ritorno,
      const RitornoDopoAssenza(10),
      'Dieci giorni lontano e sei tornato: il Loto ti aspettava con tutti i petali che avevi aperto.',
      46),
  _t('aur_47', 'Il respiro che si allunga', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('respiro_confronto', 3, dopoGiorni: 45),
      'Il tuo respiro si è allungato in un mese e mezzo, e il Cerchio l\'ha misurato.',
      47),
  _t('aur_48', 'Sette petali condivisi', FamigliaDelTraguardo.cerchio,
      const GestoDelCerchio('condivisione_petalo', 7),
      'Sette Petali condivisi: hai fatto respirare anche qualcun altro.',
      48),
  _t('aur_49', 'Tutte le arti di Aura', FamigliaDelTraguardo.ampiezza,
      const GestiNelloStessoGiorno(
          ['soffio', 'meditazione', 'chakra', 'viso']),
      'Tutte le arti di Aura in un giorno solo: respiro, silenzio, centri e volto.',
      49),
  _t('aur_50', 'L\'ultimo quarto', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.ultimoQuarto,
          conGesto: 'meditazione'),
      'Hai meditato all\'ultimo quarto di Luna: la fase in cui si lascia andare quello che non serve più.',
      50),

  // LE CINQUE FIORITURE.
  _g('aur_g10', 'La Prima Fioritura', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('presenza_mattino', 7),
      'Sette mattine di presenza hanno aperto la Prima Fioritura: il Loto ha rotto la superficie.',
      10),
  _g('aur_g20', 'La Fioritura del Respiro', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('soffio', 15, inGiorniDiversi: true),
      'Quindici giorni di Soffio hanno aperto la Fioritura del Respiro: il corpo ha preso la parola.',
      20),
  _g('aur_g30', 'La Fioritura del Cielo', FamigliaDelTraguardo.cielo,
      const GestiCompiuti('finestra_del_cielo_corpo', 5),
      'Cinque finestre del cielo attraversate col corpo hanno aperto la Fioritura del Cielo.',
      30),
  _g('aur_g40', 'La Fioritura della Memoria', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('fatti_aura', 30, dopoGiorni: 30),
      'Trenta cose tue ricordate da Aura hanno aperto la Fioritura della Memoria: ti conosce dal respiro.',
      40),
  _g('aur_g50', 'Il Loto Aperto', FamigliaDelTraguardo.identita,
      const GestiCompiuti('petalo_aperto', 49),
      'Quarantanove Petali aperti: il Loto è intero, e nessun petalo si è aperto per caso.',
      50),
];
