import 'eventi_del_cielo.dart';
import 'traguardo.dart';

/// LA COSTELLAZIONE PERSONALE, il sentiero di Medora.
///
/// Le Stelle del Cammino sono i cinquanta traguardi piccoli, le Costellazioni
/// sono i cinque grandi. Il tono e' quello di Medora: il cielo che osserva, la
/// carta che si legge, il tempo che si dispone.
///
/// **Questo e' un file di DATI.** Nessuna logica vive qui: le condizioni sono
/// oggetti tipizzati definiti in `traguardo.dart`, e cosi' le prove possono
/// contare le famiglie, misurare quanti traguardi non si chiudono in giornata,
/// sommare gli Eos e accorgersi se due traguardi dicono la stessa cosa.
///
/// I GESTI DI QUESTO SENTIERO: `stesa` (una stesa di tarocchi), `oroscopo`,
/// `sinastria`, `oracolo` (il dono del giorno di Medora), `consulto_medora`,
/// `carta_natale`. Piu' i gesti comuni a tutti: `alba`, `soffio`, `tramonto`,
/// `presenza`.
Traguardo _t(
  String id,
  String nome,
  FamigliaDelTraguardo famiglia,
  CondizioneDelTraguardo condizione,
  String frase,
  int posizione,
) =>
    Traguardo(
      id: id,
      nome: nome,
      famiglia: famiglia,
      condizione: condizione,
      frase: frase,
      posizione: posizione,
    );

/// Lo stesso, per i cinque GRANDI: il dato dice che sono grandi, cosi' la
/// posizione non deve indovinarlo.
Traguardo _g(
  String id,
  String nome,
  FamigliaDelTraguardo famiglia,
  CondizioneDelTraguardo condizione,
  String frase,
  int posizione,
) =>
    Traguardo(
      id: id,
      nome: nome,
      famiglia: famiglia,
      condizione: condizione,
      frase: frase,
      posizione: posizione,
      eGrande: true,
    );

final List<Traguardo> sentieroDellaCostellazione = [
  // I TRE AGGANCIO, uguali sui tre sentieri per decisione: sono l'identita'
  // che si completa, e completarla vale su ogni cammino.
  _t('med_1', 'La tua carta è nata', FamigliaDelTraguardo.identita,
      const PezzoDellIdentita('carta_natale'),
      'La tua carta natale è calcolata: da qui in poi il cielo parla di te e non di tutti.',
      1),
  _t('med_2', 'Il tuo Angelo ha un nome', FamigliaDelTraguardo.identita,
      const PezzoDellIdentita('angelo_custode'),
      'Il tuo Angelo Custode ha un nome e adesso lo sai: non era un angelo qualunque.',
      2),
  _t('med_3', 'Il tuo Animale ti ha trovato', FamigliaDelTraguardo.identita,
      const PezzoDellIdentita('animale_guida'),
      'Il tuo Animale Guida è emerso dalla nebbia: da oggi cammina con te.',
      3),
  _t('med_4', 'Il primo giorno intero', FamigliaDelTraguardo.giornata,
      const GestiNelloStessoGiorno(['alba', 'oracolo']),
      'Alba e Oracolo nello stesso giorno: hai aperto la giornata e l\'hai fatta parlare.',
      4),
  _t('med_5', 'Tre stese', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('stesa', 3),
      'Tre stese di tarocchi: le carte cominciano a riconoscere la tua mano.',
      5),
  _t('med_6', 'Sotto la Luna piena', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.lunaPiena, conGesto: 'stesa'),
      'Hai steso le carte sotto la Luna piena: il cielo era al colmo e tu eri qui.',
      6),
  _t('med_7', 'Due albe di seguito', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('oracolo', 2),
      'Due giorni di seguito con l\'Oracolo: la seconda volta è quella che conta.',
      7),
  _t('med_8', 'Due arti in un giorno', FamigliaDelTraguardo.ampiezza,
      const GestiNelloStessoGiorno(['stesa', 'oroscopo']),
      'Carte e Oroscopo nello stesso giorno: due sguardi sullo stesso cielo.',
      8),
  _t('med_9', 'Cinque stese in giorni diversi', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('stesa', 5, inGiorniDiversi: true),
      'Cinque stese in cinque giorni diversi: non hai cercato una risposta, hai preso un\'abitudine.',
      9),
  _t('med_10', 'Il tuo segno sotto la Luna', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.lunaNelTuoSegno,
          conGesto: 'oroscopo'),
      'La Luna era nel tuo segno e tu hai letto il tuo cielo: coincidenza cercata, non capitata.',
      10),
  _t('med_11', 'Il Cerchio ricorda', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('momenti', 10),
      'Dieci tuoi momenti custoditi: il Cerchio ha cominciato a ricordarti.',
      11),
  _t('med_12', 'Tre giorni di seguito', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('oracolo', 3),
      'Tre giorni di seguito: il terzo è quello che trasforma una prova in un rito.',
      12),
  _t('med_13', 'Dieci stese', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('stesa', 10, inGiorniDiversi: true),
      'Dieci stese in dieci giorni: le carte non ti sorprendono più, ti rispondono.',
      13),
  _t('med_14', 'Mercurio torna indietro', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.mercurioRetrogrado,
          conGesto: 'oroscopo'),
      'Hai letto il tuo cielo mentre Mercurio tornava indietro: si guarda meglio quando tutto rallenta.',
      14),
  _t('med_15', 'Il giorno chiuso', FamigliaDelTraguardo.giornata,
      const GestiNelloStessoGiorno(['oracolo', 'tramonto']),
      'Oracolo al mattino e runa al tramonto: hai chiuso il cerchio del giorno.',
      15),
  _t('med_16', 'Tre arti diverse', FamigliaDelTraguardo.ampiezza,
      const GestiNelloStessoGiorno(['stesa', 'oroscopo', 'sinastria']),
      'Carte, Oroscopo e Sinastria in un giorno solo: hai guardato il cielo da tre finestre.',
      16),
  _t('med_17', 'Cinque giorni di seguito', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('oracolo', 5),
      'Cinque giorni di seguito: adesso il Cerchio fa parte della tua settimana.',
      17),
  _t('med_18', 'Tutte le chiavi della stesa', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('stesa_tipo_diverso', 4),
      'Hai provato tutte le chiavi di lettura della stesa: nessuna carta ha più un solo modo di parlare.',
      18),
  _t('med_19', 'Il Sole nel tuo segno', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.soleNelTuoSegno,
          conGesto: 'carta_natale'),
      'Hai riaperto la tua carta mentre il Sole attraversava il tuo segno: il mese che è tuo.',
      19),
  _t('med_20', 'Una domanda ripresa', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('rilettura', 1, dopoGiorni: 30),
      'Hai riletto un consulto di un mese fa: il tuo passato ti ha risposto una seconda volta.',
      20),
  _t('med_21', 'Il giorno pieno', FamigliaDelTraguardo.giornata,
      const GestiNelloStessoGiorno(['alba', 'soffio', 'oracolo', 'tramonto']),
      'Tutti e quattro i doni del giorno, nello stesso giorno: il cerchio è intero.',
      21),
  _t('med_22', 'Mercurio torna diretto', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.mercurioDiretto,
          conGesto: 'stesa'),
      'Mercurio è tornato diretto e tu hai steso le carte: il pensiero riprende la sua strada.',
      22),
  _t('med_23', 'Venti stese', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('stesa', 20, inGiorniDiversi: true),
      'Venti stese in venti giorni: questa non è curiosità, è pratica.',
      23),
  _t('med_24', 'Il ritorno dopo tre giorni', FamigliaDelTraguardo.ritorno,
      const RitornoDopoAssenza(3),
      'Sei tornato dopo tre giorni di silenzio: il Cerchio ti aspettava nel punto in cui eri rimasto.',
      24),
  _t('med_25', 'Lo stesso tema, tre Maestri', FamigliaDelTraguardo.ampiezza,
      const GestiNelloStessoGiorno(
          ['consulto_medora', 'consulto_caligo', 'consulto_aura']),
      'Hai chiesto lo stesso tema ai tre Maestri: tre letture, un cielo solo.',
      25),
  _t('med_26', 'Il transito sul tuo Sole', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.transitoSulSole,
          conGesto: 'oroscopo'),
      'Un pianeta è passato sul tuo Sole e tu te ne sei accorto: pochi lo fanno.',
      26),
  _t('med_27', 'Il Passaporto pieno', FamigliaDelTraguardo.identita,
      const PezzoDellIdentita('passaporto'),
      'Il tuo Cosmic Passport è completo: nome, cielo, numero, tutto al suo posto.',
      27),
  _t('med_28', 'La carta che torna', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('carta_ripetuta', 3),
      'La stessa carta è uscita tre volte: quando insiste, non è più un caso.',
      28),
  _t('med_29', 'Il Maestro ti riprende', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('ripresa', 1),
      'Medora ha ripreso una cosa che le avevi detto: non era una risposta qualunque, era la tua.',
      29),
  _t('med_30', 'L\'Ascendente toccato', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.transitoSullAscendente,
          conGesto: 'carta_natale'),
      'Un transito è passato sul tuo Ascendente mentre lo guardavi: il tuo punto più personale, in movimento.',
      30),
  _t('med_31', 'Una settimana intera', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('oracolo', 7),
      'Sette giorni di seguito senza saltarne uno: la settimana è chiusa.',
      31),
  _t('med_32', 'Due giorni interi', FamigliaDelTraguardo.giornata,
      const GestiCompiuti('giorno_intero', 2, inGiorniDiversi: true),
      'Due giornate chiuse per intero: non è stata una volta sola.',
      32),
  _t('med_33', 'Trenta stese', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('stesa', 30, inGiorniDiversi: true),
      'Trenta stese: le carte hanno smesso di essere uno strumento e sono diventate una lingua.',
      33),
  _t('med_34', 'La prima stella condivisa', FamigliaDelTraguardo.cerchio,
      const GestoDelCerchio('condivisione_stella', 1),
      'Hai condiviso la tua prima Stella del Cammino: il cielo si guarda meglio in due.',
      34),
  _t('med_35', 'L\'equinozio', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.equinozio),
      'Eri qui nel giorno dell\'equinozio, quando la luce e il buio si guardano alla pari.',
      35),
  _t('med_36', 'I tre domini', FamigliaDelTraguardo.ampiezza,
      const GestiNelloStessoGiorno(
          ['dominio_medora', 'dominio_caligo', 'dominio_aura']),
      'Hai visitato i tre domini in un giorno: conosci tutto il Cerchio, non solo la tua stanza.',
      36),
  _t('med_37', 'L\'ora dell\'Oracolo', FamigliaDelTraguardo.ritorno,
      const GestoNellOraGiusta('oracolo', 'alba', quanteVolte: 3),
      'Tre volte hai chiesto l\'Oracolo all\'alba vera: l\'ora giusta non è un dettaglio.',
      37),
  _t('med_38', 'Un tema che torna', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('tema', 3, dopoGiorni: 14),
      'Lo stesso tema è tornato tre volte in due settimane: il Cerchio l\'ha visto prima di te.',
      38),
  _t('med_39', 'Tre stelle condivise', FamigliaDelTraguardo.cerchio,
      const GestoDelCerchio('condivisione_stella', 3),
      'Tre Stelle condivise: qualcuno guarda il tuo cielo insieme a te.',
      39),
  _t('med_40', 'Cinquanta stese', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('stesa', 50, inGiorniDiversi: true),
      'Cinquanta stese in cinquanta giorni diversi: pochissimi arrivano qui.',
      40),
  _t('med_41', 'La Luna piena nel tuo segno', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.lunaPienaNelTuoSegno),
      'La Luna piena è caduta nel tuo segno e tu c\'eri: capita una volta l\'anno.',
      41),
  _t('med_42', 'Sette giorni interi', FamigliaDelTraguardo.giornata,
      const GestiCompiuti('giorno_intero', 7, inGiorniDiversi: true),
      'Sette giornate chiuse per intero: una settimana senza lasciare niente a metà.',
      42),
  _t('med_43', 'L\'ora esatta', FamigliaDelTraguardo.identita,
      const PezzoDellIdentita('ora_di_nascita'),
      'Hai dato l\'ora esatta della tua nascita: Ascendente e Case escono dal velo.',
      43),
  _t('med_44', 'Il primo invito', FamigliaDelTraguardo.cerchio,
      const GestoDelCerchio('invito', 1),
      'Hai portato qualcuno nel Cerchio: il tuo primo invito, nato senza nessun obbligo.',
      44),
  _t('med_45', 'Due settimane di seguito', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('oracolo', 14),
      'Quattordici giorni di seguito: due settimane intere senza un buco.',
      45),
  _t('med_46', 'Il ritorno dopo due settimane', FamigliaDelTraguardo.ritorno,
      const RitornoDopoAssenza(14),
      'Sei tornato dopo due settimane: il Cerchio non ti ha cancellato, ti ha tenuto il posto.',
      46),
  _t('med_47', 'Cento momenti', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('momenti', 100, dopoGiorni: 30),
      'Cento tuoi momenti custoditi in un mese: adesso il Cerchio ti conosce davvero.',
      47),
  _t('med_48', 'Sette stelle condivise', FamigliaDelTraguardo.cerchio,
      const GestoDelCerchio('condivisione_stella', 7),
      'Sette Stelle condivise: il tuo cammino illumina anche fuori.',
      48),
  _t('med_49', 'Tutte le arti di Medora', FamigliaDelTraguardo.ampiezza,
      const GestiNelloStessoGiorno(
          ['stesa', 'oroscopo', 'sinastria', 'carta_natale']),
      'Tutte le arti di Medora in un giorno solo: il suo dominio non ha più angoli bui.',
      49),
  _t('med_50', 'Il tuo ritorno solare', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.ritornoSolare),
      'Il Sole è tornato dove stava quando sei nato: tu eri qui a vederlo mentre il tuo anno ricomincia.',
      50),

  // LE CINQUE COSTELLAZIONI, i grandi traguardi. Sempre visibili in anticipo,
  // modello tessera punti: si sa dove si sta andando fin dal primo giorno.
  _g('med_g10', 'La Costellazione del Ritorno', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('presenza', 7),
      'Sette giorni di presenza hanno acceso la Costellazione del Ritorno: la prima figura del tuo cielo.',
      10),
  _g('med_g20', 'La Costellazione della Lettura', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('stesa', 15, inGiorniDiversi: true),
      'Quindici giorni di carte hanno acceso la Costellazione della Lettura: leggi, non consulti più.',
      20),
  _g('med_g30', 'La Costellazione del Cielo Vero',
      FamigliaDelTraguardo.cielo,
      const GestiCompiuti('finestra_del_cielo', 5),
      'Cinque finestre del cielo colte al volo: la Costellazione del Cielo Vero è tua, di quelle che non si possono affrettare.',
      30),
  _g('med_g40', 'La Costellazione della Memoria', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('fatti', 30, dopoGiorni: 30),
      'Trenta fatti tuoi ricordati in un mese: la Costellazione della Memoria brilla di cose che hai detto.',
      40),
  _g('med_g50', 'La Costellazione Compiuta', FamigliaDelTraguardo.identita,
      const GestiCompiuti('stella_accesa', 49),
      'Quarantanove Stelle accese: la Costellazione Compiuta è il tuo cielo intero, disegnato da te.',
      50),
];
