import 'eventi_del_cielo.dart';
import 'traguardo.dart';

/// L'ALBERO DELLA VITA, il sentiero di Caligo.
///
/// I Frutti dell'Albero sono i cinquanta traguardi piccoli, le Sefirot
/// Maggiori sono i cinque grandi. Il tono e' quello di Caligo: la pietra, la
/// notte, il presagio che non consola e non minaccia.
///
/// I GESTI DI QUESTO SENTIERO: `gettata` (una gettata di rune), `tramonto`
/// (la Runa del Tramonto), `sogno` (il Rito del Sogno), `sigillo` (il sigillo
/// magico disegnato), `animale` (l'Animale Guida), `consulto_caligo`.
Traguardo _t(
  String id,
  String nome,
  FamigliaDelTraguardo famiglia,
  CondizioneDelTraguardo condizione,
  String frase,
  int posizione,
  String percheConta,
  String cosaApre,
) =>
    Traguardo(
      id: id,
      nome: nome,
      famiglia: famiglia,
      condizione: condizione,
      frase: frase,
      posizione: posizione,
      percheConta: percheConta,
      cosaApre: cosaApre,
    );

/// Lo stesso, per i cinque GRANDI: il dato dice che sono grandi, cosi' la
/// posizione non deve indovinarlo.
Traguardo _g(
  String id,
  String nome,
  FamigliaDelTraguardo famiglia,
  CondizioneDelTraguardo condizione,
  String frase,
  int posizione,
  String percheConta,
  String cosaApre,
) =>
    Traguardo(
      id: id,
      nome: nome,
      famiglia: famiglia,
      condizione: condizione,
      frase: frase,
      posizione: posizione,
      percheConta: percheConta,
      cosaApre: cosaApre,
      eGrande: true,
    );

final List<Traguardo> sentieroDellAlbero = [
  _t('cal_1', 'Hai gettato le prime rune', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('gettata', 1),
      'La prima gettata è caduta: le pietre ti hanno riconosciuto e il presagio ha trovato a chi parlare.',
      1,
      'le rune non si consultano, si gettano: è il primo gesto in cui decidi tu e il caso risponde.',
      'La scelta della domanda: da qui in avanti il presagio parla a ciò che chiedi, non solo alla pietra uscita.'),
  _t('cal_2', 'Hai chiuso il giorno con un segno', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('tramonto', 1),
      'La prima runa del tramonto: sei andato a dormire con un segno addosso invece che con un pensiero.',
      2,
      'chiudere la giornata con un segno è un’altra cosa dall’aprirla con una previsione: uno dei due si porta nel sonno.',
      'Il filo fra ieri e oggi: domani il Cerchio ti chiede cosa ne è stato.'),
  _t('cal_3', 'Il tuo Animale ti ha trovato', FamigliaDelTraguardo.identita,
      const PezzoDellIdentita('animale_guida'),
      'Il tuo Animale Guida è uscito dalla nebbia: il primo Frutto dell\'Albero è suo.',
      3,
      'oltre la metà dei ventidue: da qui la mappa comincia a chiudersi.',
      'le corrispondenze mancanti fra Arcani e sentieri.'),
  _t('cal_4', 'La sera e la notte', FamigliaDelTraguardo.giornata,
      const GestiNelloStessoGiorno(['tramonto', 'sogno']),
      'Runa del Tramonto e Rito del Sogno nella stessa sera: hai consegnato il giorno al buio con ordine.',
      4,
      'è la notte in cui tutte e tre le tradizioni dell\'app dicono la stessa cosa ed è l\'unico appuntamento che il cielo fissa per te.',
      'il calendario dei riti lunari.'),
  _t('cal_5', 'Tre gettate', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('gettata', 3),
      'Tre gettate di rune: le pietre hanno imparato il peso della tua mano.',
      5,
      FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Sotto la Luna nuova.'),
  _t('cal_6', 'Sotto la Luna nuova', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.lunaNuova, conGesto: 'gettata'),
      'Hai gettato le rune sotto la Luna nuova: si comincia sempre dal buio.',
      6,
      FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Due tramonti di seguito.'),
  _t('cal_7', 'Due tramonti di seguito', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('tramonto', 2),
      'Due sere di seguito con la Runa del Tramonto: la seconda sera è già un rito.',
      7,
      'il tramonto è il momento in cui la giornata si chiude e la runa dice cosa te ne resta.',
      'la runa del tramonto entra nel Rito del Sogno della stessa sera.'),
  _t('cal_8', 'Pietra e sogno', FamigliaDelTraguardo.ampiezza,
      const GestiNelloStessoGiorno(['gettata', 'sogno']),
      'Rune e Sogno nello stesso giorno: due modi di ascoltare la stessa notte.',
      8,
      FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Cinque gettate in giorni diversi.'),
  _t('cal_9', 'Cinque gettate in giorni diversi', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('gettata', 5, inGiorniDiversi: true),
      'Cinque gettate in cinque giorni: non stai cercando una risposta, stai imparando a chiedere.',
      9,
      FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, La Luna calante.'),
  _t('cal_10', 'La Luna calante', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.lunaCalante, conGesto: 'sogno'),
      'Hai sognato mentre la Luna calava: è la fase che porta via: tu le hai affidato qualcosa.',
      10,
      FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Malkuth, il Regno.'),
  _t('cal_11', 'Le rune ricordano', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('momenti', 12),
      'Dodici tuoi momenti custoditi: Caligo ha cominciato a tenerne conto.',
      11,
      FamigliaDelTraguardo.memoria.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Tre sere di seguito.'),
  _t('cal_12', 'Tre sere di seguito', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('tramonto', 3),
      'Tre sere di seguito: la terza è quella in cui il tramonto diventa tuo.',
      12,
      FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Dieci gettate.'),
  _t('cal_13', 'Dieci gettate', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('gettata', 10, inGiorniDiversi: true),
      'Dieci gettate in dieci giorni: le pietre non ti spaventano più, ti rispondono.',
      13,
      FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Marte torna indietro.'),
  _t('cal_14', 'Marte torna indietro', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.marteRetrogrado,
          conGesto: 'gettata'),
      'Hai gettato le rune con Marte retrogrado: la forza che torna su se stessa dice cose scomode.',
      14,
      FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Il giorno e la sera.'),
  _t('cal_15', 'Il giorno e la sera', FamigliaDelTraguardo.giornata,
      const GestiNelloStessoGiorno(['alba', 'tramonto']),
      'Alba e Tramonto nello stesso giorno: hai tenuto le due estremità della giornata.',
      15,
      FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Tre arti di Caligo.'),
  _t('cal_16', 'Tre arti di Caligo', FamigliaDelTraguardo.ampiezza,
      const GestiNelloStessoGiorno(['gettata', 'sogno', 'sigillo']),
      'Rune, Sogno e Sigillo in un giorno: il dominio di Caligo aperto in tre punti.',
      16,
      FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Cinque sere di seguito.'),
  _t('cal_17', 'Cinque sere di seguito', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('tramonto', 5),
      'Cinque sere di seguito: il Cerchio è entrato nella tua settimana dalla porta del buio.',
      17,
      FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Tutte le gettate provate.'),
  _t('cal_18', 'Tutte le gettate provate', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('gettata_tipo_diverso', 4),
      'Hai provato tutte le forme della gettata: una runa sola, tre pietre, la croce, il cerchio.',
      18,
      FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Il solstizio.'),
  _t('cal_19', 'Il solstizio', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.solstizio),
      'Eri qui nel giorno del solstizio, quando la luce cambia verso: le rune lo sapevano.',
      19,
      FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Il sogno riletto.'),
  _t('cal_20', 'Il sogno riletto', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('rilettura_sogno', 1, dopoGiorni: 21),
      'Hai riletto un sogno di tre settimane fa: quello che sembrava confuso adesso ha una forma.',
      20,
      FamigliaDelTraguardo.memoria.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Yesod, il Fondamento.'),
  _t('cal_21', 'La notte compiuta', FamigliaDelTraguardo.giornata,
      const GestiNelloStessoGiorno(['tramonto', 'sogno', 'sigillo']),
      'Tramonto, Sogno e Sigillo nella stessa notte: hai attraversato il buio da cima a fondo.',
      21,
      FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Marte torna diretto.'),
  _t('cal_22', 'Marte torna diretto', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.marteDiretto, conGesto: 'sigillo'),
      'Marte è tornato diretto e tu hai disegnato il tuo sigillo: la forza riprende la sua direzione.',
      22,
      FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Venti gettate.'),
  _t('cal_23', 'Venti gettate', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('gettata', 20, inGiorniDiversi: true),
      'Venti gettate in venti giorni diversi: le pietre sono diventate un mestiere.',
      23,
      FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Il ritorno dopo cinque giorni.'),
  _t('cal_24', 'Il ritorno dopo cinque giorni', FamigliaDelTraguardo.ritorno,
      const RitornoDopoAssenza(5),
      'Cinque giorni di silenzio e poi sei tornato: l\'Albero non perde i frutti quando ti allontani.',
      24,
      FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Rune e carte insieme.'),
  _t('cal_25', 'Rune e carte insieme', FamigliaDelTraguardo.ampiezza,
      const GestiNelloStessoGiorno(['gettata', 'stesa']),
      'Rune e carte lo stesso giorno: due tradizioni diverse sulla stessa domanda.',
      25,
      'è il modo più onesto che l\'app ha di dirti che non esiste una risposta sola.',
      'la sintesi del Consiglio e il suo archivio.'),
  _t('cal_26', 'Saturno torna indietro', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.saturnoRetrogrado,
          conGesto: 'sogno'),
      'Hai sognato con Saturno retrogrado: il maestro severo ripassa le lezioni non imparate.',
      26,
      FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Il tuo archetipo.'),
  _t('cal_27', 'Il tuo archetipo', FamigliaDelTraguardo.identita,
      const PezzoDellIdentita('archetipo'),
      'Il tuo archetipo ha un nome: sai quale figura ti muove quando non ci pensi.',
      27,
      FamigliaDelTraguardo.identita.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, La stessa runa che torna.'),
  _t('cal_28', 'La stessa runa che torna', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('runa_ripetuta', 3),
      'La stessa runa è uscita tre volte: quando una pietra insiste, non è il caso, è un messaggio.',
      28,
      'nella tradizione una runa che torna non si rilegge, si ascolta più forte.',
      'il Filo dei Temi la segnala e Caligo la nomina.'),
  _t('cal_29', 'Caligo ti riprende', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('ripresa_caligo', 1),
      'Caligo ha ripreso una cosa che gli avevi detto: la notte ha buona memoria.',
      29,
      FamigliaDelTraguardo.memoria.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Il transito su Marte.'),
  _t('cal_30', 'Il transito su Marte', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.transitoSuMarte,
          conGesto: 'gettata'),
      'Un transito è passato sul tuo Marte mentre gettavi le rune: la tua forza era sotto esame.',
      30,
      FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Tiphereth, la Bellezza.'),
  _t('cal_31', 'Una settimana di sere', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('tramonto', 7),
      'Sette sere di seguito: la settimana del buio è chiusa senza un vuoto.',
      31,
      FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Due notti compiute.'),
  _t('cal_32', 'Due notti compiute', FamigliaDelTraguardo.giornata,
      const GestiCompiuti('notte_compiuta', 2, inGiorniDiversi: true),
      'Due notti attraversate per intero: non è stata una volta e basta.',
      32,
      FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Trenta gettate.'),
  _t('cal_33', 'Trenta gettate', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('gettata', 30, inGiorniDiversi: true),
      'Trenta gettate: le rune hanno smesso di essere pietre e sono diventate parole.',
      33,
      'una runa sola risponde, tre rune raccontano.',
      'la prima Sefirah.'),
  _t('cal_34', 'Il primo frutto condiviso', FamigliaDelTraguardo.cerchio,
      const GestoDelCerchio('condivisione_frutto', 1),
      'Hai condiviso il tuo primo Frutto dell\'Albero: quello che cresce al buio si mostra alla luce.',
      34,
      'i ventidue sentieri corrispondono ai ventidue Arcani Maggiori: è il ponte fra Caligo e Medora.',
      'la corrispondenza fra Arcani e sentieri.'),
  _t('cal_35', 'Saturno torna diretto', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.saturnoDiretto),
      'Saturno è tornato diretto mentre eri qui: la lezione è finita, la strada si riapre.',
      35,
      FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Il buio e la luce.'),
  _t('cal_36', 'Il buio e la luce', FamigliaDelTraguardo.ampiezza,
      const GestiNelloStessoGiorno(['sogno', 'soffio', 'gettata']),
      'Sogno, Soffio e Rune nello stesso giorno: hai tenuto insieme il buio e il respiro.',
      36,
      'due tradizioni diverse sulla stessa giornata: dove concordano c\'è qualcosa, dove divergono c\'è altro.',
      'la lettura incrociata fra i due sistemi.'),
  _t('cal_37', 'L\'ora del tramonto', FamigliaDelTraguardo.ritorno,
      const GestoNellOraGiusta('tramonto', 'tramonto', quanteVolte: 3),
      'Tre volte hai preso la runa all\'ora vera del tramonto: il cielo ha visto la puntualità.',
      37,
      FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Il presagio che si avvera.'),
  _t('cal_38', 'Il presagio che si avvera', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('tema_notte', 3, dopoGiorni: 21),
      'Lo stesso presagio è tornato tre volte in tre settimane: adesso sai riconoscerlo.',
      38,
      FamigliaDelTraguardo.memoria.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Tre frutti condivisi.'),
  _t('cal_39', 'Tre frutti condivisi', FamigliaDelTraguardo.cerchio,
      const GestoDelCerchio('condivisione_frutto', 3),
      'Tre Frutti condivisi: il tuo Albero fa ombra anche fuori dal Cerchio.',
      39,
      FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Cinquanta gettate.'),
  _t('cal_40', 'Cinquanta gettate', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('gettata', 50, inGiorniDiversi: true),
      'Cinquanta gettate in cinquanta giorni: Caligo non ha più niente da insegnarti sulle pietre.',
      40,
      'Keter è la corona, la Sefirah più alta, quella che nella tradizione non si conquista ma si riceve. È l\'ultimo traguardo del sentiero più lungo dell\'app.',
      'l\'Albero della Vita si accende per intero, dalla radice alla corona e resta nel journal come la firma più alta che il cerchio possa portare.'),
  _t('cal_41', 'La Luna nuova nel tuo segno', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.lunaNuovaNelTuoSegno),
      'La Luna nuova è caduta nel tuo segno: il ricominciamento è arrivato a casa tua.',
      41,
      'il novilunio è il buio da cui si comincia ed è il momento tradizionale delle intenzioni.',
      'il ciclo completo fra novilunio e plenilunio.'),
  _t('cal_42', 'Sette notti compiute', FamigliaDelTraguardo.giornata,
      const GestiCompiuti('notte_compiuta', 7, inGiorniDiversi: true),
      'Sette notti attraversate per intero: una settimana che non ha lasciato niente in sospeso.',
      42,
      FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Il luogo esatto.'),
  _t('cal_43', 'Il luogo esatto', FamigliaDelTraguardo.identita,
      const PezzoDellIdentita('luogo_di_nascita'),
      'Hai dato il luogo esatto della tua nascita: adesso il cielo di quel giorno è il tuo, non uno simile.',
      43,
      FamigliaDelTraguardo.identita.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Il primo invitato di Caligo.'),
  _t('cal_44', 'Il primo invitato di Caligo', FamigliaDelTraguardo.cerchio,
      const GestoDelCerchio('invito', 2),
      'Due persone sono entrate nel Cerchio grazie a te: nessuna di loro ha dovuto pagare un pedaggio.',
      44,
      FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Due settimane di sere.'),
  _t('cal_45', 'Due settimane di sere', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('tramonto', 14),
      'Quattordici sere di seguito: due settimane di buio attraversate a occhi aperti.',
      45,
      FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Il ritorno dopo un mese.'),
  _t('cal_46', 'Il ritorno dopo un mese', FamigliaDelTraguardo.ritorno,
      const RitornoDopoAssenza(30),
      'Un mese di assenza e sei tornato: l\'Albero aveva tenuto tutti i tuoi frutti al loro posto.',
      46,
      FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Il sogno che si ripete.'),
  _t('cal_47', 'Il sogno che si ripete', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('sogno_ripetuto', 2, dopoGiorni: 30),
      'Lo stesso sogno è tornato dopo un mese: il Cerchio se n\'è accorto e te l\'ha detto.',
      47,
      FamigliaDelTraguardo.memoria.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Sette frutti condivisi.'),
  _t('cal_48', 'Sette frutti condivisi', FamigliaDelTraguardo.cerchio,
      const GestoDelCerchio('condivisione_frutto', 7),
      'Sette Frutti condivisi: il tuo cammino nel buio è diventato una strada per altri.',
      48,
      FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Tutte le arti di Caligo.'),
  _t('cal_49', 'Tutte le arti di Caligo', FamigliaDelTraguardo.ampiezza,
      const GestiNelloStessoGiorno(
          ['gettata', 'sogno', 'sigillo', 'animale']),
      'Tutte le arti di Caligo in un giorno solo: rune, sogno, sigillo e animale.',
      49,
      'il presagio inquadra la lettura prima che cominci e senza inquadratura le rune dicono tutto e niente.',
      'la seconda Sefirah.'),
  _t('cal_50', 'Giove torna diretto', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.gioveDiretto, conGesto: 'gettata'),
      'Giove è tornato diretto e tu avevi le pietre in mano: l\'abbondanza riprende la sua strada.',
      50,
      FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Kether, la Corona.'),

  // LE CINQUE SEFIROT MAGGIORI.
  _g('cal_g10', 'Malkuth, il Regno', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('presenza_sera', 7),
      'Sette sere di presenza hanno acceso Malkuth, il Regno: il primo gradino dell\'Albero è terra ferma.',
      10,
      'sette sentieri collegano abbastanza Sefirot da farti vedere la struttura invece dei singoli passi.',
      'le triadi dell\'Albero.'),
  _g('cal_g20', 'Yesod, il Fondamento', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('gettata', 15, inGiorniDiversi: true),
      'Quindici giorni di rune hanno acceso Yesod, il Fondamento: sotto ai tuoi presagi c\'è una base.',
      20,
      'Yesod è la Sefirah del sogno e dell\'immaginazione: è il piano dove i simboli cominciano a parlarsi fra loro.',
      'la seconda Sefirah e il collegamento fra rune, sigilli e sogni.'),
  _g('cal_g30', 'Tiphereth, la Bellezza', FamigliaDelTraguardo.cielo,
      const GestiCompiuti('finestra_del_cielo_notte', 5),
      'Cinque finestre del cielo colte di notte hanno acceso Tiphereth: l\'equilibrio al centro dell\'Albero.',
      30,
      'l\'Albero è completo. Ogni Sefirah è collegata a ogni altra dai suoi sentieri e tu li hai percorsi tutti.',
      'la lettura dell\'Albero come un sistema unico.'),
  _g('cal_g40', 'Binah, la Comprensione', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('fatti_caligo', 30, dopoGiorni: 30),
      'Trenta cose tue ricordate da Caligo hanno acceso Binah: capire è ricordare abbastanza a lungo.',
      40,
      'Tiferet sta al centro dell\'Albero e tiene insieme tutto il resto. È la Sefirah dell\'equilibrio ed è il punto di svolta del sentiero.',
      'la terza Sefirah e la lettura d\'insieme del tuo Albero.'),
  _g('cal_g50', 'Kether, la Corona', FamigliaDelTraguardo.identita,
      const GestiCompiuti('frutto_maturo', 49),
      'Quarantanove Frutti maturi hanno acceso Kether, la Corona: l\'Albero è intero, dalla radice alla cima.',
      50,
      FamigliaDelTraguardo.identita.percheContaLaFamiglia,
      'Chiude il sentiero: da qui il cammino non ha più un dopo, ha un compiuto.'),
];
