// GENERATO DA tool/genera_sentieri_dal_corpus.py: NON SI SCRIVE
// A MANO. Ordine AR voce 02.
//
// La fonte e' docs/corpus/Traguardi_165_Revisione_C.json, e il
// dato comanda: nomi, condizioni, fasce, Eos e porte vengono da
// li' verbatim. Per cambiare un traguardo si cambia il corpus e
// si rigenera, mai il contrario.

import 'eventi_del_cielo.dart';
import 'traguardo.dart';

final List<Traguardo> sentieroDellAlbero = [
  Traguardo(
    id: 'cal_1',
    nome: 'Hai gettato le prime rune',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('gettata', 1),
    frase: 'La prima gettata di rune.',
    posizione: 1,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'L\'Estrazione delle Rune',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_2',
    nome: 'Il segno del tramonto',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('tramonto', 1),
    frase: 'La prima Runa del Tramonto.',
    posizione: 2,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'I Doni della sera',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_3',
    nome: 'Il tuo Animale ti ha trovato',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('animale_guida', 1),
    frase: 'Incontri per la prima volta il tuo Animale Guida.',
    posizione: 3,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'L\'Animale Guida',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_4',
    nome: 'Il primo sogno',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('sogno', 1),
    frase: 'Il primo Sigillo del Sogno compiuto.',
    posizione: 4,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Il Sigillo del Sogno',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_5',
    nome: 'Il primo sigillo',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('sigillo', 1),
    frase: 'Il primo Sigillo dell\'Intenzione tracciato.',
    posizione: 5,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'Il Sigillo dell\'Intenzione',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_6',
    nome: 'Il Sigillo del Cerchio',
    famiglia: FamigliaDelTraguardo.identita,
    condizione: const PezzoDellIdentita('sigillo_del_cerchio'),
    frase: 'Scopri nel Passaporto il Sigillo che il Cerchio ha inciso per te.',
    posizione: 6,
    percheConta: FamigliaDelTraguardo.identita.percheContaLaFamiglia,
    cosaApre: 'Il Cosmic Passport',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_7',
    nome: 'Pietra e sogno',
    famiglia: FamigliaDelTraguardo.giornata,
    condizione: const GestiNelloStessoGiorno(['gettata', 'sogno']),
    frase: 'Una gettata e un Sigillo del Sogno nello stesso giorno.',
    posizione: 7,
    percheConta: FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_8',
    nome: 'La Luna che cala',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.lunaCalante, conGesto: 'sogno'),
    frase: 'Un Sigillo del Sogno mentre la Luna sta calando.',
    posizione: 8,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: 'Il cielo che governa la notte',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_9',
    nome: 'Due sere di seguito',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDiSeguito('tramonto', 2),
    frase: 'Due Rune del Tramonto in due sere consecutive.',
    posizione: 9,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_10',
    nome: 'Due modi di gettare',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const VarietaDelDettaglio('gettata', 'modo', 2),
    frase: 'Due dei quattro modi della gettata, provati almeno una volta.',
    posizione: 10,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: 'I modi della gettata',
    eGrande: false,
    eos: 10,
    fascia: 'Primi giorni',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_11',
    nome: 'MALKUTH, IL REGNO',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GradiniAlleSpalle('albero', 1),
    frase: 'Dieci gradini alle spalle: si accende col primo gesto di Caligo dopo il decimo.',
    posizione: 11,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: true,
    eos: 40,
    fascia: 'Primi giorni',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_12',
    nome: 'Sotto la Luna nuova',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.lunaNuova, conGesto: 'gettata'),
    frase: 'Una gettata compiuta nella notte di Luna nuova.',
    posizione: 12,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_13',
    nome: 'Tre sere di seguito',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDiSeguito('tramonto', 3),
    frase: 'Tre Rune del Tramonto in tre sere consecutive.',
    posizione: 13,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_14',
    nome: 'La notte compiuta',
    famiglia: FamigliaDelTraguardo.giornata,
    condizione: const GestiNelloStessoGiorno(['tramonto', 'sogno']),
    frase: 'Runa del Tramonto, Sigillo del Sogno e Sigillo nello stesso giorno.',
    posizione: 14,
    percheConta: FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_15',
    nome: 'Tutti i modi di gettare',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const VarietaDelDettaglio('gettata', 'modo', 4),
    frase: 'I quattro modi della gettata, provati almeno una volta.',
    posizione: 15,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_16',
    nome: 'La runa che ti cerca',
    famiglia: FamigliaDelTraguardo.memoria,
    condizione: const CoincidenzaDelDettaglio('tramonto', 'runa', 2),
    frase: 'La stessa runa esce in due gettate diverse.',
    posizione: 16,
    percheConta: FamigliaDelTraguardo.memoria.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_17',
    nome: 'Il primo frutto condiviso',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const GestoDelCerchio('condivisione_frutto', 1),
    frase: 'Condividi per la prima volta un traguardo dell\'Albero.',
    posizione: 17,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: 'La condivisione',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_18',
    nome: 'Sette giorni nel Cerchio',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDiSeguito('presenza', 7),
    frase: 'Sette giorni di presenza consecutivi, qualunque gesto conti.',
    posizione: 18,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_19',
    nome: 'Il primo ritorno',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const RitornoDopoAssenza(3),
    frase: 'Torni nel Cerchio dopo almeno tre giorni di assenza.',
    posizione: 19,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_20',
    nome: 'Il primo quarto',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.primoQuarto, conGesto: 'sigillo'),
    frase: 'Un Sigillo dell\'Intenzione tracciato sotto il primo quarto di Luna.',
    posizione: 20,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_21',
    nome: 'Il sogno riletto',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('sogno', 7),
    frase: 'Rileggi un tuo sogno almeno sette giorni dopo averlo scritto.',
    posizione: 21,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: 'La memoria del Cerchio',
    eGrande: false,
    eos: 20,
    fascia: 'Prima settimana',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_22',
    nome: 'YESOD, IL FONDAMENTO',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GradiniAlleSpalle('albero', 21),
    frase: 'Ventun gradini alle spalle: si accende col primo gesto di Caligo dopo il ventunesimo.',
    posizione: 22,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: true,
    eos: 60,
    fascia: 'Prima settimana',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_23',
    nome: 'Una settimana di sere',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDiSeguito('tramonto', 7),
    frase: 'Sette Rune del Tramonto in sette sere consecutive.',
    posizione: 23,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_24',
    nome: 'Dodici rune diverse',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const VarietaDelDettaglio('tramonto', 'runa', 12),
    frase: 'Metà dell\'Elder Futhark uscita almeno una volta nelle tue gettate.',
    posizione: 24,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_25',
    nome: 'La notte del solstizio',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.solstizio, conGesto: 'tramonto'),
    frase: 'Una Runa del Tramonto nel giorno di un solstizio.',
    posizione: 25,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_26',
    nome: 'Il ritorno dopo una settimana',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const RitornoDopoAssenza(7),
    frase: 'Torni nel Cerchio dopo almeno sette giorni di assenza.',
    posizione: 26,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_27',
    nome: 'Tre frutti condivisi',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const GestoDelCerchio('condivisione_frutto', 3),
    frase: 'Tre traguardi dell\'Albero condivisi.',
    posizione: 27,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_28',
    nome: 'Quattordici giorni nel Cerchio',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDiSeguito('presenza', 14),
    frase: 'Due settimane di presenza consecutive.',
    posizione: 28,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_29',
    nome: 'Il presagio che torna',
    famiglia: FamigliaDelTraguardo.giornata,
    condizione: const Dormiente('cal_29', 'il tramonto passa la runa incisa ma non il presagio: servirebbe un dettaglio che la scena oggi non manda'),
    frase: 'Lo stesso presagio riconosciuto in tre sere, nell\'arco di tre settimane.',
    posizione: 29,
    percheConta: FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: true,
  ),
  Traguardo(
    id: 'cal_30',
    nome: 'Saturno torna indietro',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.saturnoRetrogrado, conGesto: 'sogno'),
    frase: 'Un Sigillo del Sogno durante un Saturno retrogrado.',
    posizione: 30,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_31',
    nome: 'Il sigillo nelle tre Lune',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const Dormiente('cal_31', 'la fase lunare non viaggia coi dettagli del gesto: servirebbe che la scena la passasse. È un dettaglio nuovo'),
    frase: 'Un Sigillo dell\'Intenzione tracciato sotto tre fasi lunari diverse.',
    posizione: 31,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: true,
  ),
  Traguardo(
    id: 'cal_32',
    nome: 'Il giorno affidato alle pietre',
    famiglia: FamigliaDelTraguardo.giornata,
    condizione: const GestiNelloStessoGiorno(['tramonto', 'gettata', 'sogno']),
    frase: 'Gettata, Runa del Tramonto e Sigillo del Sogno nello stesso giorno.',
    posizione: 32,
    percheConta: FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 30,
    fascia: 'Primo mese',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_33',
    nome: 'TIPHERETH, LA BELLEZZA',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GradiniAlleSpalle('albero', 32),
    frase: 'Trentadue gradini alle spalle: si accende col primo gesto di Caligo dopo il trentaduesimo.',
    posizione: 33,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: true,
    eos: 80,
    fascia: 'Primo mese',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_34',
    nome: 'Trenta giorni nel Cerchio',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDiSeguito('presenza', 30),
    frase: 'Un mese di presenza consecutiva.',
    posizione: 34,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_35',
    nome: 'Tutte le ventiquattro rune',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const VarietaDelDettaglio('tramonto', 'runa', 24),
    frase: 'Ogni runa dell\'Elder Futhark uscita almeno una volta.',
    posizione: 35,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_36',
    nome: 'Marte torna indietro',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.marteRetrogrado, conGesto: 'gettata'),
    frase: 'Una gettata durante un Marte retrogrado.',
    posizione: 36,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_37',
    nome: 'Il ritorno dopo due settimane',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const RitornoDopoAssenza(14),
    frase: 'Torni nel Cerchio dopo almeno quattordici giorni di assenza.',
    posizione: 37,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_38',
    nome: 'Sette frutti condivisi',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const GestoDelCerchio('condivisione_frutto', 7),
    frase: 'Sette traguardi dell\'Albero condivisi.',
    posizione: 38,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_39',
    nome: 'La Luna nuova nel tuo segno',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.lunaNuovaNelTuoSegno, conGesto: 'gettata'),
    frase: 'Una gettata nella notte in cui la Luna nuova cade nel tuo segno.',
    posizione: 39,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_40',
    nome: 'Ventuno sere di seguito',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDiSeguito('tramonto', 21),
    frase: 'Tre settimane di Rune del Tramonto consecutive.',
    posizione: 40,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_41',
    nome: 'Il transito su Marte',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.transitoSuMarte, conGesto: 'gettata'),
    frase: 'Una gettata mentre un pianeta transita sul tuo Marte di nascita.',
    posizione: 41,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_42',
    nome: 'Tre sogni che si somigliano',
    famiglia: FamigliaDelTraguardo.ampiezza,
    condizione: const GestiCompiuti('sogno', 3),
    frase: 'Tre Riti del Sogno che il Cerchio riconosce vicini fra loro.',
    posizione: 42,
    percheConta: FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_43',
    nome: 'Giove torna diretto',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.gioveDiretto, conGesto: 'sigillo'),
    frase: 'Un Sigillo dell\'Intenzione nel giorno in cui Giove torna diretto.',
    posizione: 43,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 45,
    fascia: 'La stagione',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_44',
    nome: 'BINAH, LA COMPRENSIONE',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GradiniAlleSpalle('albero', 43),
    frase: 'Quarantatré gradini alle spalle: si accende col primo gesto di Caligo dopo il quarantatreesimo.',
    posizione: 44,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: true,
    eos: 100,
    fascia: 'La stagione',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_45',
    nome: 'Sessanta giorni nel Cerchio',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDiSeguito('presenza', 60),
    frase: 'Due mesi di presenza consecutiva.',
    posizione: 45,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_46',
    nome: 'Saturno torna diretto',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const FinestraDelCielo(EventiDelCielo.saturnoDiretto, conGesto: 'sogno'),
    frase: 'Un Sigillo del Sogno nel giorno in cui Saturno torna diretto.',
    posizione: 46,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_47',
    nome: 'Tutte le arti di Caligo in un giorno',
    famiglia: FamigliaDelTraguardo.giornata,
    condizione: const GestiNelloStessoGiorno(['tramonto', 'gettata', 'sogno', 'animale_guida']),
    frase: 'Gettata, Runa del Tramonto, Sigillo del Sogno, Sigillo e Animale Guida nello stesso giorno.',
    posizione: 47,
    percheConta: FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_48',
    nome: 'Dodici frutti condivisi',
    famiglia: FamigliaDelTraguardo.cerchio,
    condizione: const GestoDelCerchio('condivisione_frutto', 12),
    frase: 'Dodici traguardi dell\'Albero condivisi.',
    posizione: 48,
    percheConta: FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_49',
    nome: 'Quaranta sere di seguito',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDiSeguito('tramonto', 40),
    frase: 'Quaranta Rune del Tramonto consecutive.',
    posizione: 49,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_50',
    nome: 'Le dodici Lune nuove',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const Dormiente('cal_50', 'la costanza LUNGA su un evento del cielo (dodici Lune di seguito) chiede una memoria per evento che il diario non tiene: si conta la serie dei GIORNI, non quella degli eventi'),
    frase: 'Dodici Lune nuove di seguito con una gettata in ciascuna.',
    posizione: 50,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
  ),
  Traguardo(
    id: 'cal_51',
    nome: 'Il ritorno dopo un mese',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const RitornoDopoAssenza(30),
    frase: 'Torni nel Cerchio dopo almeno trenta giorni di assenza.',
    posizione: 51,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_52',
    nome: 'Novanta giorni nel Cerchio',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const GiorniDiSeguito('presenza', 90),
    frase: 'Tre mesi di presenza consecutiva.',
    posizione: 52,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: false,
  ),
  Traguardo(
    id: 'cal_53',
    nome: 'L\'eclissi di Luna',
    famiglia: FamigliaDelTraguardo.cielo,
    condizione: const Dormiente('cal_53', 'DORMIENTE: il motore delle eclissi non esiste ancora.'),
    frase: 'Un Sigillo del Sogno nella notte di un\'eclissi di Luna.',
    posizione: 53,
    percheConta: FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
  ),
  Traguardo(
    id: 'cal_54',
    nome: 'L\'anno delle pietre',
    famiglia: FamigliaDelTraguardo.ritorno,
    condizione: const Dormiente('cal_54', 'il diario tiene i giorni e le serie, non i gesti mese per mese: "un gesto ogni mese per un anno" non è verificabile'),
    frase: 'Un anno dalla tua prima gettata, con almeno una gettata ogni mese.',
    posizione: 54,
    percheConta: FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: false,
    eos: 55,
    fascia: 'L\'anno',
    dormiente: true,
  ),
  Traguardo(
    id: 'cal_55',
    nome: 'KETHER, LA CORONA',
    famiglia: FamigliaDelTraguardo.profondita,
    condizione: const GradiniAlleSpalle('albero', 54),
    frase: 'Tutti i gradini alle spalle: si accende col primo gesto di Caligo dopo l\'ultimo.',
    posizione: 55,
    percheConta: FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
    cosaApre: '',
    eGrande: true,
    eos: 130,
    fascia: 'L\'anno',
    dormiente: false,
  ),
];
