import 'eventi_del_cielo.dart';
import 'traguardo.dart';

/// LA COSTELLAZIONE PERSONALE, il sentiero di Medora.
///
/// Le Stelle del Cammino sono i cinquanta traguardi piccoli, le Costellazioni
/// sono i cinque grandi. Il tono e' quello di Medora: il cielo che osserva, la
/// carta che si legge, il tempo che si dispone.
///
/// **Questo e' un file di DATI.** Nessuna logica vive qui: le condizioni sono
/// oggetti tipizzati definiti in `traguardo.dart`, e cosi' le prove possono
/// contare le famiglie, misurare quanti traguardi non si chiudono in giornata,
/// sommare gli Eos e accorgersi se due traguardi dicono la stessa cosa.
///
/// I GESTI DI QUESTO SENTIERO: `stesa` (una stesa di tarocchi), `oroscopo`,
/// `sinastria`, `oracolo` (il dono del giorno di Medora), `consulto_medora`,
/// `carta_natale`. Piu' i gesti comuni a tutti: `alba`, `soffio`, `tramonto`,
/// `presenza`.
Traguardo _t(
  String id,
  String nome,
  FamigliaDelTraguardo famiglia,
  CondizioneDelTraguardo condizione,
  String frase,
  int posizione,
  String percheConta,
  String cosaApre,
) =>
    Traguardo(
      id: id,
      nome: nome,
      famiglia: famiglia,
      condizione: condizione,
      frase: frase,
      posizione: posizione,
      percheConta: percheConta,
      cosaApre: cosaApre,
    );

/// Lo stesso, per i cinque GRANDI: il dato dice che sono grandi, cosi' la
/// posizione non deve indovinarlo.
Traguardo _g(
  String id,
  String nome,
  FamigliaDelTraguardo famiglia,
  CondizioneDelTraguardo condizione,
  String frase,
  int posizione,
  String percheConta,
  String cosaApre,
) =>
    Traguardo(
      id: id,
      nome: nome,
      famiglia: famiglia,
      condizione: condizione,
      frase: frase,
      posizione: posizione,
      percheConta: percheConta,
      cosaApre: cosaApre,
      eGrande: true,
    );

final List<Traguardo> sentieroDellaCostellazione = [
  // I TRE AGGANCIO, uguali sui tre sentieri per decisione: sono l'identita'
  // che si completa, e completarla vale su ogni cammino.
  _t('med_1', 'La tua carta è nata', FamigliaDelTraguardo.identita,
      const PezzoDellIdentita('carta_natale'),
      'La tua carta natale è calcolata: da qui in poi il cielo parla di te e non di tutti.',
      1,
      'è quasi sempre il momento in cui l\'app entra in una conversazione reale con qualcuno che ti sta vicino.',
      'la Sinastria con una persona vera invece che con un personaggio famoso.'),
  _t('med_2', 'Il tuo Angelo ha un nome', FamigliaDelTraguardo.identita,
      const PezzoDellIdentita('angelo_custode'),
      'Il tuo Angelo Custode ha un nome e adesso lo sai: non era un angelo qualunque.',
      2,
      FamigliaDelTraguardo.identita.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Il tuo Animale ti ha trovato.'),
  _t('med_3', 'Il cielo di oggi ti riguarda', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('oracolo', 1),
      'Il primo Oracolo letto fino all’ultima riga: il cielo di oggi ti ha trovato attento.',
      3,
      'è il primo momento in cui il cielo smette di essere un disegno e diventa una cosa che parla di te, oggi.',
      'Il ritorno di domani: l’Oracolo cambia col cielo e domani non dirà la stessa cosa.'),
  _t('med_4', 'Il primo giorno intero', FamigliaDelTraguardo.giornata,
      const GestiNelloStessoGiorno(['alba', 'oracolo']),
      'Alba e Oracolo nello stesso giorno: hai aperto la giornata e l\'hai fatta parlare.',
      4,
      FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Tre stese.'),
  _t('med_5', 'Tre stese', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('stesa', 3),
      'Tre stese di tarocchi: le carte cominciano a riconoscere la tua mano.',
      5,
      'è la prima volta che scegli tu invece di ricevere e la scelta cambia il peso del responso.',
      'il consiglio di Medora e la domanda che ti lascia per il giorno dopo.'),
  _t('med_6', 'Sotto la Luna piena', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.lunaPiena, conGesto: 'stesa'),
      'Hai steso le carte sotto la Luna piena: il cielo era al colmo e tu eri qui.',
      6,
      FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Due albe di seguito.'),
  _t('med_7', 'Due albe di seguito', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('oracolo', 2),
      'Due giorni di seguito con l\'Oracolo: la seconda volta è quella che conta.',
      7,
      FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Due arti in un giorno.'),
  _t('med_8', 'Due arti in un giorno', FamigliaDelTraguardo.ampiezza,
      const GestiNelloStessoGiorno(['stesa', 'oroscopo']),
      'Carte e Oroscopo nello stesso giorno: due sguardi sullo stesso cielo.',
      8,
      FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Cinque stese in giorni diversi.'),
  _t('med_9', 'Cinque stese in giorni diversi', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('stesa', 5, inGiorniDiversi: true),
      'Cinque stese in cinque giorni diversi: non hai cercato una risposta, hai preso un\'abitudine.',
      9,
      'cinque stese sono la quantità minima perché lo storico dica qualcosa che non sapevi.',
      'la statistica delle tue carte ricorrenti.'),
  _t('med_10', 'Il tuo segno sotto la Luna', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.lunaNelTuoSegno,
          conGesto: 'oroscopo'),
      'La Luna era nel tuo segno e tu hai letto il tuo cielo: coincidenza cercata, non capitata.',
      10,
      FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, La Costellazione del Ritorno.'),
  _t('med_11', 'Il Cerchio ricorda', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('momenti', 10),
      'Dieci tuoi momenti custoditi: il Cerchio ha cominciato a ricordarti.',
      11,
      FamigliaDelTraguardo.memoria.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Tre giorni di seguito.'),
  _t('med_12', 'Tre giorni di seguito', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('oracolo', 3),
      'Tre giorni di seguito: il terzo è quello che trasforma una prova in un rito.',
      12,
      FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Dieci stese.'),
  _t('med_13', 'Dieci stese', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('stesa', 10, inGiorniDiversi: true),
      'Dieci stese in dieci giorni: le carte non ti sorprendono più, ti rispondono.',
      13,
      'dieci stese sono un archivio e un archivio si rilegge.',
      'la rilettura delle tue prime stese con quello che sai adesso.'),
  _t('med_14', 'Mercurio torna indietro', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.mercurioRetrogrado,
          conGesto: 'oroscopo'),
      'Hai letto il tuo cielo mentre Mercurio tornava indietro: si guarda meglio quando tutto rallenta.',
      14,
      'il retrogrado non è un guasto, è un ritorno: capirlo toglie metà della paura che gira sui social.',
      'l\'avviso dei periodi retrogradi nel dono del mattino.'),
  _t('med_15', 'Il giorno chiuso', FamigliaDelTraguardo.giornata,
      const GestiNelloStessoGiorno(['oracolo', 'tramonto']),
      'Oracolo al mattino e runa al tramonto: hai chiuso il cerchio del giorno.',
      15,
      FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Tre arti diverse.'),
  _t('med_16', 'Tre arti diverse', FamigliaDelTraguardo.ampiezza,
      const GestiNelloStessoGiorno(['stesa', 'oroscopo', 'sinastria']),
      'Carte, Oroscopo e Sinastria in un giorno solo: hai guardato il cielo da tre finestre.',
      16,
      'cento giorni di cielo sono la tua storia, non più la tua abitudine.',
      'la Costellazione personale, il traguardo più alto del sentiero.'),
  _t('med_17', 'Cinque giorni di seguito', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('oracolo', 5),
      'Cinque giorni di seguito: adesso il Cerchio fa parte della tua settimana.',
      17,
      FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Tutte le chiavi della stesa.'),
  _t('med_18', 'Tutte le chiavi della stesa', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('stesa_tipo_diverso', 4),
      'Hai provato tutte le chiavi di lettura della stesa: nessuna carta ha più un solo modo di parlare.',
      18,
      'hai visto lo stesso mazzo rispondere in tre modi diversi: è la prova che il metodo conta quanto le carte.',
      'la scelta della chiave diventa parte della domanda e non un\'impostazione.'),
  _t('med_19', 'Il Sole nel tuo segno', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.soleNelTuoSegno,
          conGesto: 'carta_natale'),
      'Hai riaperto la tua carta mentre il Sole attraversava il tuo segno: il mese che è tuo.',
      19,
      FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Una domanda ripresa.'),
  _t('med_20', 'Una domanda ripresa', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('rilettura', 1, dopoGiorni: 30),
      'Hai riletto un consulto di un mese fa: il tuo passato ti ha risposto una seconda volta.',
      20,
      FamigliaDelTraguardo.memoria.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, La Costellazione della Lettura.'),
  _t('med_21', 'Il giorno pieno', FamigliaDelTraguardo.giornata,
      const GestiNelloStessoGiorno(['alba', 'soffio', 'oracolo', 'tramonto']),
      'Tutti e quattro i doni del giorno, nello stesso giorno: il cerchio è intero.',
      21,
      FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Mercurio torna diretto.'),
  _t('med_22', 'Mercurio torna diretto', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.mercurioDiretto,
          conGesto: 'stesa'),
      'Mercurio è tornato diretto e tu hai steso le carte: il pensiero riprende la sua strada.',
      22,
      FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Venti stese.'),
  _t('med_23', 'Venti stese', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('stesa', 20, inGiorniDiversi: true),
      'Venti stese in venti giorni: questa non è curiosità, è pratica.',
      23,
      FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Il ritorno dopo tre giorni.'),
  _t('med_24', 'Il ritorno dopo tre giorni', FamigliaDelTraguardo.ritorno,
      const RitornoDopoAssenza(3),
      'Sei tornato dopo tre giorni di silenzio: il Cerchio ti aspettava nel punto in cui eri rimasto.',
      24,
      FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Lo stesso tema, tre Maestri.'),
  _t('med_25', 'Lo stesso tema, tre Maestri', FamigliaDelTraguardo.ampiezza,
      const GestiNelloStessoGiorno(
          ['consulto_medora', 'consulto_caligo', 'consulto_aura']),
      'Hai chiesto lo stesso tema ai tre Maestri: tre letture, un cielo solo.',
      25,
      'non è più l\'app che ti spiega il cielo, è il cielo che comincia a raccontare te.',
      'la quarta Costellazione e la biografia celeste dello Specchio dell\'Anima.'),
  _t('med_26', 'Il transito sul tuo Sole', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.transitoSulSole,
          conGesto: 'oroscopo'),
      'Un pianeta è passato sul tuo Sole e tu te ne sei accorto: pochi lo fanno.',
      26,
      'i pianeti lenti sono quelli che cambiano la vita e si vedono solo se li guardi più di una volta.',
      'l\'avviso del transito attivo comincia a comparire nel Rito dell\'Alba.'),
  _t('med_27', 'Il Passaporto pieno', FamigliaDelTraguardo.identita,
      const PezzoDellIdentita('passaporto'),
      'Il tuo Cosmic Passport è completo: nome, cielo, numero, tutto al suo posto.',
      27,
      'è il tuo ritratto celeste in una schermata sola, la cosa che mostrerai a qualcuno prima di spiegare cos\'è l\'app.',
      'la Sinastria, che ha bisogno del tuo passaporto per confrontarti con chiunque.'),
  _t('med_28', 'La carta che torna', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('carta_ripetuta', 3),
      'La stessa carta è uscita tre volte: quando insiste, non è più un caso.',
      28,
      'una carta che ritorna non è una coincidenza da spiegare, è un tema da guardare.',
      'il Filo dei Temi la segnala e Medora la nomina.'),
  _t('med_29', 'Il Maestro ti riprende', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('ripresa', 1),
      'Medora ha ripreso una cosa che le avevi detto: non era una risposta qualunque, era la tua.',
      29,
      FamigliaDelTraguardo.memoria.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, L\'Ascendente toccato.'),
  _t('med_30', 'L\'Ascendente toccato', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.transitoSullAscendente,
          conGesto: 'carta_natale'),
      'Un transito è passato sul tuo Ascendente mentre lo guardavi: il tuo punto più personale, in movimento.',
      30,
      FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, La Costellazione del Cielo Vero.'),
  _t('med_31', 'Una settimana intera', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('oracolo', 7),
      'Sette giorni di seguito senza saltarne uno: la settimana è chiusa.',
      31,
      FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Due giorni interi.'),
  _t('med_32', 'Due giorni interi', FamigliaDelTraguardo.giornata,
      const GestiCompiuti('giorno_intero', 2, inGiorniDiversi: true),
      'Due giornate chiuse per intero: non è stata una volta sola.',
      32,
      FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Trenta stese.'),
  _t('med_33', 'Trenta stese', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('stesa', 30, inGiorniDiversi: true),
      'Trenta stese: le carte hanno smesso di essere uno strumento e sono diventate una lingua.',
      33,
      FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, La prima stella condivisa.'),
  _t('med_34', 'La prima stella condivisa', FamigliaDelTraguardo.cerchio,
      const GestoDelCerchio('condivisione_stella', 1),
      'Hai condiviso la tua prima Stella del Cammino: il cielo si guarda meglio in due.',
      34,
      FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, L\'equinozio.'),
  _t('med_35', 'L\'equinozio', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.equinozio),
      'Eri qui nel giorno dell\'equinozio, quando la luce e il buio si guardano alla pari.',
      35,
      FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, I tre domini.'),
  _t('med_36', 'I tre domini', FamigliaDelTraguardo.ampiezza,
      const GestiNelloStessoGiorno(
          ['dominio_medora', 'dominio_caligo', 'dominio_aura']),
      'Hai visitato i tre domini in un giorno: conosci tutto il Cerchio, non solo la tua stanza.',
      36,
      FamigliaDelTraguardo.ampiezza.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, L\'ora dell\'Oracolo.'),
  _t('med_37', 'L\'ora dell\'Oracolo', FamigliaDelTraguardo.ritorno,
      const GestoNellOraGiusta('oracolo', 'alba', quanteVolte: 3),
      'Tre volte hai chiesto l\'Oracolo all\'alba vera: l\'ora giusta non è un dettaglio.',
      37,
      FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Un tema che torna.'),
  _t('med_38', 'Un tema che torna', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('tema', 3, dopoGiorni: 14),
      'Lo stesso tema è tornato tre volte in due settimane: il Cerchio l\'ha visto prima di te.',
      38,
      FamigliaDelTraguardo.memoria.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Tre stelle condivise.'),
  _t('med_39', 'Tre stelle condivise', FamigliaDelTraguardo.cerchio,
      const GestoDelCerchio('condivisione_stella', 3),
      'Tre Stelle condivise: qualcuno guarda il tuo cielo insieme a te.',
      39,
      FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Cinquanta stese.'),
  _t('med_40', 'Cinquanta stese', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('stesa', 50, inGiorniDiversi: true),
      'Cinquanta stese in cinquanta giorni diversi: pochissimi arrivano qui.',
      40,
      FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, La Costellazione della Memoria.'),
  _t('med_41', 'La Luna piena nel tuo segno', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.lunaPienaNelTuoSegno),
      'La Luna piena è caduta nel tuo segno e tu c\'eri: capita una volta l\'anno.',
      41,
      FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Sette giorni interi.'),
  _t('med_42', 'Sette giorni interi', FamigliaDelTraguardo.giornata,
      const GestiCompiuti('giorno_intero', 7, inGiorniDiversi: true),
      'Sette giornate chiuse per intero: una settimana senza lasciare niente a metà.',
      42,
      FamigliaDelTraguardo.giornata.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, L\'ora esatta.'),
  _t('med_43', 'L\'ora esatta', FamigliaDelTraguardo.identita,
      const PezzoDellIdentita('ora_di_nascita'),
      'Hai dato l\'ora esatta della tua nascita: Ascendente e Case escono dal velo.',
      43,
      FamigliaDelTraguardo.identita.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Il primo invito.'),
  _t('med_44', 'Il primo invito', FamigliaDelTraguardo.cerchio,
      const GestoDelCerchio('invito', 1),
      'Hai portato qualcuno nel Cerchio: il tuo primo invito, nato senza nessun obbligo.',
      44,
      FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Due settimane di seguito.'),
  _t('med_45', 'Due settimane di seguito', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('oracolo', 14),
      'Quattordici giorni di seguito: due settimane intere senza un buco.',
      45,
      FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Il ritorno dopo due settimane.'),
  _t('med_46', 'Il ritorno dopo due settimane', FamigliaDelTraguardo.ritorno,
      const RitornoDopoAssenza(14),
      'Sei tornato dopo due settimane: il Cerchio non ti ha cancellato, ti ha tenuto il posto.',
      46,
      FamigliaDelTraguardo.ritorno.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Cento momenti.'),
  _t('med_47', 'Cento momenti', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('momenti', 100, dopoGiorni: 30),
      'Cento tuoi momenti custoditi in un mese: adesso il Cerchio ti conosce davvero.',
      47,
      FamigliaDelTraguardo.memoria.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Sette stelle condivise.'),
  _t('med_48', 'Sette stelle condivise', FamigliaDelTraguardo.cerchio,
      const GestoDelCerchio('condivisione_stella', 7),
      'Sette Stelle condivise: il tuo cammino illumina anche fuori.',
      48,
      FamigliaDelTraguardo.cerchio.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Tutte le arti di Medora.'),
  _t('med_49', 'Tutte le arti di Medora', FamigliaDelTraguardo.ampiezza,
      const GestiNelloStessoGiorno(
          ['stesa', 'oroscopo', 'sinastria', 'carta_natale']),
      'Tutte le arti di Medora in un giorno solo: il suo dominio non ha più angoli bui.',
      49,
      'un responso che esce dall\'app è un responso che hai riconosciuto come tuo.',
      'il bonus in Eos graduato per valore della condivisione.'),
  _t('med_50', 'Il tuo ritorno solare', FamigliaDelTraguardo.cielo,
      const FinestraDelCielo(EventiDelCielo.ritornoSolare),
      'Il Sole è tornato dove stava quando sei nato: tu eri qui a vederlo mentre il tuo anno ricomincia.',
      50,
      'è il giorno in cui il Sole torna dove era quando sei nato: è l\'unico anniversario astronomico che ti riguarda davvero.',
      'la lettura del ritorno solare e la card del compleanno.'),

  // LE CINQUE COSTELLAZIONI, i grandi traguardi. Sempre visibili in anticipo,
  // modello tessera punti: si sa dove si sta andando fin dal primo giorno.
  _g('med_g10', 'La Costellazione del Ritorno', FamigliaDelTraguardo.ritorno,
      const GiorniDiSeguito('presenza', 7),
      'Sette giorni di presenza hanno acceso la Costellazione del Ritorno: la prima figura del tuo cielo.',
      10,
      'sette giorni bastano perché il cielo cambi abbastanza da farti vedere che il testo cambia con lui.',
      'la prima Costellazione si compone.'),
  _g('med_g20', 'La Costellazione della Lettura', FamigliaDelTraguardo.profondita,
      const GestiCompiuti('stesa', 15, inGiorniDiversi: true),
      'Quindici giorni di carte hanno acceso la Costellazione della Lettura: leggi, non consulti più.',
      20,
      FamigliaDelTraguardo.profondita.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Il giorno pieno.'),
  _g('med_g30', 'La Costellazione del Cielo Vero',
      FamigliaDelTraguardo.cielo,
      const GestiCompiuti('finestra_del_cielo', 5),
      'Cinque finestre del cielo colte al volo: la Costellazione del Cielo Vero è tua, di quelle che non si possono affrettare.',
      30,
      FamigliaDelTraguardo.cielo.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, Una settimana intera.'),
  _g('med_g40', 'La Costellazione della Memoria', FamigliaDelTraguardo.memoria,
      const MemoriaDelCerchio('fatti', 30, dopoGiorni: 30),
      'Trenta fatti tuoi ricordati in un mese: la Costellazione della Memoria brilla di cose che hai detto.',
      40,
      FamigliaDelTraguardo.memoria.percheContaLaFamiglia,
      'Rende visibile in anticipo il traguardo che viene dopo, La Luna piena nel tuo segno.'),
  _g('med_g50', 'La Costellazione Compiuta', FamigliaDelTraguardo.identita,
      const GestiCompiuti('stella_accesa', 49),
      'Quarantanove Stelle accese: la Costellazione Compiuta è il tuo cielo intero, disegnato da te.',
      50,
      FamigliaDelTraguardo.identita.percheContaLaFamiglia,
      'Chiude il sentiero: da qui il cammino non ha più un dopo, ha un compiuto.'),
];
